### ISSUE TITLE
Scrollbar interval time

### ISSUE THREAD

**Issue by tr14466** [AnyChart/AnyChart#100]
Hi,
You can display the start and end times of the current scrollbar section, and then display the title.
Thank you!
![ssssss](https://user-images.githubusercontent.com/53610056/63940290-c11aa000-ca9b-11e9-9152-da75a5fdd549.png)

**Comment by Shestac92** [comment]
@tr14466 
Yes, it's possible with using listeners and getting current min/max from the xScale. For details, check [the sample](https://playground.anychart.com/GUA8vZJc/0).

**Comment by tr14466** [comment]
> @tr14466
> Yes, it's possible with using listeners and getting current min/max from the xScale. For details, check [the sample](https://playground.anychart.com/GUA8vZJc/0).

Thank you!
