### ISSUE TITLE
What is the event name of the graphical drag

### ISSUE THREAD

**Issue by tr14466** [AnyChart/AnyChart#101]
Hi,
What is the event name of the graphical drag.
![sssssss](https://user-images.githubusercontent.com/53610056/64007904-98e87b00-cb47-11e9-8636-8715515fc740.png)

**Comment by Shestac92** [comment]
@tr14466 
In case, when you need to listen to only scroller actions you can use `scrollerChange` event.
If you need to handle mouse drag too, which means visible range change, you can use `selectedRangeChange ` event. This event dispatches when the user uses the scroller or dragging the plot. For details, check [the sample](https://playground.anychart.com/lwsU0JLX).

Also, the API provides some types of similar events, probably you will find them useful. Check the full list [here](https://api.anychart.com/anychart.enums.EventType#category-stock-event-types).

**Comment by tr14466** [comment]
> @tr14466
> In case, when you need to listen to only scroller actions you can use `scrollerChange` event.
> If you need to handle mouse drag too, which means visible range change, you can use `selectedRangeChange ` event. This event dispatches when the user uses the scroller or dragging the plot. For details, check [the sample](https://playground.anychart.com/lwsU0JLX).
> 
> Also, the API provides some types of similar events, probably you will find them useful. Check the full list [here](https://api.anychart.com/anychart.enums.EventType#category-stock-event-types).

Ok,Tks.
