### ISSUE TITLE
IE11 has many problems

### ISSUE THREAD

**Issue by tr14466** [AnyChart/AnyChart#102]
Hi,
There are several problems in opening graphics with IE11.
1. Unable to edit and modify
2. Invalid right mouse button and suspension
   
anychart.exports.clientside({ enabled: false });
3. Problems with exporting images using the server: DOM7011 code on this page disables reverse and forward huanc;
Can't exports images.
![ssssssss](https://user-images.githubusercontent.com/53610056/64019628-42d50100-cb62-11e9-86b4-82c0dea7a9a9.png)

**Comment by Shestac92** [comment]
@tr14466 
The 1st and 2nd problem occurs only in the playground. You can run your charts locally and it will solve the issue. The playground website uses some modern solutions which are not fully compatible with IE11.
The 3rd problem should be reproduced locally. Please, provide a screenshot of the console message.

**Comment by tr14466** [comment]
> @tr14466
> The 1st and 2nd problem occurs only in the playground. You can run your charts locally and it will solve the issue. The playground website uses some modern solutions which are not fully compatible with IE11.
> The 3rd problem should be reproduced locally. Please, provide a screenshot of the console message.

This is the official example link.
https://playground.anychart.com/docs/v8/samples/STOCK_Grouping_07

I downloaded this instance locally and added ‘anychart. exports. clientside (enabled: false})’ code.
Unable to export pictures when running under IE11
![ssssssssss](https://user-images.githubusercontent.com/53610056/64088276-3b387680-cd73-11e9-8c8d-234c252cb290.png)
![sssssssss](https://user-images.githubusercontent.com/53610056/64088395-ce71ac00-cd73-11e9-8f06-34c27defbb64.png)

**Comment by Shestac92** [comment]
@tr14466 
A few more steps required to enable loading exports via IE11.
1) Add the following line to rout the local running sample to the export server:
```
anychart.exports.server(https://export.anychart.com);
```
2) Open `Internet options` (IE11 settings), go to `Security` tab and decrease the security level. For tests, I almost switched off protected mode. Probably, medium or low level allows downloading exports. 

This is IE11 security issue as it's deprecated browser and it doesn't meet modern security and usability requirements.

**Comment by tr14466** [comment]
> 1. off protected mode

I switched off protected mode, IE11 allows downloading exports image.
Thank you, every good!
