### ISSUE TITLE
Create multi charts in multi containers

### ISSUE THREAD

**Issue by sky7st** [AnyChart/AnyChart#104]
The UI of my page is as follow pic:
![Untitled Diagram](https://user-images.githubusercontent.com/25301882/67360130-b3633180-f597-11e9-9c6b-218aa9ec8b41.png)

There's a main chart which's show the main data.
But I want to add several sub areas for my page.
There are some custom elements in the sub area(text, button, and chart)

```
<div class="sub-area">
    <div class="title"> My Title</div>
    <div class="sub-chart-container-1"></div>
    <button class="submit">submit</button>
</div>
```
Most example I found is drawing multi chart on one container.
But in my case, I have custom element between charts, so I might need multi containers.
How do I implement multi charts to multi containers?

BTW, I'm using stock chart.

**Comment by Shestac92** [comment]
@sky7st 
For your purpose, every chart (main or subChart) requires its own container. Then give to every chart container unique ID.
For example:
```
<div class="sub-area">
    <div class="title"> My Title</div>
    <div class="sub-chart-container-1" id="subChart1"></div>
    <button class="submit">submit</button>
</div>

<div class="sub-area">
    <div class="title"> My Title</div>
    <div class="sub-chart-container-2" id="subChart2"></div>
    <button class="submit">submit</button>
</div>
```
After that you can create separate charts in JS and apply them to the relevant container using those IDs:
```
var chart1 = anychart.stock();
// ....configuring chart1 code
chart1.container('subChart1').draw();

var chart2 = anychart.stock();
// ....configuring chart2 code
chart1.container('subChart2').draw();
```
