### ISSUE TITLE
TypeError: Cannot read property 'mb' of null at d3.sync

### ISSUE THREAD

**Issue by davidmcooper** [AnyChart/AnyChart#107]
Getting the following error in the console:  

`"TypeError: Cannot read property 'mb' of null at d3.sync" `

This code works fine with Anychart 8.6.0, but I'm seeing this issue using both Anychart 8.7.0 and 8.7.1 when using AnyStock and React 16.10.1.

**Comment by Shestac92** [comment]
@davidmcooper 
Please, can you provide more details about the issue? 

- the chart configuration code

- are you using the AnyChart-React plugin or plain AnyChart JS library?

**Comment by L-X-T** [comment]
AnyChart JS library V 8.7.1, same TypeError
