### ISSUE TITLE
gap in  Stock chart

### ISSUE THREAD

**Issue by parsa-xy** [AnyChart/AnyChart#108]
Hello, 
In the stock chart, while we input the real date on the chart there is no gap at the end chart which is one of the features which this chart really needs to have. I know that for not real data we can make it manually with adding some blank points but this is not available for real data. Please kindly find a solution for that or tell me an alternative method.
THank's
![Untitled](https://user-images.githubusercontent.com/57038782/71485954-cf4bb380-2824-11ea-8bf0-ac3a07435368.png)

**Comment by elizabet999** [comment]
I reported this bug a while ago, and after I understood that this problem hasn't been solved since 2017, it puts space between candles when we use chart.xScale() .maximumGap, I will also upload my photo.
I asked them many times to solve it, but no answer and solution so far.
![Screenshot 2019-12-27 at 15 36 05](https://user-images.githubusercontent.com/56912080/71517465-328a2400-28bf-11ea-8062-c493b26c381c.png)

**Comment by Pa22** [comment]
@Shestac92 Hello, Is there any update for this issue?

**Comment by Shestac92** [comment]
@Pa22 @elizabet999 
Thank you for the report!
Yes, this is already a known issue. We will provide the fix in future updates. I have linked this thread to a support ticket, so we will notify you when the fix becomes available.

**Comment by Pa22** [comment]
hello, any update regarding this issue after 4 months?

**Comment by Shestac92** [comment]
@Pa22 
Unfortunately, the ETA on the fix is not defined yet. It will be provided in future updates.

**Comment by Jennyana999** [comment]
Hello, is this resolved? or the project is canceled?
I see this issue is important to be fixed.

**Comment by Shestac92** [comment]
@Jennyana999 
Unfortunately, the fix is not scheduled yet. We are planning to solve the issue in future updates.

**Comment by sturdystablestalwart** [comment]
While the additional method was not added, there is a way to achieve this empty gap on the right side; it's shown in [the sample](https://playground.anychart.com/nws7RVU6).
Thank you for your report, and if you have any additional questions or requests, I'm here to help.
