### ISSUE TITLE
Mouse position in chart

### ISSUE THREAD

**Issue by elizabet999** [AnyChart/AnyChart#109]
When I move the mouse on the chart, it only shows me a point in candle, I want to make the mouse free to show me each point in chart not only one point.
please let me know if you have solution for that.

**Comment by Shestac92** [comment]
@elizabet999 
I'm afraid that I didn't get your idea correctly. Please, can you provide a detailed explanation or provide a screenshot with notes on it that describes what the chart must show according to the current cursor position?

**Comment by elizabet999** [comment]
Thanks I found the answer.
