### ISSUE TITLE
When data is added, the scroll starts to shift.

### ISSUE THREAD

**Issue by helloris25** [AnyChart/AnyChart#11]
This is very inconvenient when creating live charts, for example, a quotation chart.
This is because the scroll is tied to dates. To avoid this, you have to use the 'selectRange'. 
Can this be avoided and how to make a normal zoom without reference to the date?

![bug](https://cloud.githubusercontent.com/assets/3649203/25273410/58cbd31e-2694-11e7-9005-733f3f86ac10.gif)
![bug2](https://cloud.githubusercontent.com/assets/3649203/25273411/58cc15e0-2694-11e7-9133-eecbd8befdea.gif)

**Comment by maresha** [comment]
Hi!

You can try to set the range using scale minimum and maximum values, like
`chart.selectRange(chart.xScale().getMinimum()-10000000000,chart.xScale().getMaximum()+10000000000);
`

Like here: http://jsfiddle.net/0t6402gd/3/

It doesn't depend on the exact data, so it could help.

**Comment by maresha** [comment]
@helloris25 this feature will be included in the 8.0.0 version (ETA: Sep 2017) too. Please be assured we'll keep you updated on the progress.

**Comment by loki20beta** [comment]
@helloris25 now you can decide how scroller behaves on update using

- [Documentation on preserveSelectedRangeOnDataUpdate](https://docs.anychart.com/Stock_Charts/Scroller#preserve_selected_range)
- API:[https://api.anychart.com/8.0.0/anychart.charts.Stock#preserveSelectedRangeOnDataUpdate](https://api.anychart.com/8.0.0/anychart.charts.Stock#preserveSelectedRangeOnDataUpdate)
- [Sample](https://playground.anychart.com/api/8.0.0/charts/anychart.charts.Stock.preserveSelectedRangeOnDataUpdate-plain)
