### ISSUE TITLE
indicators size

### ISSUE THREAD

**Issue by elizabet999** [AnyChart/AnyChart#111]
When applying indicators, it takes half of the chart, and when another one is applied it takes 33% as I understood right about calculation of that.
So I want to apply indicator which must take over 25% of the chart not 50%, is it possible?

**Comment by Shestac92** [comment]
@elizabet999 
If the indicator is placed on a separate plot you can adjust the plot height. Check [the sample](https://playground.anychart.com/ysdySMxZ) for details.

**Comment by elizabet999** [comment]
Thanks, amazing.
