### ISSUE TITLE
scroller

### ISSUE THREAD

**Issue by elizabet999** [AnyChart/AnyChart#112]
Is it possible to change the height of scroller? if i want to make it shorter.
https://docs.anychart.com/Stock_Charts/Stock_Charts/Scroller
in this examples i can not find it.

**Comment by Shestac92** [comment]
@elizabet999 
You can achieve that using the `height()` method. 
For example, `chart.scroller().height('2%');` in percents or `chart.scroller().height(25);` in pixels.

**Comment by sathish151198** [comment]
> @elizabet999 You can achieve that using the `height()` method. For example, `chart.scroller().height('2%');` in percents or `chart.scroller().height(25);` in pixels.

Hi @Shestac92 
Is this same applicable for gantt chart? If not please provide a solution.
