### ISSUE TITLE
Last price

### ISSUE THREAD

**Issue by elizabet999** [AnyChart/AnyChart#114]
Is it possible to make the chart shines when it gets last price. I mean just a point can shine, it will look more like live chart. 
Or if we can use this diamond to our stockchart which can get the last price, we can make it super small. is it ppossible to use it?
https://playground.anychart.com/api/v8/graphics/vector/_samples/anychart.graphics.vector.primitives.diamond
which must be white color and super small and works in stockchart and stays there.

**Comment by Shestac92** [comment]
@elizabet999 
Technically you can pure Graphics to highlight new points but it can be challenging. I can suggest you using annotations for this purpose. For details, check [the sample](https://playground.anychart.com/jHr7f12Q/1).

**Comment by elizabet999** [comment]
Thanks, anyhow, using this code also give us a bug, the chart has a bugs when live data is applied. I hope you can fix it.
![Screenshot 2020-02-02 at 16 49 21](https://user-images.githubusercontent.com/56912080/73609181-3440b900-45dc-11ea-8ec8-b0b1a60967ef.png)

**Comment by Shestac92** [comment]
@elizabet999 
Thank you for the report! I have successfully reproduced the issue, I will forward it to our dev team and notify you about the fix.
As a temporary workaround, you can use `removeAllAnnotations()` method to resolve it. Please, note that it removes all annotations from the plot, take it into account. For details, check [the modified sample](https://playground.anychart.com/6uMbDbsf/0).

**Comment by Shestac92** [comment]
@elizabet999 
We can suggest a workaround to achieve the result you need. The idea is to reuse the same marker and simply update its position and show/hide it when the new point comes.
For details, check [the updated sample](https://playground.anychart.com/sTaKS8Uf/1).

**Comment by elizabet999** [comment]
perfect, was the best.
