### ISSUE TITLE
Event marker

### ISSUE THREAD

**Issue by elizabet999** [AnyChart/AnyChart#115]
This code has a bug when applied live data. 
Numbers or alphabet inside it make a copy of it self when it must be removed. And in general.
Otherwise, i need to reset the chart to delete them.
![20200128_114543](https://user-images.githubusercontent.com/56912080/73248410-fac71280-41c3-11ea-90d6-48d18b93d38b.jpg)

**Comment by Shestac92** [comment]
@elizabet999 
Thank you for your report!
This is a known issue and our team has prepared a fix for this. It will become available in the upcoming release (also, we will notify you).

**Comment by Shestac92** [comment]
@Datsotrade 
Yes, this issue was resolved. Use the latest version of the library v8.8.0
