### ISSUE TITLE
Shadow 

### ISSUE THREAD

**Issue by parsa-xy** [AnyChart/AnyChart#116]
Hello,
Is there any possibility if we could adjust shadow at the edges of each candles on the candle strike chart? I mean something like this: 
![Untitled](https://user-images.githubusercontent.com/57038782/73609153-f0e64a80-45db-11ea-9584-fe20c27e3d6b.png)

**Comment by Shestac92** [comment]
@Pa22 
I'm afraid that exactly the same not, but all available stroke settings you can in [the article](https://docs.anychart.com/Graphics/Stroke_Settings).
