### ISSUE TITLE
candlestick time

### ISSUE THREAD

**Issue by elizabet999** [AnyChart/AnyChart#118]
Hello, would you please let me know how we can change the candle time to 2 minutes or even 5 minutes or like 30 seconds?
because I get the api each 1 second I have 1 minute candle, how I can make it more or even less.

**Comment by Shestac92** [comment]
@elizabet999 
To achieve that you can override the default grouping behavior. [The grouping guide](https://docs.anychart.com/Stock_Charts/Data_Grouping#adjusting) gives all the required information and examples.

**Comment by elizabet999** [comment]
Will you please give me one example with button in candlestick? I tried a lot but couldnt make as I want.

**Comment by elizabet999** [comment]
@Shestac92 Precisely I want to have a button for that, not only with moving scrollbar. Thanks

**Comment by Shestac92** [comment]
@elizabet999 
For example, like [this](https://playground.anychart.com/y98Zq0m4).

**Comment by elizabet999** [comment]
@Shestac92 even your example doesnt work, beside that this is not candlestick. I want to make a button to have 1 minute, 5 minute, 10 minute. so that everytime I call, it can show me. I tried this one:
var grouping = chart.grouping();
    grouping.levels([
{unit: 'minute', count: 1},
{unit: 'minute', count: 5},
{unit: 'minute', count: 10},
{unit: 'minute', count: 15}
    ]);

but the problem is that it only listens to scroller, when I make a button, does not change and doesnt affect on that.

**Comment by Alez999** [comment]
I have the same problem for long time, candles can not be arranged in minutes only scroll can help.

**Comment by Shestac92** [comment]
@elizabet999 @Alez999 
In this case, there's no difference in series type, grouping works the same for all series types. Anyway, I modified my previous sample for using the candlestick series - https://playground.anychart.com/nBpUmxSY

If you apply an array of levels ()more than one) then the chart chooses the current level automatically. If you want to control the level manually you should always apply only one level in the array, just like it is shown in the sample.
