### ISSUE TITLE
How to use anychart maps with React

### ISSUE THREAD

**Issue by jimmy-e** [AnyChart/AnyChart#119]
Hi,

How are we supposed to get map anychart? Per the React examples [here](https://www.anychart.com/technical-integrations/samples/react-charts/), we should be adding a script tag that links to the anychart node modle, specifically the path `node_modules/anychart/dist/geodata/countries/australia/australia.js`. However, anychart's `dist` folder currently does not have any geodata, as seen [here](https://github.com/AnyChart/AnyChart/tree/master/dist).

```js
import React from 'react'
import ReactDOM from 'react-dom'
import AnyChart from '../../dist/anychart-react.min.js'
import anychart from 'anychart'

let data = anychart.data.set([
  {'id': 'AU.WA', 'value': 300},
  {'id': 'AU.JB', 'value': 230},
  {'id': 'AU.NS', 'value': 240},
  {'id': 'AU.VI', 'value': 275},
  {'id': 'AU.NT', 'value': 130},
  {'id': 'AU.TS', 'value': 190},
  {'id': 'AU.CT', 'value': 100},
  {'id': 'AU.SA', 'value': 305},
  {'id': 'AU.QL', 'value': 190}
]);

// please do not forget to include the map to your html file (<head> section)
// <script src="path/to/node_modules/anychart/dist/geodata/countries/australia/australia.js"></script>

ReactDOM.render(
  <AnyChart
    width={800}
    height={600}
    type="choropleth"
    data={data}
    title="Map example"
    geoData="anychart.maps.australia"
  />, document.getElementById('root'));
```

**Comment by Shestac92** [comment]
@jimmy-e 
This is possible using GeoJSON of the map and chart instance approach.

1. Download and place somewhere in the project the required GeoJSON map file. For example, the same [Australia map from our CDN](https://cdn.anychart.com/releases/8.7.1/geodata/countries/australia/australia.json).

2. Import this json to the script
```
import australia from '../../maps/australia.json'
```
Now the map geometry is stored in the `australia` variable.

3. Apply the `australia` variable to the chart geo data
```
chart.geoData(australia);
```

4. The chart instance approach gives much more possibilities to adjust the chart. The idea is to store the chart instance in the variable, adjust it using the AnyChart API and then apply it to the `instance` property of the element. 

The full JS code is below, it will help you:
```
import React from 'react'
import ReactDOM from 'react-dom'
import AnyChart from '../../dist/anychart-react.min.js'
import anychart from 'anychart'
import australia from '../../maps/australia.json'


const data = [
  {'id': 'AU.WA', 'value': 300},
  {'id': 'AU.JB', 'value': 230},
  {'id': 'AU.NS', 'value': 240},
  {'id': 'AU.VI', 'value': 275},
  {'id': 'AU.NT', 'value': 130},
  {'id': 'AU.TS', 'value': 190},
  {'id': 'AU.CT', 'value': 100},
  {'id': 'AU.SA', 'value': 305},
  {'id': 'AU.QL', 'value': 190}
];

//
const chart = anychart.map();
chart.geoData(australia);

// set the series
const series = chart.choropleth(data);

ReactDOM.render(
  <AnyChart
    width={800}
    height={600}
    instance={chart}
    title="Map chart demo"
  />, document.getElementById('root'));

```

**Comment by jimmy-e** [comment]
Great this works, thanks!
