### ISSUE TITLE
Price marker

### ISSUE THREAD

**Issue by helloris25** [AnyChart/AnyChart#12]
Is it possible to make such markers in a simple way?

Now i have to do the line separately, and the container with the price to do next to the chart is a simple div and calculate its position
(Сейчас приходиться делать линию отдельно, а контейнер с ценой делать рядом с графиком простым див и вычислять его положение)

![markers](https://cloud.githubusercontent.com/assets/3649203/25274899/242591de-269b-11e7-9569-d80272af0305.jpg)

**Comment by sarat1111** [comment]
Hi, Can you send me the code in jsfiddle?

Thanks

**Comment by loki20beta** [comment]
@helloris25 there is no better way at the moment, this feature is in our to do list, internal ticket id: DVF-3036

**Comment by maresha** [comment]
@helloris25 glad to inform you that we are going to implement the Current Price Indicator feature in the 8.0.0 version (ETA: Sep 2017). Please be assured we'll keep you updated on the progress.

**Comment by loki20beta** [comment]
@helloris25 Price Indicator has been added in version 8, see [AnyChart Stock: Price Indicator](https://docs.anychart.com/Stock_Charts/Price_Indicator)
