### ISSUE TITLE
Having issues when trying to delete Anychart node_modules package

### ISSUE THREAD

**Issue by derekburton** [AnyChart/AnyChart#120]
When installing and using Anychart in our applications, I seem to be getting a duplicate of a certain geodata country instance for hong kong (screenshot attached). 

The main issue I am having is that, if I try to delete the project/node_modules folder, it can delete one of the instances, but I'm guessing one is pointing to the other, and it is saying that, when trying to delete the other folder, that it is no longer found at the location (also attached below). 

Any idea on what is happening here? Using version 8.7.1.

![hongkong1](https://user-images.githubusercontent.com/6432161/74849313-8dac2600-5306-11ea-86f1-2586e91161fb.PNG)

![hong_kong2](https://user-images.githubusercontent.com/6432161/74849819-2cd11d80-5307-11ea-8848-56eba28316df.PNG)

**Comment by Shestac92** [comment]
@derekburton 
This is a Windows-specific issue, never reproduced on unix systems.
Try to remove them separately or use any other file manager.

**Comment by derekburton** [comment]
@Shestac92 If this is an windows specific-issue, why isn't it being fixed? I don't have access to a Unix box, I can't use a different file manager because the same issue is happening in a DevOps pipeline, and removing separately is what is causing the issue. No other country data has two instances of the same folder, so why is this having it, is it because of the abbreviation at the end?

**Comment by muskiehunter1985** [comment]
I am experiencing the exact same issue while trying to automate node builds.  Our company dictates the build server environment and windows is our only choice.  Seems windows is struggling with the folder ending in ".", seems like a bug that should be fixed.

**Comment by Shestac92** [comment]
@derekburton @muskiehunter1985 
The latest version of AnyChart maps collection doesn't include files and folders with problem names like `s.a.r.`. It was already fixed.
Yes, Windows fails at such file names.
The latest version of the map collection is not released as NPM module yet, but you can download it as a separate collection from [the download page](https://www.anychart.com/download/products/). The collection you will find in the `geodata` directory.
Also, it includes many geometry improvements and geo-meta fixes.

**Comment by muskiehunter1985** [comment]
@Shestac92 thanks for the reference.  Will give it a try.  Are there any plans to publish this as an npm module anytime in the near future?

**Comment by Shestac92** [comment]
@muskiehunter1985 
Yes, for sure! We are planning to release the maps collection as a separate NPM module along with future updates.

**Comment by Kissema** [comment]
Thank you, but how we can remove that folder now?
