### ISSUE TITLE
Anychart Mode bar can not be removed

### ISSUE THREAD

**Issue by MarcoK0610** [AnyChart/AnyChart#123]
I am using a JSON to show a chart with Anychart. I tried to remove the Modebar with the following addition {"displayModebar":false} in the config, layout and data but this will not effect the Modebar. See example txt file.
[ExampleAnychart.txt](https://github.com/AnyChart/AnyChart/files/4387659/ExampleAnychart.txt)
 What can be the issue?

**Comment by Shestac92** [comment]
@MarcoK0610 
Please, can you specify the library name you are using? The file you provided doesn't include AnyChart API.

**Comment by MarcoK0610** [comment]
Sorry it was not a bug in ANychart but in the Anychart widget in our platform Mendix. The creator of the widget is fixing it right now. Thx
