### ISSUE TITLE
How to update choropleth map with new dataset?

### ISSUE THREAD

**Issue by Lukas-Cu** [AnyChart/AnyChart#124]
Hi,

I have a choropleth map generated with some dataSet (array of JSONs loaded from file) and need to redraw it (update) with new dataSet if new file is loaded. 

Can you please help me with doing so?

**Comment by Shestac92** [comment]
@Lukas-Cu 
To achieve that you should apply the new data to the existing series. There's no need to recreate the chart or series. For details, check [the sample](https://playground.anychart.com/BET0QY6U/1).
