### ISSUE TITLE
How to change shape of Scroller Thumbs 

### ISSUE THREAD

**Issue by parsa-xy** [AnyChart/AnyChart#126]
Hello,
How could we change the shape of scoller thumb? I couldn't find any article regarding the shape and most of them were about the color filling and size changing.
![WhatsApp Image 2020-04-03 at 07 42 06](https://user-images.githubusercontent.com/57038782/78375509-bb30f400-7581-11ea-8630-fa36c1b6b923.jpeg)

**Comment by Shestac92** [comment]
@Pa22 
Unfortunately, the current version of the library doesn't support shape settings for the scroller thumbs. All available settings you can find in [the article](https://docs.anychart.com/Common_Settings/Scroller#thumbs).
