### ISSUE TITLE
Div container charts

### ISSUE THREAD

**Issue by Mr-Jobs** [AnyChart/AnyChart#127]
Hello.
I can’t understand how to implement it.
Briefly about what I’m doing, I’m doing Chart. Charts loads everything well, but there is a select on the page, when you select it, the ticker changes and, accordingly, the chart
But anychart when changing the ticker creates a div with the chart, and does not give the result to the old chart. Tell me how you can make loading the chart in the old div and not create a new one.
https://www.anychart.com/products/anystock/gallery/Stock_General_Features/Multiple_Chart_instances_with_one_Data_Set.php
using this chart

**Comment by Shestac92** [comment]
To replace the chart's data there's no need to recreate the chart. You can simply append new data or completely replace it. For details, check [the sample](https://playground.anychart.com/ywWNdpbp).

**Comment by Mr-Jobs** [comment]
This example still creates a new div with a chart. How do I ban this?
![chart](https://user-images.githubusercontent.com/64742650/80961574-e4100780-8e13-11ea-8768-d0d203fbf7b1.png)

**Comment by Shestac92** [comment]
@Mr-Jobs 
The sample I provided in my previous comment creates only a single container for the chart.
Can you provide the full chart JS code? If you don't want to provide publicly you can contact me at support@anychart.com

**Comment by theJCrakcer** [comment]
try again using :
document.getElementById("your_chart_container").remove(); 

and call again method for reload
