### ISSUE TITLE
Tooltip issue on radar chart

### ISSUE THREAD

**Issue by darklight721** [AnyChart/AnyChart#13]
I noticed on v7.13.1 that the tooltips on a radar chart are not showing correctly.
See here: https://jsfiddle.net/tn1dsqgw/
Compare that with v7.13.0: https://jsfiddle.net/eLxnvqco/1/

**Comment by loki20beta** [comment]
@darklight721 yes, it seems there is a bug, we will double check and get back with an ETA

**Comment by maresha** [comment]
This issue was fixed with the latest 7.14.0 version: https://jsfiddle.net/2t08ahkg/4/
Please check it and let us know if it doesn't work for you.

**Comment by darklight721** [comment]
@maresha works for me, thanks!
