### ISSUE TITLE
Resizing the chart container?

### ISSUE THREAD

**Issue by 26medias** [AnyChart/AnyChart#130]
Hi,

I have the #container with absolute positioning (width:100%;height:100%) however when the parent (relative) resizes, the chart doesn't resize.

I can't find any reference in the doc to resizing or even setting the width/height via code.

**Here's the container after I resize the window:**
![](https://i.imgur.com/fWuwcYg.png)

**The SVG element is properly scaled:**
![](https://i.imgur.com/CrfvJM8.png)

**The chart itself isn't scaling:**
![](https://i.imgur.com/1VTT2bL.png)

I tried to call the chart.draw() method when the container resizes, but it's not working.

How can I fix this?

Thanks.

**Comment by Shestac92** [comment]
@26medias 
The AnyChart library doesn't affect the HTML layout and can't control it. The chart always fits the container if bounds are not applied manually in JS code - `bounds()` function. Anyway, it can't expand or collapse the HTML container. It affects only svg inside it.
All issues with resizing the chart container may come from CSS settings.

You should inherit styles to make width and height percents work as expected. For details, check [the sample](https://playground.anychart.com/jY8A5aYT/1), try to resize the chart, and pay attention to CSS.

**Comment by 26medias** [comment]
So there's no method I can call to force the chart to resize to its container? (the div targeted in `chart.container('container');`)

**Comment by Shestac92** [comment]
@26medias 
There's no need for this method. If you didn't apply bounds() settings manually, then the chart always fits the parent container on the fly.
If you can provide a sample, that reproduces the issue on Playground, then we can review it to find what's wrong with the container.
