### ISSUE TITLE
horizontal line

### ISSUE THREAD

**Issue by Alez999** [AnyChart/AnyChart#131]
does horizontal line have an end point?
https://docs.anychart.com/Stock_Charts/Drawing_Tools_and_Annotations/Horizontal_Line
I can not see that, it is only available to draw it without the end.

**Comment by Shestac92** [comment]
@Alez999 
The horizontal line is an endless line without start/end X-coordinate. It has only Y-value.

If you need a line with start/end points, you can use [Line segment annotation](https://docs.anychart.com/Stock_Charts/Drawing_Tools_and_Annotations/Line_Segment).
