### ISSUE TITLE
Range selection

### ISSUE THREAD

**Issue by Alez999** [AnyChart/AnyChart#132]
can we change color of range selection box or change size or something in it?
https://docs.anychart.com/Stock_Charts/Range_Selection#zoom_to_label

**Comment by loki20beta** [comment]
You can override range selector css: https://playground.anychart.com/VT1K9gQG

**Comment by Alez999** [comment]
@loki20beta I can not see any difference in color in your example, thank you.
![Capture12121212](https://user-images.githubusercontent.com/65306527/82673687-de575600-9c4a-11ea-9736-8af16b92904c.JPG)

**Comment by loki20beta** [comment]
buttons are controlled by another class: https://playground.anychart.com/VT1K9gQG/1
