### ISSUE TITLE
price line action

### ISSUE THREAD

**Issue by Alez999** [AnyChart/AnyChart#133]
can we put a delay in price line when it is getting new data?
for example now, it is too sharp, but if we can give it a delay so when the new price will come, price line will go there with delay.

**Comment by loki20beta** [comment]
You can put any delay while adding data, for example here https://www.anychart.com/solutions/big-data-speed-test/ (the source of the sample can be found at https://github.com/anychart-solutions/big-data-speed-test) you can set the delay for the data generated, basically, when you get the data you can decide when you actually append it to the data set.

The super-basic sample may look like this https://playground.anychart.com/NspdrEQ8/1 (it fails when it runs out of data, you need to decide how you generate data and make proper adjustments)
