### ISSUE TITLE
delete numbers below the chart

### ISSUE THREAD

**Issue by Alez999** [AnyChart/AnyChart#135]
Hello, how I can delete these numbers which indicate times, i dont need them because the time is readable in candle itself.

![Capture](https://user-images.githubusercontent.com/65306527/83168701-90df5b00-a11a-11ea-8913-cf144e241a9f.JPG)

**Comment by loki20beta** [comment]
You need to disable minor and major labels: https://playground.anychart.com/cJsRVoP6
