### ISSUE TITLE
using anychartview.clear() showing blank screen. Unable to replace a chart with another chart dynamically

### ISSUE THREAD

**Issue by trisandhyanagam** [AnyChart/AnyChart#136]
I created a  pie chart dynamically and tried to replace it with line graph in the same view on user selection of graph type.

Used anychartview.clear() before setting the graph but its showing blank screen.
Also, anychartview.dispose() is not working. Please help me here.

**Comment by karalehemant07** [comment]
I am also facing the same issue. Is there anything that can solve this issue?

**Comment by AkexStar** [comment]
I have the same problem....
Is here anybody can help us?
Maybe there is a better way to show Chart in Android? Please tell me!
I'm looking for any recommendation about chart in Android. Please help us!
