### ISSUE TITLE
TypeScript Definition File

### ISSUE THREAD

**Issue by mbugbee** [AnyChart/AnyChart#14]
We're trying out AnyChart in our TypeScript project but we're having trouble getting code hinting working.  Is there any special setup required to use the packaged TypeScript Definition file?

We currently import the module as"
``` import * as anychart from 'anychart'; ```

but when we go to use "anychart" in the code, no code hinting occurs.

Thanks for any help!
Matt

**Comment by maresha** [comment]
Matt,

first, we should know your version of TypeScript.
Also, please try to use our include the dist/index.d.ts file with
`/// <reference path="path/to/index.d.ts" />`
You should add it at the beginning of your .ts file.

**Comment by mbugbee** [comment]
Using TypeScript 2.2.1

We'll give the reference code a try, however, we're also using MomentJS which also packages its own definition file but doesn't require any addition reference code to be added.  Might be worth exploring how they pull that off to help remove that requirement.

Thanks
Matt

**Comment by mbugbee** [comment]
Just tried adding the reference code to the top of the ts file, pointing to the correct location for index.d.ts, and we're still not seeing any code hinting.

**Comment by maresha** [comment]
Matt,

we prepared the example of integration with the TypeScript, please find here all docs:
https://github.com/anychart-integrations/webpack-typescript-example

Please do not forget to:
- add `import 'anychart';` to your code
- add `/// <reference types="anychart" />` into the head of your .ts file 
- install the latest version with `npm install anychart`

Hope this helps! Please try it and let us know if it doesn't work for you.

**Comment by RomanLubushkin** [comment]
Closed due to zero activity
