### ISSUE TITLE
anyStock datetime label format yields "Invalid Date"

### ISSUE THREAD

**Issue by danrockstheplanet** [AnyChart/AnyChart#141]
Whenever I try to format the datetime-based x-axis labels in anyStock, I get "Invalid Date" for one or more labels.

Example: https://playground.anychart.com/EbFxRjhO

![image](https://user-images.githubusercontent.com/1088493/85326316-b3069780-b492-11ea-9f3e-98c2b645edfc.png)

**Comment by Shestac92** [comment]
@danrockstheplanet 
It's just a matter of using arrow functions in JS. All callback function in AnyChart provides the context in `this` that refers to the object it belongs to. Using arrow function it loses its context. In short, with arrow functions, there is no binding of this. 
So, in this case, you should rework the callback like this (lines 22-23) - https://playground.anychart.com/u8JwyDaX/1

You can learn more about arrow function specifics about `this` context [in the article](https://www.w3schools.com/js/js_arrow_function.asp).

**Comment by danrockstheplanet** [comment]
Got it. My mistake, then. Closing.
