### ISSUE TITLE
scrubbing anyStock's range scroller causes ranges to expand

### ISSUE THREAD

**Issue by danrockstheplanet** [AnyChart/AnyChart#142]
In the video below, I start by resizing a range. Then when I go to scrub that range back and forth, the range automatically grows. This was done on this playground chart (without any changes): https://playground.anychart.com/docs/v8/samples/STOCK_Axes_02

Windows 10 Pro
Chrome Version 83.0.4103.106 (Official Build) (64-bit)

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/1088493/85333713-ab012480-b49f-11ea-8ce1-8067df4500ae.gif)

**Comment by Shestac92** [comment]
@danrockstheplanet 
Thank you for your report!
This is a known issue and we are planning to fix that in future updates. We will notify you when the ETA and the fix become available.

**Comment by Shestac92** [comment]
@danrockstheplanet 
We will do our best to include the fix in the autumn update. We will notify you when the fix becomes available.
