### ISSUE TITLE
TreeMap not expand height to 100%

### ISSUE THREAD

**Issue by almirus** [AnyChart/AnyChart#144]
![image](https://user-images.githubusercontent.com/16898685/85949484-c8326900-b95f-11ea-8bfe-8af2d7fa404b.png)

https://playground.anychart.com/zhSnyNf9

**Comment by Shestac92** [comment]
@almirus 
The chart can't affect the div container size. You should apply a correct CSS selector for that container. Like this:
```
html, body, #container {
  	width:100%;
    height: 100%;
    margin: 0;
    padding: 0;
}
```
Then it will work - https://playground.anychart.com/FJuMDjFQ/0
