### ISSUE TITLE
Formatted dates cause month labels to shift (anystock)

### ISSUE THREAD

**Issue by danrockstheplanet** [AnyChart/AnyChart#146]
I've created an anyStock chart where the date labels on top plot have no formatting, but the labels on bottom plot are formatted. The bottom labels are off by one month.

https://playground.anychart.com/DZ3P5DCJ

**Comment by Shestac92** [comment]
@danrockstheplanet 
Please, can you highlight the issue at the screenshot?
We launched the sample and see no any issues. All ticks and labels match.
<img width="906" alt="Screenshot 2020-07-01 at 10 54 17" src="https://user-images.githubusercontent.com/24609062/86198076-65bcb100-bb89-11ea-89a4-e6f002bec29a.png">

**Comment by danrockstheplanet** [comment]
@Shestac92 
Hrm. We're seeing two different things. That would make me think it's a browser issue, but I've tried it on the following browsers on my MS Windows 10 Pro, all with similar results:
  - Chrome Version 83.0.4103.116 (Official Build) (64-bit)  (pictured below)
  - Firefox 78.0.2 (64-bit) 
  - MS Edge  Version 83.0.478.64 (Official build) (64-bit)
  - Opera 68.0.3618.173
  

![image](https://user-images.githubusercontent.com/1088493/87555189-be587780-c67a-11ea-9210-b342eaec2674.png)

**Comment by Shestac92** [comment]
@danrockstheplanet 
Thank you for the details, we will test that in different OS and browsers

**Comment by sturdystablestalwart** [comment]
I could not reproduce the behavior; I tested both 8.7.1 and the latest 8.11.1. Both work as intended; a possible explanation is a specific screen ratio. If there is any other request or concern, I'm here to help.
