### ISSUE TITLE
3D surface plot chart does not support string values for x axis?

### ISSUE THREAD

**Issue by manikandanm1757** [AnyChart/AnyChart#147]
I tried to assign string values for x axis but it does not work, please check and update the solution to resolve this.

Please find the the sample data below.

var data = [
        ["A", 3, 1],
        ["A", 6, 1],
        ["A", 9, 1],
        ["B", 3, 1],
        ["B", 6, 1],
        ["B", 9, 1],
        ["C", 3, 1],
        ["C", 6, 1],
        ["C", 9, 1]
    ];

**Comment by Shestac92** [comment]
@manikandanm1757 
Unfortunately, the current version of the library doesn't support the ordinal scale for the Surface chart.
We will take into account this requirement for future updates.

**Comment by Shestac92** [comment]
@manikandanm1757 
There's an approach that allows implementing the required chart. It requires preprocessing the data and the trick to replace the number labels of the xScale with category names. For details, [check the sample](https://playground.anychart.com/gallery/src/Surface_Chart/GDP_Per_Capita).
