### ISSUE TITLE
Need a native angular Module

### ISSUE THREAD

**Issue by techBeck03** [AnyChart/AnyChart#148]
Angular 10 complains when using the regular js files with the following message:

```
/platform-page.component.ts depends on 'anychart'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```

I'm also seeing very odd behavior when i switch between routes in my angular app where anychart charts are being used.  The charts work great(ish) until i change routes to another page with a chart in it.  At that point the second chart never renders correctly for some reason.

Thanks

**Comment by Shestac92** [comment]
@techBeck03 
At the moment you can ignore this warning. The anychart module is already optimized and Angular optimization can't affect it further.

To solve the rendering issue, try to add the following line in your code before creating every chart:
```
anychart.graphics.useAbsoluteReferences(false);
// then create chart, etc
```
