### ISSUE TITLE
How to apply colors to Tree Map Chart in iOS -Swift ?

### ISSUE THREAD

**Issue by Pallavid28** [AnyChart/AnyChart#149]

**Comment by Pallavid28** [comment]
Am unable to apply colors to Tree Map Chart in iOS using swift language.

**sample code:**
let chart = AnyChart.treeMap()
chart.data(data: treeMapData, fillMethod: anychart.enums.TreeFillingMethod.AS_TABLE)
let colorsDef:[String] = ["#008FFB","#00E396","#FEB019","#FF4560","#775DD0"]
chart.colorScale().colors(colors: colorsDef)
![Simulator Screen Shot - iPhone 11 Pro - 2020-07-28 at 10 54 45](https://user-images.githubusercontent.com/52535106/88631647-19a15580-d0d0-11ea-90d3-5c18c0479f7a.png)

**Comment by Shestac92** [comment]
@Pallavid28 
We have successfully reproduced the issue. Unfortunately, the current version of the library doesn't support custom colors for the Treemap chart.
We will take it into account for future updates.

**Comment by AfaqaL** [comment]
Hello @Pallavid28 

How did you create the data for treemap? code snippets were not provided and I couldn't figure out the way through android snippets. Any help?

**Comment by chaudharyvikram** [comment]
> Hello @Pallavid28
> 
> How did you create the data for treemap? code snippets were not provided and I couldn't figure out the way through android snippets. Any help?
> 
> Also, Didn't you have the problem with AnyChartView-s having white paddings at the top and scrolls inside the views itself? Couldn't manage to efficiently get rid of any of those problems

Here is sample

```
let treeMap = AnyChart.treeMap()
let entry: Array<DataEntry> = [
            CustomTreeDataEntry(id: "Country", parent: nil, product: "Country"),
            CustomTreeDataEntry(id: "India", parent: "Country", product: "India", value: 20),
            CustomTreeDataEntry(id: "US", parent: "Country", product: "US", value: 200),
            CustomTreeDataEntry(id: "UK", parent: "Country", product: "UK", value: 50)
 ]
        
treeMap.data(data: entry, fillMethod: .AS_TABLE)



class CustomTreeDataEntry: TreeMap {
    public init(id: String, parent: String, product: String, value: Int) {
        super.init(id: id, parent: parent, value: value)
        setValue(key: "product", value: product)
    }
    
    public init(id: String, parent: String?, product: String) {
        super.init(id: id, parent: parent)
        setValue(key: "product", value: product)
    }
}

open class TreeMap: DataEntry {
    
    public init(id: String, parent: String?) {
        super.init()
        setValue(key: "id", value: id)
        setValue(key: "parent", value: parent)
    }
    
    public init(id: Int, parent: String) {
        super.init()
        setValue(key: "id", value: id)
        setValue(key: "parent", value: parent)
    }
    
    public init(id: String, parent: Int) {
        super.init()
        setValue(key: "id", value: id)
        setValue(key: "parent", value: parent)
    }
    
    public init(id: Int, parent: Int) {
        super.init()
        setValue(key: "id", value: id)
        setValue(key: "parent", value: parent)
    }
    
    public init(id: String, parent: String, value: Int) {
        super.init()
        setValue(key: "id", value: id)
        setValue(key: "parent", value: parent)
        setValue(key: "value", value: value)
    }
    
}
```

![Simulator Screenshot - iPhone 15 Pro - 2024-02-13 at 14 57 24](https://github.com/AnyChart/AnyChart/assets/39688232/ab29f8ec-e62b-4887-b9d5-4e5efcfbd938)
