### ISSUE TITLE
Error when requiring the library

### ISSUE THREAD

**Issue by abderrahmaneayad** [AnyChart/AnyChart#15]
Thank you guys for this awesome library,

When I use the link from the cdn it works perfectly, but when requiring it it shows an error:
I try this code in : https://npm.runkit.com/anychart

```
var anychart = require("anychart")

anychart.onDocumentReady(function() {
  var chart = anychart.pie([10, 20, 7, 18, 30]);
  console.log('done');
});
```
It shows this error: _TypeError: anychart.onDocumentReady is not a function_

I have no idea what is the problem.

**Comment by mbugbee** [comment]
Seeing a similar issue... using 7.14.0.

We see a "TypeError: anychart is not a function"
TypeScript also complains that "node_modules/anychart/dist/index.d.ts' is not a module."

**Comment by loki20beta** [comment]
We will double check and get back to you.

**Comment by loki20beta** [comment]
Internal id: TS-157

**Comment by loki20beta** [comment]
Please try this https://github.com/anychart-integrations/webpack-typescript-example and let us know if it works for you or not.

**Comment by maresha** [comment]
@mbugbee the ticket has been closed due to inactivity. If the issue is not solved, please contact us via support@anychart.com or reply.

**Comment by mbugbee** [comment]
Using ```import 'anychart';``` did the trick.  

When using VSCode I found ```/// <reference types="anychart" />``` wasn't necessary.
