### ISSUE TITLE
How to disable scroll from AnyChartView in iOS Swift?

### ISSUE THREAD

**Issue by Pallavid28** [AnyChart/AnyChart#150]
I want to disable scroll from chart view(Rendering treemap chart in iOS by using swift language), chart should appear in the given width and height.
![Simulator Screen Shot - iPhone 11 Pro - 2020-07-28 at 12 40 23](https://user-images.githubusercontent.com/52535106/88631347-a8fa3900-d0cf-11ea-97e6-1518dd37bfef.png)

**Comment by sturdystablestalwart** [comment]
@Pallavid28 

Unfortunately, the current version of the library does not offer the option to disable scrolling for the AnyChartView. Rest assured, we will take this into consideration for future updates.

If you have any additional information or questions, feel free to reach out—I'm here to assist you.
