### ISSUE TITLE
Additional Scale not working in android studio

### ISSUE THREAD

**Issue by Legal-developer** [AnyChart/AnyChart#151]
i need to draw a chart in android with 2 y axis both with different scale. i have been trying to do it for a week now but i am not able to do it in android. i am using the code given in the documentation.
Linear extraYScale = anychart.scale.linear();
please help

**Comment by Shestac92** [comment]
@Legal-developer 
To achieve that you should create a scale instance, adjust it and apply it to the chart axis. For details, check a snippet below:
```
        Linear extraScale = Linear.instantiate();
        extraScale.minimum(-1000);
        extraScale.maximum(1000);
        chart.yAxis(1).scale(extraScale);
```

**Comment by Legal-developer** [comment]
Thanks for your help, i have been stuck at it for last 20 days
