### ISSUE TITLE
Container is not set or can not be properly recognized. Use container() method to set it

### ISSUE THREAD

**Issue by Gokulakannanaj** [AnyChart/AnyChart#152]
Hi,
Getting Following Error:
Error: 1 (anychart-core.min.js:209 ) 

Container is not set or can not be properly recognized. Use container() method to set it

**Code Info**
<html>
 <head>
	<script src="https://cdn.anychart.com/releases/8.7.1/js/anychart-core.min.js"></script>
	//<script src="https://cdn.anychart.com/releases/8.7.1/js/anychart-bundle.min.js"></script>
	//<script src="https://cdn.anychart.com/releases/8.7.1/js/anychart-base.min.js"></script>
	<script src="https://cdn.anychart.com/releases/8.7.1/js/anychart-graph.min.js"></script>
	<script type="text/javascript">
		// create data
		var data = {
		  nodes: [
		    {id: "Richard"},
		    {id: "Larry"},
		    {id: "Marta"},
		    {id: "Jane"},
		    {id: "Norma"},
		    {id: "Frank"},
		    {id: "Brett"}
		  ],
		  edges: [
		    {from: "Richard", to: "Larry"},
		    {from: "Richard", to: "Marta"},
		    {from: "Larry",   to: "Marta"},
		    {from: "Marta",   to: "Jane"},
		    {from: "Jane",    to: "Norma"},
		    {from: "Jane",    to: "Frank"},
		    {from: "Jane",    to: "Brett"},
		    {from: "Brett",   to: "Frank"}
		  ]
		};

		// create a chart and set the data
		var chart = anychart.graph(data);

		// set the container id
		chart.container("container");

		// initiate drawing the chart
		chart.draw();
	</script>
 </head>
 <body>
  <div id="container"></div>
 </body>
</html>

**Comment by Shestac92** [comment]
@Gokulakannanaj 
This error means that DIV element with id "container" doesn't exist so the chart can't found it.
The [Quick Start Guide](https://docs.anychart.com/Quick_Start/Quick_Start) describes how to create a container for the chart.

**Comment by Gokulakannanaj** [comment]
@Shestac92 - Thanks for your update. I missed some lines in JavaScript while copy paste. It's my mistake and working fine.
