### ISSUE TITLE
Is there a way to insert points between 2 already existing ones without expanding the chart?

### ISSUE THREAD

**Issue by persiklover** [AnyChart/AnyChart#153]
All my points are mapped like this:
`{ x: "1", value: 1000000 }, { x: "2", value: 1050000 }`
Adding a value in between with something like `{ x: "1.5", value: 1025000 }` doesn't work, the point doesn't land in the middle as I want it to, it simply moves the rest of the chart to the right
![Screenshot_7](https://user-images.githubusercontent.com/38048337/94600043-0199ae00-029a-11eb-8ea6-a35bcfd42c57.png)

**Comment by Shestac92** [comment]
@persiklover 
As I can see, you are using Ordinal xScale with continuous mode.
The ordinal scale works with categories, it means that "1.5" has its own category.
You should use a linear scale for this purpose like this:
```
// create linear scale
var xScale = anychart.scales.linear();
// apply it to the chart xScale
chart.xScale(xScale);
// also you can apply min/max manually
xScale.minimum(0).maximum(5);
```
In this case, there's no need to apply continuous mode.

**Comment by persiklover** [comment]
@Shestac92 
I did as you said but it still doesn't work.
I uploaded mycode to [AnyChart playground](https://playground.anychart.com/sOfRGpSF/1), can you please take a look at it?

**Comment by Shestac92** [comment]
@persiklover 
The ordinal chart expects that every series has the same set of points (the same x coordinates). If they don't match continuous series can get broken.
In this case, you can use Scatter chart type. It will solve the issue with broken series and it provides linear xScale as a default. 
For details, check [the modified sample based on the scatter chart](https://playground.anychart.com/XC3AeGEp/1).
