### ISSUE TITLE
Stock chart zoom without change timeframe

### ISSUE THREAD

**Issue by RubberArchind** [AnyChart/AnyChart#155]
Is it possible to make zoom control like https://docs.anychart.com/Common_Settings/UI_Controls/Zoom_Controls in the stock chart?

**Comment by Shestac92** [comment]
@RubberArchind 
The `zoomControl` of the Map chart is not compatible with the Stock chart. But using the library API and any third-party controls you can implement a similar functionality. For details, check [the sample](https://playground.anychart.com/6iKNpT17).

**Comment by RubberArchind** [comment]
@Shestac92 Thanks for your answer, but how to solve the zoom without changing the timeframe, for example if using the current system if the timeframe is 1 year if I zoom it will zoom but with the timeframe reduced, how to zoom without changing the timeframe?

**Comment by RubberArchind** [comment]
this is the reason why i'm asking this
![image](https://user-images.githubusercontent.com/35050952/95164672-9a698580-07d4-11eb-832a-d4446750c36d.png)
in MAX timeframe one candle represent one month but when i zoom it the time represented by one candle changes

**Comment by Shestac92** [comment]
@RubberArchind 
The data grouping switches the interval automatically while zooming. You can disable it or switch manually using the library API. This functionality is well described in [the documentation article](https://docs.anychart.com/Stock_Charts/Data_Grouping).

**Comment by RubberArchind** [comment]
Damn i missed that one, thanks you saved my day again
