### ISSUE TITLE
How to Position TextMarker on Chart directly?

### ISSUE THREAD

**Issue by f0ff886f** [AnyChart/AnyChart#156]
I am trying out sparklines, and so far they're quite cool.

I would like to do something simple like put a text marker at the upper right and lower left corners of the chart to display the maximum and minimum values. Ideally I'd like the yAxis max and yAxis min but I don't think these are available in sparklines.

Is this possible? Everything I can achieve aligns the TextMarker to a value, rather than something specific to the canvas area.

**Comment by RubberArchind** [comment]
I think we can make an overlay for that, here's an example I made [https://jsfiddle.net/rtho6nza/](https://jsfiddle.net/rtho6nza/)
**P.S: sorry for bad implementation**

**Comment by f0ff886f** [comment]
Oh wow, clever solution! I forgot that the wide world of HTML and CSS is still at our hands 👍 Thank you for the idea, if there is no "native" way I will try this.

I am also going to try and replicate sparklines with regular graphs, I believe that I can put markers on axis() at that point.

**Comment by RubberArchind** [comment]
and take a look at [https://docs.anychart.com/Chart_Editor/Overview](https://docs.anychart.com/Chart_Editor/Overview)

**Comment by Shestac92** [comment]
@f0ff886f @RubberArchind 
Sparklines do not support yAxis and textMarkers can be bound only to a specific value according to the yScale.
If you need to show min/max values of the scale, then you should not use sparklines. In this case, a [simple Line chart](https://docs.anychart.com/Basic_Charts/Line_Chart) would be the best choice.
These chart types implement different features for different purposes.

**Comment by f0ff886f** [comment]
Hi, I just want to finish this issue by stating the advice to use regular line charts. I did that, removed many of the elements and managed to create almost-spark-line-esque charts with some extra features.

Thanks!
