### ISSUE TITLE
AnyStock: Trend Channel пропадает при изменении позиции скроллера

### ISSUE THREAD

**Issue by CrazyJerboa** [AnyChart/AnyChart#157]
Приветствую. Обнаружил такую особенность поведения anychart при скролле графика:

![Запись экрана 2020-10-17 в 00 46 54](https://user-images.githubusercontent.com/30646210/96311845-0ccb3880-1013-11eb-87b6-c121ad37d273.gif)

Проявляется всегда при увеличении масштаба скроллера, зависимости от величины масштаба не обнаружил.

Является ли это багом? Если нет, то как исправить такое поведение аннотации, чтобы канал отображался всегда вне зависимости от положения скроллера?

Заранее спасибо за ответ.

**Comment by Shestac92** [comment]
@CrazyJerboa 
Спасибо за ваш репорт! Да, это похоже на баг. Мы все проверим с командой разработки и сообщим позже о возможном решении проблемы или ориентировочных сроках, когда фикс станет доступен.

**Comment by Shestac92** [comment]
@CrazyJerboa 
Фикс для этой проблемы выйдет вместе с грядущим обновлением 8.9.1
