### ISSUE TITLE
Anychart not load first time when use gradient color in angular 9.

### ISSUE THREAD

**Issue by bhaveshpatel200** [AnyChart/AnyChart#158]
Hi,
I have use anycharts '8.8.0' version.

I have use below gradient color in column chart.
columnSeries.fill(['#3BCBEF', '#8FAFB9', '#B8A09E', '#E69082', '#FC8973'], -90).stroke('0 #000');

When i use above gradient color, not load column chart first time.
after refresh full page then it will work, i don't know what is problem.

i have remove gradient color and its working with all scenarios. so problems comes when use gradient color.

below is the full code of column chart.
--------------------------------------------------
        let chart = anychart.column(); chart.animation(true);
        chart.interactivity().selectionMode("none");

        let ds = anychart.data.set(data);
        let dataSeries = ds.mapAs({ x: [0], value: [1] });

        let columnSeries = chart.column(dataSeries);
        columnSeries.fill(['#3BCBEF', '#8FAFB9', '#B8A09E', '#E69082', '#FC8973'], -90).stroke('0 #000');

        if (document.body.clientWidth < 576) { columnSeries.pointWidth(5); }
        else { columnSeries.pointWidth(10); }

        let tooltip = chart.tooltip(); tooltip.useHtml(true)
        columnSeries.tooltip().format(d => { return "<div class='font14'>Counts : " + d.value + "</div>" });

        chart.xAxis().labels().fontSize(10).rotation(-90);
        chart.yAxis().labels().fontSize(10);

        chart.yGrid().enabled(true); chart.xGrid().enabled(true);
        if (data.length > 0) { chart.yScale().ticks().count(5).interval(10); } else { chart.yScale().ticks().count(5); }

        document.getElementById("hourly_chart").innerHTML = "";
        chart.container('hourly_chart');
        chart.draw();

**Comment by Shestac92** [comment]
@bhaveshpatel200 
To solve the issue add the following line before the chart creation code:
```
anychart.graphics.useAbsoluteReferences(false);
```

**Comment by bhaveshpatel200** [comment]
Thank You @Shestac92.
I have just one question just for information.
is this above change will affect in other anycharts of other pages ?

**Comment by Shestac92** [comment]
@bhaveshpatel200 
It will affect the AnyChart globally.

**Comment by bhaveshpatel200** [comment]
Ok, Thanks.
i have update 'useAbsoluteReferences' to 'true' after generated chart. and its working properly. like below,

    anychart.graphics.useAbsoluteReferences(false);
    chart.draw();
    anychart.graphics.useAbsoluteReferences(true);
    anychart.graphics.updateReferences();
