### ISSUE TITLE
how to use modules when using webpack?

### ISSUE THREAD

**Issue by bonesoul** [AnyChart/AnyChart#159]
i'm using webpack to load anychart,

https://docs.anychart.com/Quick_Start/Modules doesn't say much.

how can i for example import/require exports module within my webpacked stuff?

**Comment by Shestac92** [comment]
@bonesoul 
There are no any special approaches. Simply add the AnyChart to the package json. Then import the AnyChart to the main or dependent JS file. Then webpack will do all the stuff. For details, check [the demo application that describes that](https://github.com/anychart-integrations/anychart-es6-webpack).

**Comment by bonesoul** [comment]
I did so but I can't get the modules working.

**Comment by Shestac92** [comment]
@bonesoul 
Can you provide more details on the issue?

**Comment by bonesoul** [comment]
i've installed anychart from npm

`"anychart": "8.9.0",`

requiring it in my website assets;

`const anychart = require('anychart');`

trying range picker and stuff;

```
  var rangePicker = anychart.ui.rangePicker();
  rangePicker.render(chart);

  var rangeSelector = anychart.ui.rangeSelector();
  rangeSelector.render(chart);
```

but the range button doesn't render.

same with the exporting module.

**Comment by Shestac92** [comment]
@bonesoul 
For rendering selector and picker you also need AnyChart CSS files.
```
<link rel="stylesheet" type="text/css" href="https://cdn.anychart.com/releases/8.9.0/css/anychart-ui.min.css"/>
```

**Comment by bonesoul** [comment]
oh it may be the case then, thanks
