### ISSUE TITLE
Comma-separated values not possible with 'groupsSeparator' formatting logic

### ISSUE THREAD

**Issue by wkruddy** [AnyChart/AnyChart#16]
I noticed this recently while trying to add commas to the y-scale values for a bar chart.

GroupsSeparator works fine for any other value, except commas, which would seem to be a common use case. I've tried to put it inside quotes, and tried escaping it, encoding it, etc. Nothing seems to work.

I can wrote custom formatting logic, but since you have the ability to separate on other characters, I'm curious why you can't separate on a comma.

This is even evident in your text formatting playground item (shown in this fiddle: https://jsfiddle.net/eh4yu59n/ ).

Is this something that is painfully obvious to others and I'm just missing something, or is this a bug? Thanks.

**Comment by loki20beta** [comment]
Double back slash escape is needed:

`chart = anychart.line();
`chart.yAxis().labels().format("{%Value}{groupsSeparator:\\,}");

Here is  a sample [https://jsfiddle.net/eh4yu59n/1/](https://jsfiddle.net/eh4yu59n/1/)

**Comment by wkruddy** [comment]
@loki20beta Great! Thanks so much for that help. User-error 😆
