### ISSUE TITLE
Understanding how a scale maximum is calculated

### ISSUE THREAD

**Issue by f0ff886f** [AnyChart/AnyChart#160]
Hello, this isn't really a bug but rather a question in general to try and understand what the chart is doing.

I have _one_ chart that calculates super odd minimum and maximum values, for no apparent reason. It is a simple line chart, with one series that has the values:

```
data: (10) […]
0: Array [ "a", null ]
1: Array [ "b", null ]
2: Array [ "c", null ]
3: Array [ "d", null ]
4: Array [ "e", null ]
5: Array [ "f", 0.0026 ]
6: Array [ "g", 0.0026 ]
7: Array [ "h", 0.0026 ]
8: Array [ "i", 0.0026 ]
9: Array [ "j", 0.0026 ]
```

And for some reason, the chart calculates a minimum of -0.750 and a maximum of 0.750, and I can't understand why for the life of me. Other charts that have also 5 null values but then _slightly_ different second values (say 0.0023 instead of 0.0026) have scales that I would completely expect. And they all get generated with the same JS function 😆 

Is there any pointer to the Anychart max/min code so I could understand why these values cause this funny case?

**Comment by f0ff886f** [comment]
As an example, the another dataset with realistic scales is:

```
data: (10) […]
0: Array [ "a", null ]
1: Array [ "b", null ]
2: Array [ "c", null ]
3: Array [ "d", null ]
4: Array [ "e", null ]
5: Array [ "f", 0.0021 ]
6: Array [ "g", 0.0021 ]
7: Array [ "h", 0.0021 ]
8: Array [ "i", 0.0021 ]
9: Array [ "j", 0.0022 ]
```

Which provides min=0.002, max=0.002 (on the labels, I'm guessing its something like 0.0020 and 0.0022 or 0.0023, all of which is fine), so it doesn't seem like precision is an issue.

**Comment by f0ff886f** [comment]
I can "fix" it by making sure the values are not uniform (which was easy since I was pre-rounding the data, now I round the data in the tooltip). In case it helps anyone in the future, just make sure the values aren't uniform.

But its impossible to "fix" when there is 9 null datapoints and just one datapoint of any decimal value like 0.0021 or 0.0026. Then the limits are always 0.750 and -0.750, interestingly enough.

**Comment by Shestac92** [comment]
@f0ff886f 
The scale calculation algorithm tends to calculate nice ticks with comfortable gaps according to the data range. This algorithm is quite complex and works nicely in most real cases. But in some synthetic cases like this data set (multiple nulls and then a single value for the rest of points) the algorithm can't calculate nice ticks so it falls back to the default range around that single value 0.0021.
The `min=0.002, max=0.002` is simple number formatting thing. As a default, the are 3 decimals are enabled. But you can increase the number of decimals.
