### ISSUE TITLE
Stacked area chart is rendered corrupt with sparse data points.

### ISSUE THREAD

**Issue by joshk0** [AnyChart/AnyChart#161]
This stacked area chart looks really strange. The lines and areas are weirdly disjointed and broken.

![image](https://user-images.githubusercontent.com/5368926/98961829-0033e600-24d4-11eb-91d3-ab2986b25b98.png)

[Playground](https://playground.anychart.com/DMM6C2iB/1)

This is because the categories, Monday thru Friday, and the associated data sets, do not completely align. There are some series that are not filled for every single day.

By adding zero points in each series for days where there are no points for that given day, the graph looks correct.

![image](https://user-images.githubusercontent.com/5368926/98962067-3f623700-24d4-11eb-84b9-502e05866038.png)

[Playground](https://playground.anychart.com/PUYqpALq/1)

My expectation would be that the stacked area would still look ok if there was not a point for every single (x category, y category) pair. Is there support in anychart for this sort of 'sparse' data set, or is it documented somewhere that this is a global constraint?

My use case is that I'm querying a database which won't fill the zeros for this timeseries data, so I have to do so on the client side.

**Comment by Shestac92** [comment]
@joshk0 
If you are using continuous series types like line/area/spline with missing points you should use [connectMissingPoints()](https://api.anychart.com/anychart.core.cartesian.series.Area#connectMissingPoints) settings to avoid series breaks. Anyway, it missing in the stacked area chart may lead to unexpected behavior because of missings. We will look into it and think about improving the behavior.
In this case, we recommend using column series type, it doesn't depend on the missings in the data. Here is [the modified sample](https://playground.anychart.com/SW41BhAY/0).

**Comment by joshk0** [comment]
@Shestac92, yes, using `connectMissingPoints()` doesn't help here.
And I was using column in the past, but my team preferred stacked area for this specific graph. So I tried to change it and ran into this problem. I think the intuitive behavior is to fill zeroes in when parts of the series are missing. It works well _for this type of graph._

**Comment by sturdystablestalwart** [comment]
@joshk0 

While filling with zeros is a perfectly good solution for some cases, it might not be appropriate for situations where the absence of data does not equal the data being 0. The chart does look bad with missing data points, as will every chart if the given data is wrong or badly formatted.
The solution to this situation is to fill in the missing points with zeros or to use a different, [less sensitive chart](https://docs.anychart.com/Basic_Charts/Stacked/Value/Column_Chart), as mentioned above.
Thank you for your report, and if you have any additional information or questions, I'm here to help.
