### ISSUE TITLE
Line Marker in between Columns in a Column Chart?

### ISSUE THREAD

**Issue by f0ff886f** [AnyChart/AnyChart#162]
Is it possible to place Line Markers in between columns in a Column Chart?

IE in https://playground.anychart.com/docs/v8/samples/BCT_Column_Chart_05 have a vertical line separating John and Jake. I can only get the line to appear directly in the middle of John, for example, not on the barrier of the two series (or in the middle of them, if they had a padding).

**Comment by Shestac92** [comment]
@f0ff886f 
I'm afraid it's not possible because Cartesian charts use an Ordinal scale type. This scale type is categorized, which means that all points and elements are placed inside the category (in the middle of it).
