### ISSUE TITLE
What is the itemsProvider Context's Target property?

### ISSUE THREAD

**Issue by f0ff886f** [AnyChart/AnyChart#163]
The documentation states that the itemsProvider context is a https://api.anychart.com/anychart.ui.ContextMenu.PrepareItemsContext object. It has a `target` property, which seems to contain information about the point I just right clicked, and I'd like to access that if possible.

The reason I ask is I'd like to setup a custom right click menu for a chart with `interactivitiy().selectionMode("none")`, and that causes the `selectedPoints` property's array to be empty (but on inspection of the `target` property, there seems to be enough data to reconstruct which point was clicked).

**Comment by Shestac92** [comment]
@f0ff886f 
The itemsFormatter() was not designed to provide information in the context about the clicked element. The target field always includes an instance of the chart, so there you can find the chart API. But it doesn't include information about the clicked point.
