### ISSUE TITLE
pert chart throw 'non planar'

### ISSUE THREAD

**Issue by kanouken** [AnyChart/AnyChart#164]
when two tasks has the same depends on value ..
example 
      `    var data = [

            {
                id: '1',
                duration: 30,
                name: '1',
                fullName: 'Aerodynamics'
            },

            {
                id: '2',
                duration: 50,
                name: '2',
                fullName: 'Build & Test Model'
            },

            {
                id: '3',
                duration: 35,
                name: '3',
                dependsOn:['1','2'],
                fullName: 'Structure'
            },

            {
                id: '4',
                duration: 50,
                name: '4',
                dependsOn:['1','2'],
                fullName: 'Propulsion'
            }
        ]`
how to fix ?

**Comment by kanouken** [comment]
@nymphly

**Comment by kanouken** [comment]
Anybody can help me ?

**Comment by Shestac92** [comment]
@kanouken 
This is the expected behavior. AnyChart supports only planar Pert chart. The data you are trying to apply to the chart can't be demonstrated using a planar chart, it requires intersections.

**Comment by kanouken** [comment]
@Shestac92 
thanks  very much
I can use an "task 2.1" to connect  task 3 and task 4, like this 
![QQ截图20201201125959](https://user-images.githubusercontent.com/4925886/100699302-95d8dc00-33d5-11eb-8a46-26a00005b3a4.png)

so , has  any api to set the line to  dotted line for the task 2.1  or     remove it ?

**Comment by Shestac92** [comment]
@kanouken 
I'm afraid it's not possible with the current version of the library.
