### ISSUE TITLE
error URL logo

### ISSUE THREAD

**Issue by panda-bk** [AnyChart/AnyChart#165]
error loading the logo route

![image](https://user-images.githubusercontent.com/39135977/102617413-e8293500-4117-11eb-8f19-346a5807ff30.png)
![image](https://user-images.githubusercontent.com/39135977/102617583-2f172a80-4118-11eb-95c6-ee90e9424f57.png)
![image](https://user-images.githubusercontent.com/39135977/102619357-14928080-411b-11eb-9f1d-68caa4ee21ab.png)

**Comment by Shestac92** [comment]
@pandabk 
Thank you for the report! We have just fixed the issue and now it loads correctly.
