### ISSUE TITLE
how to set different color for column chart in anystock?

### ISSUE THREAD

**Issue by RubberArchind** [AnyChart/AnyChart#166]
Hey i try to make something like [this](https://playground.anychart.com/docs/v8/samples/BCT_Column_Chart_03) in anystock but the chart doesn't even appear

Here is my data
```
{
  "x": "2020-01-02",
  "val": 41350,
  "normal": {
    "fill": "green",
    "stroke": null,
    "label": {
      "enabled": true
    }
  }
}
```

and i just wrote this for that
```
chart.plot(1).column(bfData[1])
```

how can i get the same result in anystock

**Comment by Shestac92** [comment]
@RubberArchind 
To enable individual styling in a Stock chart you should apply true flag to the chart constructor:
```
var chart = anychart.stock(true);
```
But note, that individual styling may reduce the chart performance if there are too many points with individual styling.

**Comment by RubberArchind** [comment]
@Shestac92 thanks for the answer it's work. i have another question , can i simply change xScale mode to continous with ```chart.xScale().mode('continuous');``` in anystock? [this](https://playground.anychart.com/docs/v8/samples/BCT_Line_Chart_03) doesn't work when i try it

**Comment by Shestac92** [comment]
@RubberArchind 
This function is not supported by AnyStock. The Stock xScale is already continuous (Ordinal or Scatter). But you can add gaps if it is required.

**Comment by RubberArchind** [comment]
@Shestac92 i facing some issue with that 

this what i got when using anychart 
![photo_2021-01-20_11-35-24](https://user-images.githubusercontent.com/35050952/105168410-ae9b7d80-5b4c-11eb-8aeb-37d757ee0b69.jpg)

and this what i got when using another library
![image](https://user-images.githubusercontent.com/35050952/105168467-c07d2080-5b4c-11eb-8ab9-9899bdafb5fc.png)

**Comment by Shestac92** [comment]
@RubberArchind 
It looks like the data for these two charts are different at the beginning of the series. The line series got points with dates before the first candlestick date. There's no other explanation for that. If you are sure that it is not expected behavior, please, contact support@anychart.com and provide the full chart configuration code and exactly the same data. We will review the code, reproduce the issue and provide a solution.

**Comment by RubberArchind** [comment]
New update for my problem, i try to plot it with anychart again today and it's works like charm!! 
i think i probably  misstype somthing or i add a whitespace data before in that chart, thanks for your support @Shestac92
