### ISSUE TITLE
Dynamically change colours for showcase 

### ISSUE THREAD

**Issue by mmohamud1** [AnyChart/AnyChart#167]
So I made variables for themes and changed chart colours to fill, stroke or distinctColors().items to theme. However when I click the theme buttons the theme does not dynamically change. Is there another way to this?
`/* THEMES */
  var themeOne = document.getElementById("theme-1");
  var themeTwo = document.getElementById("theme-2");
  var themeThree = document.getElementById("theme-3");
  // Set theme
  let theme = ["#23D685", "#0C3E4D", "#55565A", "#D7D7D5"];
  let themeHex = [
    "rgba(35,214,133,0.7)",
    "rgba(12,62,77,0.7)",
    "rgba(85,86,90,0.7)",
    "rgba(215,215,213,0.7)",
  ];
  // Change Themes
  themeOne.addEventListener("click", () => {
    let theme = ["#23D685", "#0C3E4D", "#55565A", "#D7D7D5"];
    let themeHex = [
      "rgba(35,214,133,0.7)",
      "rgba(12,62,77,0.7)",
      "rgba(85,86,90,0.7)",
      "rgba(215,215,213,0.7)",
    ];
    console.log(theme);
    return theme;
  });
  themeTwo.addEventListener("click", () => {
    let theme = ["#58508d", "#bc5090", "#ff6361", "#ffa600"];
    let themeHex = [
      "rgba(88,80,141,0.7)",
      "rgba(188,80,144,0.7)",
      "rgba(255,99,97,0.7)",
      "rgba(255,166,0,0.7)",
    ];
    console.log(theme);
    return theme;
  });
  themeThree.addEventListener("click", () => {
    let theme = ["#151965", "#32407b", "#515585", "#46b5d1"];
    let themeHex = [
      "rgba(21,25,101,0.7)",
      "rgba(50,64,123,0.7)",
      "rgba(81,85,133,0.7)",
      "rgba(70,181,209,0.7)",
    ];
    console.log(theme);
    return theme;
  });`

**Comment by Shestac92** [comment]
@mmohamud1 
To apply a new theme to the chart it should be recreated totally. The chart can't change the theme even partially on the fly.
The theme is applied only once when the chart is created. Then you can change chart appearance on the fly only using the chart's API.
