### ISSUE TITLE
HTML formatting of tooltips doesn't allow newlines

### ISSUE THREAD

**Issue by wkruddy** [AnyChart/AnyChart#17]
I'm trying to do something hacky since I don't have full access to rendering custom HTML for the tooltips.

On a multi-series, stacked bar chart, I'm attempting to take all the series items in a union'd tooltip, and color them independently. Unfortunately, `useHtml` and `format()` don't actually give you the flexibility to write custom HTML, only to add flavoring to it.

For instance:
```
const chart.tooltip();
tooltip.format(function () {
     const hexFill = this.b.Zg.fe.data.fill || '#000000'; // Really wish this was more accessible :)

     return `\n<div style="color:${hexFill};">${this.seriesName}: ${this.value}</div>\n`;
});
```
This colors them appropriately, but since it converts any HTML to a `<tspan fill="#000000">` it doesn't actually take into account that I want them broken on separate lines.

I've attempted to the the same with a `unionFormat()` function, reducing all of the point values into one string with a bunch of `'\n'`, to no avail. Escaping the newline doesn't help either.

Am I missing something, or is this flexibility not possible?

Actual:
![image](https://user-images.githubusercontent.com/5588561/28483751-a2b3c56e-6e23-11e7-94e0-6bd16cf45e3d.png)

Expected:
![image](https://user-images.githubusercontent.com/5588561/28483783-cc2bbe38-6e23-11e7-95c7-b8d81b7801ed.png)

Also, curious, are dropshadows going to be implemented on tooltips anytime in the future? 

Thanks!

**Comment by loki20beta** [comment]
@wkruddy looks like you are looking for this type of formatting: https://jsfiddle.net/yd7f7Laq/

```
chart.tooltip().format(function(){
     return '<br><span style="color:' + this.series.color() + ';">' + this.seriesName + ': ' + this.value + '</span>';
});
```

**Comment by loki20beta** [comment]
@wkruddy on a side note: we are moving towards fully supported HTML in tooltips but the timeline has not been established yet.

**Comment by loki20beta** [comment]
@wkruddy 
> dropshadows going to be implemented on tooltips anytime in the future?

We will look into it and let you know.

**Comment by loki20beta** [comment]
@wkruddy we are moving towards fully HTML tooltips in future releases but you can actually create custom fully HTML tooltip now https://jsfiddle.net/6ucpmLn2/1/

**Comment by wkruddy** [comment]
@loki20beta Wow, yeah, both of those examples definitely work! I didn't think of using it that way, but this is a good interim solution, so thanks a ton.
