### ISSUE TITLE
No individual formatting over 300 edges

### ISSUE THREAD

**Issue by SakiiCode** [AnyChart/AnyChart#171]
Network graph loses the individual formatting of the edges if there are more than 300 of them. They revert to the global formatting which still works.

300 edges
![correct](https://user-images.githubusercontent.com/13037299/108778879-fa7f7f00-755d-11eb-8fea-cca22cd66b98.png)

301 edges
![incorrect](https://user-images.githubusercontent.com/13037299/108778886-fce1d900-755d-11eb-8c6b-331b40ea407d.png)

[Sample project here.](https://pastebin.com/LsKG9hCz) Comment out line 401 and it will work correctly

Sorry if this is an intentional limitation, I didn't find it anywhere in the docs

**Comment by Shestac92** [comment]
@SakiiCode 
Thank you for the report!
I will discuss the issue with the dev team and back to you as soon as I get the results.

**Comment by Shestac92** [comment]
@SakiiCode 
If the number of edges gets greater than 300, then a specific optimization gets enabled. To avoid it, you can add the following line to your code and it will solve the issue:
`chart.interactivity().edges(true);`

**Comment by SakiiCode** [comment]
Nice, thank you!
