### ISSUE TITLE
[Bug] Sudden Jump in date Scroller

### ISSUE THREAD

**Issue by arthurgeron-work** [AnyChart/AnyChart#172]
Version: 8.9.0
Type: Stocks
Example: https://playground.anychart.com/Jwhp6kaO/1

- Context:
You have a stock chart with a date scroller for the x Axis, you have selected a range within the scroller. 
You have `preserveSelectedRangeOnDataUpdate` set to true.

- What happens:
 Your chart receives/adds new data to the table while you are dragging the scroller.
 The scroller suddenly jumps towards where the data was added in the chart timeline
- What should  happen:
The scroller should keep moving towards where you're dragging it and not lose track of where it was before the date was added.

- Observations
This isn't an issue caused by the mouse position, the same happens if you click and drag horizontally on the chart itself instead of the scroller.

![jumping bug](https://user-images.githubusercontent.com/71399856/109086546-88887080-76ea-11eb-810e-34b80a9f3b01.gif)

**Comment by Shestac92** [comment]
@arthurgeron-work 
In the current version of the library, the scroller keeps its ratio position when the new data comes. We will look into if it's possible to keep the date in future updates.

**Comment by arthurgeron-work** [comment]
> @arthurgeron-work 
> In the current version of the library, the scroller keeps its ratio position when the new data comes. We will look into if it's possible to keep the date in future updates.

That's odd because it keeps the date of the user isn't actively moving the scroller instead of changing the date because of the ratio.. 

Do you have any ference as to where in the code it does that change to keep the ratio after adding data ?

**Comment by arthurgeron-work** [comment]
It's quite curious to have a property called `preserveSelectedRangeOnDataUpdate` that gets completely ignored, calling this a "feature" is even more intriguing  since it completely hinders the capability to deliver a chart that updates in realtime. I wonder what'd be the reason behind preserving the ratio instead of date range on a scroller that is based upon a date/time scale.

**Comment by arthurgeron-work** [comment]
@Shestac92  It's quite curious to have a property called `preserveSelectedRangeOnDataUpdate` that gets completely ignored, calling this a "feature" is even more intriguing  since it completely hinders the capability to deliver a chart that updates in realtime. I wonder what'd be the reason behind preserving the ratio instead of date range on a scroller that is based upon a date/time scale.

Not only this, but the ratio itself isn't "preserved", it's basically reversed to the previous state that it was when the user started scrolling.

**Comment by sturdystablestalwart** [comment]
@arthurgeron-work 

Thank you for detailing the description of the observed behaviour of the chart; it will be taken into account in future releases.
Allow me to shed some light on the idea of such behaviour and relieve some of the confusion:
1. While in some cases it may feel unnatural, it can be quite beneficial to be able to [preserve visible date range](https://api.anychart.com/anychart.charts.Stock#preserveSelectedRangeOnDataUpdate) with `preserveSelectedRangeOnDataUpdate()` method
2. If you wish to preserve scroller position and don't care about changing range, it is possible if you'll pass `false` to `preserveSelectedRangeOnDataUpdate()` method or not use said method at all
3. While you're dragging the scroller with `preserveSelectedRangeOnDataUpdate(true)`, it will try to keep it's range relative to the dates visible, but every time the mouse is moved, a new position will be applied. This will become obvious in your example if you:
   1. Start dragging the scroller but do not move your mouse
   2. Give the chart some time to upload new data
   3. Then move your mouse a little.
 
Thank you for your report, and if you have any additional concerns or questions, I'm here to help.
