### ISSUE TITLE
Filling table cell dynamically 

### ISSUE THREAD

**Issue by mmohamud1** [AnyChart/AnyChart#173]
I was wondering if it was possible to fill cells in anychart.standalones.table() based on string within table.contents([[]]) e.g if a cell has the string "degraded" I want the cell to be filled 'rgba(255,187,83,0.7)'

**Comment by mmohamud1** [comment]
My current code. Which will not be viable for dynamic table contents which is the end goal 
` anychart.onDocumentReady(function () {
  
  // set stage
  var stage = anychart.graphics.create("weekly-rep-table-1");

  // Remove Watermark
  stage.credits().enabled(false);
  
  // create table
  var table = anychart.standalones.table();
  
  // set table content
  table.contents([
    [
      null,
      null,
      "Protect",
      null,
      "Detect",
      null,
      "Respond",
      null,
      "Overall Risk Rating"
    ],
    [
      null,
      null,
      "PR.IP-1",
      "PR.AC-1",
      "DE.CM-7",
      "DE.CM-3",
      "RS.MI-3",
      "RS.AN-5"
    ],[
      "Organisational InfoSec Risks",
      "External data breach",
      "Ok",
      "Degraded",
      "Ok",
      "Failed",
      "Ok",
      "Failed",
      "Degraded"
    ], [
      null,
      "Internal data breach",
      "Ok",
      "Ok",
      "Ok",
      "Ok",
      "Ok",
      "Ok",
      "Ok"
    ], [
      null,
      "Denial/Distributed Denial of Service",
      "Degraded",
      "Degraded",
      "Degraded",
      "Degraded",
      "Degraded",
      "Degraded",
      "Degraded"
    ] , [
      null,
      "Supply Chain Security compromise",
      "Failed",
      "Failed",
      "Failed",
      "Failed",
      "Failed",
      "Failed",
      "Failed"
    ]
    
  ]);

  console.log(table.contents);
  // Make null values empty cols
  table.getCell(0,0).colSpan(2);
  table.getCell(0,0).rowSpan(2);


  // make first row headers long
  table.getCell(0,2).colSpan(2);
  table.getCell(0,4).colSpan(2);
  table.getCell(0,6).colSpan(2);

  // Overall risk rating cell
  table.getCell(0,8).rowSpan(2)

  // Organisational cell
  table.getCell(2,0).rowSpan(4)

  // table headers
  table.getRow(0).height(40).fontWeight(900).fontColor('#3d6571');   // Set height 40px for the first row and bold the text
  table.getRow(1).height(20).fontWeight(900).fontColor('#3d6571');   // Set height 40px for the first row and bold the text
  table.getCol(0).width(120).fontWeight(900).fontColor('#3d6571');    // Set width 70 px for the first column and bold the text
  table.getCol(1).width(200).fontWeight(900).hAlign('left') .fontColor('#3d6571');       ;    // Set width 70 px for the second column and bold the text

  // Cell colours
  var cell1 = table.getCell(2,2);
  var cell2 = table.getCell(2,3);
  var cell3 = table.getCell(2,4);
  var cell4 = table.getCell(2,5);
  var cell5 = table.getCell(2,6);
  var cell6 = table.getCell(2,7);
  var cell7 = table.getCell(2,8);
  var cell8 = table.getCell(3,2);
  var cell9 = table.getCell(3,3);
  var cell10 = table.getCell(3,4);
  var cell11 = table.getCell(3,5);
  var cell12 = table.getCell(3,6);
  var cell13 = table.getCell(3,7);
  var cell14 = table.getCell(3,8);
  var cell15 = table.getCell(4,2);
  var cell16 = table.getCell(4,3);
  var cell17 = table.getCell(4,4);
  var cell18 = table.getCell(4,5);
  var cell19 = table.getCell(4,6);
  var cell20 = table.getCell(4,7);
  var cell21 = table.getCell(4,8);
  var cell22 = table.getCell(5,2);
  var cell23 = table.getCell(5,3);
  var cell24 = table.getCell(5,4);
  var cell25 = table.getCell(5,5);
  var cell26 = table.getCell(5,6);
  var cell27 = table.getCell(5,7);
  var cell28 = table.getCell(5,8);

  cell1.fill('rgba(36,214,131,0.7)');   
  cell2.fill('rgba(255,187,83,0.7)');   
  cell3.fill('rgba(36,214,131,0.7)');   
  cell4.fill('rgba(255,67,64,0.7)');   
  cell5.fill('rgba(36,214,131,0.7)');   
  cell6.fill('rgba(255,67,64,0.7)');   
  cell7.fill('rgba(255,187,83,0.7)');   
  cell8.fill('rgba(36,214,131,0.7)');   
  cell9.fill('rgba(36,214,131,0.7)');   
  cell10.fill('rgba(36,214,131,0.7)');   
  cell11.fill('rgba(36,214,131,0.7)');   
  cell12.fill('rgba(36,214,131,0.7)');   
  cell13.fill('rgba(36,214,131,0.7)');   
  cell14.fill('rgba(36,214,131,0.7)');   
  cell15.fill('rgba(255,187,83,0.7)');   
  cell16.fill('rgba(255,187,83,0.7)');   
  cell17.fill('rgba(255,187,83,0.7)');   
  cell18.fill('rgba(255,187,83,0.7)');   
  cell19.fill('rgba(255,187,83,0.7)');   
  cell20.fill('rgba(255,187,83,0.7)');   
  cell21.fill('rgba(255,187,83,0.7)');   
  cell22.fill('rgba(255,67,64,0.7)');   
  cell23.fill('rgba(255,67,64,0.7)');   
  cell24.fill('rgba(255,67,64,0.7)');   
  cell25.fill('rgba(255,67,64,0.7)');   
  cell26.fill('rgba(255,67,64,0.7)');   
  cell27.fill('rgba(255,67,64,0.7)');   
  cell28.fill('rgba(255,67,64,0.7)');   



  
  // set border style
  table.cellBorder("#B8B8B8");
  
  table.vAlign("middle").hAlign("center").fontSize(12);

  
  
  // set table container and initiate draw
  table.container(stage).draw();
});`

**Comment by Shestac92** [comment]
@mmohamud1 
The library doesn't provide API for that. You can implement a custom JS function that parses the incoming data and applies the color to the particular cell.
