### ISSUE TITLE
Network Graph Live Update Nodes

### ISSUE THREAD

**Issue by ThomasWu2333** [AnyChart/AnyChart#175]
I am wondering if there is a way lo live update nodes and node labels.
it seems to me that the function set and .append is not working on the network graph.
https://playground.anychart.com/yJyq7cMc/1

**Comment by Shestac92** [comment]
@ThomasWu2333 
if you need to update the label's content or add/replace points, then you need to apply to the chart the updated data.
For details, check [the sample](https://playground.anychart.com/2sSXrf17).

If you need to change the label's appearance settings, then you can call the label's API on the fly after the got rendered.
