### ISSUE TITLE
Error: 5 Description: Chart scale should be only ordinal, linear, log, date-time type. anychart-bundle.min.js:210 

### ISSUE THREAD

**Issue by BH-yasmine** [AnyChart/AnyChart#176]
this.chart.sortPointsByX(false)
        // set series type
        .defaultSeriesType('column')
        // disable y-axis
        .yAxis(false);
      this.chart.xScale(anychart.scales.ordinal);
      
      
![image](https://user-images.githubusercontent.com/46843452/117377884-31620180-aecc-11eb-904a-e8c2f872f22e.png)

**Comment by Shestac92** [comment]
@BH-yasmine 
If you are trying to apply new scale type, you should call it like a constructor function, like this:
`this.chart.xScale(anychart.scales.ordinal());`

Anyway, if you are using a Cartesian chart, then there's no need to apply the ordinal scale manually as it is the default one for this chart type.
