### ISSUE TITLE
"hovered" has private access in "com.anychart.anychart.HeatMap" 

### ISSUE THREAD

**Issue by sunflowerzf** [AnyChart/AnyChart#177]
I'm trying the latest chart code into my Android studio app, there's errors as shown in the image, which say many functions has private access, so cannot be used, how to deal with it? Thanks.

<img width="534" alt="无标题-3" src="https://user-images.githubusercontent.com/71755716/118062962-b23c6400-b3ca-11eb-980d-4155b6585e28.png">

**Comment by sturdystablestalwart** [comment]
@sunflowerzf 

I've checked but couldn't reproduce.
The issue isn't reproducible in the latest version either.
For complex issues, please email us at support@anychart.com.
Thank you for your report!
