### ISSUE TITLE
甘特图treeItemUpdate没有更新数据

### ISSUE THREAD

**Issue by LaReinaA** [AnyChart/AnyChart#178]
甘特图treeItemUpdate没有更新数据，如何获取更新后的数据

**Comment by Shestac92** [comment]
@LaReinaA 
Please, can you describe in detail how exactly you are trying to update the chart data?

**Comment by LaReinaA** [comment]
treeData.listen("treeItemUpdate", function (e) {
    var itemName = e.item.get("name");
    var actualStart = e.item.get("actualStart");
    console.log(actualStart)
});


例如：打印actualStart是初始值，不是编辑后的新数据。

LaReinaA

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AnyChart/AnyChart"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月7日(星期一) 中午11:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AnyChart/AnyChart] 甘特图treeItemUpdate没有更新数据 (#178)





 
@LaReinaA
 Please, can you describe in detail how exactly you are trying to update the chart data?

**Comment by Shestac92** [comment]
Try the following workaround to get the value on the next iteration of the JS event loop:
```
treeData.listen("treeItemUpdate", function (e) {
    var itemName = e.item.get("name");
setTimeout(function() {
    var actualStart = e.item.get("actualStart");
    console.log(actualStart)
}, 0);
});
```
