### ISSUE TITLE
New Calendar Charts functionality

### ISSUE THREAD

**Issue by mmohamud1** [AnyChart/AnyChart#179]
I would like to implement the new calendar chart https://www.anychart.com/products/anychart/gallery/Calendar_Chart/ . I was wondering if there is a way to add point click functionality if not is there a timeline for this?

**Comment by Shestac92** [comment]
@mmohamud1 
Unfortunately, the current version of the Calendar chart doesn't support this interactivity. The current roadmap doesn't include this improvement, but we will take it into account for future updates.

**Comment by sturdystablestalwart** [comment]
@mmohamud1 
 In the current version(8.12.0) a `pointClick` event has been introduced. How it works can be seen in [this sample ](https://playground.anychart.com/dLR7T9Ym/0) and in [a tutorial](https://www.anychart.com/blog/2024/03/04/javascript-calendar-charts/).
