### ISSUE TITLE
How to change size of circles in legend

### ISSUE THREAD

**Issue by GianlucaCesari** [AnyChart/AnyChart#18]
I was wondering if it's possible to change the size of the legend circles through code or css, i did not find anything in the documentations that led me to believe is possible, any confirmations?

**Comment by loki20beta** [comment]
Are you looking for iconSize: https://api.anychart.com/7.14.3/anychart.core.ui.Legend#iconSize
https://playground.anychart.com/api/7.14.3/core/ui/anychart.core.ui.Legend.iconSize_set-plain ?

**Comment by GianlucaCesari** [comment]
I tried to use it on series.legendItem() and on chart.legend(), is that the right place?

**Comment by GianlucaCesari** [comment]
I just realized I'm dumb,

chart.legend().iconSize(<n>);

resolved it for me, thank you so much!
