### ISSUE TITLE
Panning VerticalLine Chart Upward

### ISSUE THREAD

**Issue by martineboh** [AnyChart/AnyChart#180]
Hi, thanks for this wonderful product.

I am plotting a Vertical line chart of time against temperature. Data comes in every 5 seconds in realtime via socketio and I will like to pan the chart upload since the plot becomes over crowded after 30 minutes. I tried using the move(), but doesn't work for Vertical line. I have search through the docs with no results. 

Also, I want the verticalLine chart to be continuous in one end only, not both, since new data gets appended to the view area.

Thanks for any suggestions

**Comment by Shestac92** [comment]
@martineboh 
To achieve that you can use [setToPointsCount()](https://api.anychart.com/anychart.core.utils.OrdinalZoom#setToPointsCount) method. Pay attention to arguments, the 2nd one allows zooming to the end of the scale where new points get appended.
