### ISSUE TITLE
Programmatically Scroll the xScroller?

### ISSUE THREAD

**Issue by martineboh** [AnyChart/AnyChart#181]
Is it possible to programmatically scroll the xScroller of a line chart? I have a requirement for a realtime chart where after plotting 1,000 points, the plot area should move along showing just 500 plotted points. Moves again after plotting another 500 points. Works perfectly when xScroller is scrolled manually.

**Comment by Shestac92** [comment]
@martineboh 
Yes, it is possible via library API.
You can use [setTo() method](https://playground.anychart.com/api/core/utils/_samples/anychart.core.utils.OrdinalZoom.setTo) to apply start and end ratio.

And [setToValues() method](https://playground.anychart.com/oIlbPtYV) to apply start/end values of the scale.
