### ISSUE TITLE
Nodes don't have custom events

### ISSUE THREAD

**Issue by saintienn** [AnyChart/AnyChart#182]
When click in a node, should be possible to perform a custom event

**Comment by Shestac92** [comment]
@saintienn 
Do you mean nodes in Network graphs?

**Comment by saintienn** [comment]
Yes, in a Graph chart for example: I want to attach a click event listener
in a specific node to show a form or alert some value.

I see some examples in other chart types, that I can attach a event to a
point, but I try to replicate this behavior to Graph Nodes and I can't do
it.

**Comment by Shestac92** [comment]
@saintienn 
You can achieve that like in [the live sample](https://playground.anychart.com/s4RhY1MV/0) demonstrated.
