### ISSUE TITLE
Network diagram starting node positioning

### ISSUE THREAD

**Issue by Kvarkas** [AnyChart/AnyChart#184]
Is it possible to set starting position of node in network diagram? E.g. I have user in a centre, and around his friends - they can be 2, or 3 or any number (theoretically) so if its let say 1 friend I am expecting to see him at 12 o'clock, however its rotated, if its 2 I wish to see first one at 12 o'clock another one at 6 o'clock, similar for 3 or 4 - for now I am confused how i can set that without calculating manually coordinates as I don't know from data point how many friends it may have so that points amount will be but that I am sure first friend should start from 12 o'clock directions.

**Comment by Shestac92** [comment]
@Kvarkas 
The default layout is applied by the algorithm and you can't override its behavior. To achieve the desired layout, you can use [the fixed layout type](https://docs.anychart.com/Basic_Charts/Network_Graph#layout).

**Comment by Kvarkas** [comment]
is it possible to feed x,y cords by function calculations? I mean do that programmatically not manually in data, but depending on nodes amount?

**Comment by Shestac92** [comment]
@Kvarkas 
Sure, you can generate coordinates as you need. It's totally up to you.

**Comment by Kvarkas** [comment]
@Shestac92 could you advice how to make central point always stay in same place and not jumping as a flea :) 
my play [example](https://playground.anychart.com/yyOgg3P9/7)

**Comment by Shestac92** [comment]
In the fixed layout simply apply static coordinates. In forced layout, the position depends on the structure of the data and positions are applied by the algorithm.
The way you calculate/generate coordinates is totally up to you, you can implement any logic you want.

**Comment by Kvarkas** [comment]
yes I did that, but problem is that even if I set starting point to be in 0,0 coordinates with forced layout - its moving along a surface, is it possible to get it stuck? chart.bounds(0, 0, "100%", "100%"); don't seems to be working (or maybe I don't understand how to use it properly. Perhaps its a bug or feature? :D

**Comment by Shestac92** [comment]
Coordinates are relative. You should place the central node in the center among other nodes.
