### ISSUE TITLE
Network diagram - cant control labels background

### ISSUE THREAD

**Issue by Kvarkas** [AnyChart/AnyChart#185]
not sure if I am doing right but this one don't working for me, I wish to have a background on labels so they are not looks as crossed by edges, is it possible? 
My playground: https://playground.anychart.com/yyOgg3P9/1

**Comment by Shestac92** [comment]
@Kvarkas 
Unfortunately, the network labels do not support background functionality at the moment. We will take it into account for future updates.

**Comment by Kvarkas** [comment]
Is it possible then move nodes from end of edges somehow? kind of offset?

**Comment by Shestac92** [comment]
@Kvarkas Not it's not supported in the current version.

**Comment by Kvarkas** [comment]
is it possible then to make a form with same background colour and move it to be under node icon? any example of such if possible?

**Comment by Shestac92** [comment]
I'm not sure I understood you well. What form do you mean? Can you provide an example of the desired appearance?
