### ISSUE TITLE
Stock Multiple Plot  Scale DateTime 

### ISSUE THREAD

**Issue by YuriyTigiev** [AnyChart/AnyChart#186]
Hello, 

How to properly set xScale minimum and maximum date period for a stock with two plots candlestick and column?   
The scale works only if data is passed to the stock() function.  

```
      var scale = anychart.scales.dateTime();
      scale.minimum(anychart.format.parseDateTime('2007-08-27', 'yyyy-MM-dd'));
      scale.maximum(anychart.format.parseDateTime('2007-08-30', 'yyyy-MM-dd')); 
      chart.xScale(scale);    
```

**Comment by sturdystablestalwart** [comment]
@YuriyTigiev 

While there is no conventional way to set the minimum and maximum values, the `selectRange()` [method](https://api.anychart.com/v8/anychart.charts.Stock#selectRange) could be used to set the visible range for the x-axis values.
Furthermore, data that should not be displayed at all can be filtered out before being passed into the chart.
Please feel free to explore [the sample](https://playground.anychart.com/swv66WTD) I've put together to showcase the usage of the method mentioned above on an example chart close to what you've described.
Thank you for your report, and if you have any additional questions or requests, I'm here to help.
