### ISSUE TITLE
Display several y for same x with  anychart.stock ?

### ISSUE THREAD

**Issue by DAigory** [AnyChart/AnyChart#187]
```
 anychart.stock(); 
var dataTable = anychart.data.table();
    dataTable.addData([
      ["2016-12-25", 511],
      ["2016-12-25", 400],    
      ["2016-12-25", 700],      
    ])
    plot.marker(mapping2);
```
 The question is:
 How to draw  several vertical markers  with same X but different Y?

I found a way  put markers with same X to different map or database like:[https://playground.anychart.com/docs/v8/samples/STOCK_Candlestick_03](url)
```

var _ = chart.plot(0).marker(MAP1);
var _ = chart.plot(0).marker(MAP2);
```

but it strange and I need to know in advance maximum vertical identical Y for build enough data bases or maps.

**Comment by Shestac92** [comment]
@DAigory 
The data table supports points with unique X values only. It means that there is no possibility to store multiple rows with the same X date in the table. But you can rework it like this:
```javascript
dataTable.addData([
      ["2016-12-25", 511, 400, 700],
    ])
```

Now, if you need to show three points on the same X date, then you need three mappings and three series.

**Comment by DAigory** [comment]
thank you
