### ISSUE TITLE
How to hide undefined?

### ISSUE THREAD

**Issue by DAigory** [AnyChart/AnyChart#188]
How to hide empty/undefined values for  
chart type: anychart.stock();

Screen was made with next data:
```
 var dataTable2 = anychart.data.table();
        dataTable2.addData([
          ["2016-12-24", 518.40],
         ["2016-12-25",  519.34],
         
        ]);
    
        var dataTable3 = anychart.data.table();
        dataTable3.addData([
          ["2016-12-24",  undefined],
          ["2016-12-25",  524.34],
         
        ]);
        var mapping3 = dataTable3.mapAs(
            { value: 1}
          );
        var mapping2 = dataTable2.mapAs(
            { value: 1}
          );
  
```
![image](https://user-images.githubusercontent.com/9402450/148164129-12c80396-10a5-43c0-81b8-6ed064750aee.png)

With one undefined is not a big problem but what if I have 20? It would be take time to find defined value
It is useless information for my opinion and decreasing speed for understanding chart
I tried to remove line but result the same...can't find any workaround

Result the same like on screen above
```
 var dataTable2 = anychart.data.table();
        dataTable2.addData([
          ["2016-12-24", 518.40],
         ["2016-12-25",  519.34],
         
        ]);
    
        var dataTable3 = anychart.data.table();
        dataTable3.addData([        
          ["2016-12-25",  524.34],
         
        ]);
        var mapping3 = dataTable3.mapAs(
            { value: 1}
          );
        var mapping2 = dataTable2.mapAs(
            { value: 1}
          );
  
```

**Comment by Shestac92** [comment]
@DAigory 
To overcome that you can provide [custom formatting for the union tooltip](https://api.anychart.com/anychart.core.ui.Tooltip#unionFormat). 
[Here is the solution based on your code](https://playground.anychart.com/LIssuWWm).

**Comment by DAigory** [comment]
Thank you!  Problem Solved.
