### ISSUE TITLE
Hide/show series with same name together (one button)

### ISSUE THREAD

**Issue by DAigory** [AnyChart/AnyChart#189]
I have a lot of series with same name. Is it possible to group them somehow to use hide/show ability (button) on the title of  the chart?
![image](https://user-images.githubusercontent.com/9402450/148190697-fdf32b46-074f-4f28-9164-da3be0463742.png)

chart type:
 var chart = anychart.stock();

The screen was made by customize below 
```
 var a = plot.marker(mapping2);
  a.name("common_name");     
  
  var b = plot.marker(mapping3);
  b.name("common_name");

```

The best solution would be have one button for all series with same name (on the screen above two buttons)

**Comment by Shestac92** [comment]
@DAigory 
I'm afraid it is not possible with the built-in legend. Every legend item references a specific unique series. Also, series can be accessed by unique ID, not name.
So, you can use unique names or something like `common_name_A` and `common_name_B`. Or implement your own custom buttons outside the chart that will enable/disable groups of series.

**Comment by DAigory** [comment]
Implement button is a solution for me. I will aggregate them by id/name but Is it possible hide build-in legend because I will not use it and I have about 30 of them...it is overload view

**Comment by Shestac92** [comment]
@DAigory 
1. Yes, you can disable all legend items like this:
```javascript
chart.plot(N).legend(false;
```
Where N is the index of the chart plot (0, 1, 2 etc)

2. Unfortunately, it is not possible to add custom UI elements inside the chart. Custom UI elements can be placed outside the chart on your page.

**Comment by DAigory** [comment]
thanks
