### ISSUE TITLE
Anychart UI files don't exist

### ISSUE THREAD

**Issue by panovps** [AnyChart/AnyChart#19]
Files:
https://cdn.anychart.com/releases/js/8.0.0/anychart-ui.min.js
https://cdn.anychart.com/releases/css/8.0.0/anychart-ui.css

don't exists, but mentioned here:
https://docs.anychart.com/Common_Settings/UI_Controls/Context_Menu

**Comment by loki20beta** [comment]
It was a typo in docs, should be:

```
https://cdn.anychart.com/releases/8.0.0/js/anychart-ui.min.js
https://cdn.anychart.com/releases/8.0.0/css/anychart-ui.css
```
Documentation has been updated to show correct links: [AnyChart Context Menu](https://docs.anychart.com/Common_Settings/UI_Controls/Context_Menu)
