### ISSUE TITLE
when iam using, large data in y axis of heatmap, unable to display data of all rows in y axis

### ISSUE THREAD

**Issue by Harithakakumanu** [AnyChart/AnyChart#191]
y axis...is all dates of year..for 24 hours.
so i have 24*365 rows..
for every row my data is not displaying, if iam taking for 3months it is displaying, please suggest me 
![logo](https://user-images.githubusercontent.com/100674153/156131428-05cfbc6f-c0f6-4fe9-8772-1e0289b9431e.png)
.

**Comment by loki20beta** [comment]
Can you show the sample somehow?
