### ISSUE TITLE
Destroy Sankey chart

### ISSUE THREAD

**Issue by kaariwedoms** [AnyChart/AnyChart#193]
Hi how can I remove or destroy previously generated Sankey Diagram in version 8

When I am processing click action again, new svg is created again and appending

How do I can remove the previous instance, is there any workaround for it

**Comment by Bepely** [comment]
Use a chart.dispose() method to remove the chart. 

To evaluate your query properly, please provide us with a code sample or a Playground Demo. 
Playground Link - https://playground.anychart.com/
