### ISSUE TITLE
v8 alternative to threshold, error using ordinalColor

### ISSUE THREAD

**Issue by mrlowe** [AnyChart/AnyChart#196]
I'm converting a bunch of old xml linear charts from v6 to v8, and it appears the `threshold` element has been removed from the api.

I've started looking at options for setting the stroke range, but I'm getting an error when trying to use `ordinalColor()` as shown in the map documentation (link to the playground chart below), and I can't pass a function to `stroke()` because, you know, xml. I also have to admit I'm having a hard time using the documentation since so many of the chart functions have identical names but different behaviors. Ditto reading the code.

Could suggest a good way to replace `threshold`, or take a look at this error?

error with `ordinalColor()`:
https://playground.anychart.com/GLYE4CYB

**Comment by sturdystablestalwart** [comment]
@mrlowe

To replace the `threshold ` functionality, you could use the `coloreScale()` method. Here is [a sample](https://playground.anychart.com/xxsA0wPQ) that I've put together using your code as a basis to make everything work.
Allow me to additionally suggest the API reference on [coloreScale](https://api.anychart.com/v8/anychart.core.cartesian.series.Line#colorScale).
Thank you for your report, and if you have any additional questions or requests, I'm here to help.
