### ISSUE TITLE
Network visualization based on the connections of a target node

### ISSUE THREAD

**Issue by abreumorais** [AnyChart/AnyChart#197]
I would like to know if there is a way to set a node target and use a parameter to control the nodes displayed based on their distance to the target. Or similarly, it would be possible to show only the most important nodes (based on some property like the number of connections) and, by clicking on these nodes, show their connections to a certain depth.

Thanks,

**Comment by sturdystablestalwart** [comment]
@abreumorais 

While there are no inbuilt tools to what you've asked to, I've created a [sample ](https://playground.anychart.com/qeYYvUva)to showcase the way it can be done in via fill and stroke properties and a custom function.
Allow me to additionally recommend taking a look at the [Nodes](https://docs.anychart.com/Basic_Charts/Network_Graph#nodes) documentation section.
Thank you for your report, and if you have any additional questions or requests, I'm here to help.
