### ISSUE TITLE
Does not work with Java 9

### ISSUE THREAD

**Issue by tomasKa** [AnyChart/AnyChart#20]
Updating documentation to reflect that would be useful.

**Comment by loki20beta** [comment]
@tomasKa can you, please, elaborate do you mean by that? Java is Java and AnyChart is a JavaScript library. What part of AnyChart documentation led you to believe it is Java?

**Comment by loki20beta** [comment]
@tomasKa seems your comment referred to https://github.com/AnyChart/export-server. We will specify that there.
