### ISSUE TITLE
There is no Taiwan on the map of China

### ISSUE THREAD

**Issue by Timgdz** [AnyChart/AnyChart#200]
![image](https://user-images.githubusercontent.com/46734541/196125594-53d5bb78-b72e-4cda-9ade-3589c26410f0.png)
![image](https://user-images.githubusercontent.com/46734541/196125640-ae5fe0fc-db9e-46e7-a4e8-0bec9ff6c14f.png)

**Comment by dlccyes** [comment]
Agreed! But actually, this is the correct China map

![image](https://user-images.githubusercontent.com/32875990/200105076-c3eaf7b1-fc8b-4940-bc87-bafc704d5a96.png)

**Comment by sturdystablestalwart** [comment]
In situations where the default map selection necessitates adjustments, there is the [opportunity to create custom maps](https://docs.anychart.com/Maps/Custom_GeoJson_Maps).
