### ISSUE TITLE
chart adds again it self when fragment restarts

### ISSUE THREAD

**Issue by ShashankMistry** [AnyChart/AnyChart#202]
I am using AnyChart in fragment and whenever the fragment restarts, it again adds new data and displays a new chart below the old chart. and AnyChart.clear() is also not working.

**Comment by sturdystablestalwart** [comment]
@ShashankMistry 

It will be hard to recommend anything without seeing the code first, but generally, you could make use of the [dispose() method](https://api.anychart.com/anychart.core.ui.Table#dispose).
Please, provide:
1. A code sample (HTML, CSS, JS) or a [playground sample](https://playground.anychart.com/)
