### ISSUE TITLE
Cannot Read properties of Undefined Reading 'BE'. Issue when clicking on the chart via mobile device

### ISSUE THREAD

**Issue by mohd676** [AnyChart/AnyChart#207]
i have an issue with the touch event listener from your charts where an error appears once the chart is used on a mobile device. i have managed to find that the event listeners in question are the touch events which i manually deleted using chrome dev, however, i could not delete them through my application. 

![image](https://user-images.githubusercontent.com/2113530/232027476-3c6b23b0-e286-4857-a8d0-c7077ade65a6.png)

![image](https://user-images.githubusercontent.com/2113530/232027624-4a0ec214-0f16-4d07-9164-21a75c7fd074.png)

Please support in resolving this matter, i am using react anychart plugin

**Comment by sturdystablestalwart** [comment]
@mohd676 

Unfortunately, the issue couldn't be reproduced. Please provide additional information, such as:
1. A code sample( HTML, CSS, JS) or [a playground demo](https://playground.anychart.com/).
2. Data sample

Thank you for your report, and if you have any additional concerns or questions, I'm here to help.
