### ISSUE TITLE
Как отключить округление и выставить нужное кол-во знаков после запятой в priceIndicator?

### ISSUE THREAD

**Issue by helloris25** [AnyChart/AnyChart#21]
Как отключить округление и выставить нужное кол-во знаков после запятой в priceIndicator?
Последняя цена моих данных 1,176545 а в лэйбле показывается 1,2

**Comment by loki20beta** [comment]
@helloris25 format them as any other label, be it axis or legend: [Formatting Price Indicator Label in AnyStock Sample](https://jsfiddle.net/up9xh0sa/)

```
var indicator = chart.plot(0).priceIndicator(0);
indicator.label().format("{%Value}{decimalsCount:4,zeroFillDecimals:true}");
```

You can use formatting function if you need more than basic formatting.
