### ISSUE TITLE
Не загружается Gantt From JSON

### ISSUE THREAD

**Issue by IgorLelyakov** [AnyChart/AnyChart#214]
Добрый день, не могу загрузить диаграмму из JSON формата.
Создал таблицу и ввел записи.
CREATE TABLE public.ganttproject (
	id varchar NULL,
	parent varchar NULL,
	"name" varchar NULL,
	baselinestart date NULL,
	baselineend date NULL,
	actualstart date NULL,
	actualend date NULL,
	progressvalue int4 NULL,
	connectto varchar NULL,
	connectortype varchar NULL
);
Выбираю записи из таблицы и формирую JSON следующей структуры
chart = {
		    "chart": {
			"type": "gantt-project",
			"title": "Проект",
			"data": Data,
			"container": "container"
		            }
	                }
и заполняю следующими данными:
{'chart': {'type': 'gantt-project', 'title': 'Проект', 'data': [{'id': '1', 'parent': 'null', 'name': 'Проект 1', 'baselinestart': '2024-02-01', 'baselineend': '2024-02-01', 'actualstart': 'null', 'actualend': 'null', 'progressvalue': '50', 'connectto': 'null', 'connectortype': 'null'}, {'id': '1_1', 'parent': '1', 'name': 'Задача 1', 'baselinestart': 'null', 'baselineend': 'null', 'actualstart': 'null', 'actualend': 'null', 'progressvalue': 'null', 'connectto': 'null', 'connectortype': 'null'}, {'id': '1_1_1', 'parent': '1_1', 'name': 'Задача 1_1', 'baselinestart': 'null', 'baselineend': 'null', 'actualstart': 'null', 'actualend': 'null', 'progressvalue': 'null', 'connectto': 'null', 'connectortype': 'null'}, {'id': '1_1_2', 'parent': '1_1', 'name': 'Задача 1_2', 'baselinestart': 'null', 'baselineend': 'null', 'actualstart': 'null', 'actualend': 'null', 'progressvalue': 'null', 'connectto': 'null', 'connectortype': 'null'}, {'id': '1_2', 'parent': '1', 'name': 'Задача 2', 'baselinestart': 'null', 'baselineend': 'null', 'actualstart': 'null', 'actualend': 'null', 'progressvalue': 'null', 'connectto': 'null', 'connectortype': 'null'}, {'id': '1_2_1', 'parent': '1_2', 'name': 'Задача 2_1', 'baselinestart': 'null', 'baselineend': 'null', 'actualstart': 'null', 'actualend': 'null', 'progressvalue': 
'null', 'connectto': 'null', 'connectortype': 'null'}, {'id': '1_2_2', 'parent': '1_2', 'name': 'Задача 2_2', 'baselinestart': 'null', 'baselineend': 'null', 'actualstart': 'null', 'actualend': 'null', 'progressvalue': 'null', 'connectto': 'null', 'connectortype': 'null'}, {'id': '1_3', 'parent': '1', 'name': 'Задача 3', 'baselinestart': 'null', 'baselineend': 'null', 'actualstart': 'null', 'actualend': 'null', 'progressvalue': 'null', 'connectto': 'null', 'connectortype': 'null'}], 'container': 'container'}}

Передаю в HTML
return render_template('gant2.html', chartData = chart)

Затем в файле HTML  применяю операцию:

var data = anychart.fromJson({{chartData|safe}});

и получаю ошибку:
anychart-core.min.js:324 Uncaught Unknown chart type: gantt-project

Файл HTML прилагаю, прошу подскажите в чем проблема
[gant_html.txt](https://github.com/AnyChart/AnyChart/files/14175657/gant_html.txt)

**Comment by sturdystablestalwart** [comment]
@IgorLelyakov 
You coul solve this issue by using the `gantt` key instead of `chart`. As in:

```JSON
{
    "gantt": {
        "type": "gantt-project",
        "title": "Проект",
        "data": [
            {
                "id": "1",
                "parent": "null",
                "name": "Проект 1",
                "baselinestart": "2024-02-01",
                "baselineend": "2024-02-01",
                "actualstart": "null",
                "actualend": "null",
                "progressvalue": "50",
                "connectto": "null",
                "connectortype": "null"
            },
            {
                "id": "1_1",
                "parent": "1",
                "name": "Задача 1",
                "baselinestart": "null",
                "baselineend": "null",
                "actualstart": "null",
                "actualend": "null",
                "progressvalue": "null",
                "connectto": "null",
                "connectortype": "null"
            },
            {
                "id": "1_1_1",
                "parent": "1_1",
                "name": "Задача 1_1",
                "baselinestart": "null",
                "baselineend": "null",
                "actualstart": "null",
                "actualend": "null",
                "progressvalue": "null",
                "connectto": "null",
                "connectortype": "null"
            },
            {
                "id": "1_1_2",
                "parent": "1_1",
                "name": "Задача 1_2",
                "baselinestart": "null",
                "baselineend": "null",
                "actualstart": "null",
                "actualend": "null",
                "progressvalue": "null",
                "connectto": "null",
                "connectortype": "null"
            },
            {
                "id": "1_2",
                "parent": "1",
                "name": "Задача 2",
                "baselinestart": "null",
                "baselineend": "null",
                "actualstart": "null",
                "actualend": "null",
                "progressvalue": "null",
                "connectto": "null",
                "connectortype": "null"
            },
            {
                "id": "1_2_1",
                "parent": "1_2",
                "name": "Задача 2_1",
                "baselinestart": "null",
                "baselineend": "null",
                "actualstart": "null",
                "actualend": "null",
                "progressvalue": "null",
                "connectto": "null",
                "connectortype": "null"
            },
            {
                "id": "1_2_2",
                "parent": "1_2",
                "name": "Задача 2_2",
                "baselinestart": "null",
                "baselineend": "null",
                "actualstart": "null",
                "actualend": "null",
                "progressvalue": "null",
                "connectto": "null",
                "connectortype": "null"
            },
            {
                "id": "1_3",
                "parent": "1",
                "name": "Задача 3",
                "baselinestart": "null",
                "baselineend": "null",
                "actualstart": "null",
                "actualend": "null",
                "progressvalue": "null",
                "connectto": "null",
                "connectortype": "null"
            }
        ],
        "container": "container"
    }
}
```
But I'm confused as to why are you loading an almost complete configuration as json and then configure the chart in js again?

**Comment by IgorLelyakov** [comment]
Большое спасибо!
Пытаюсь научиться использовать ваш пакет и не все понимаю, если дополните - исправите код буду очень благодарен.
