### ISSUE TITLE
Как вывести значение в колонке в Диаграмме Ганта

### ISSUE THREAD

**Issue by IgorLelyakov** [AnyChart/AnyChart#215]
Добрый день!

Прошу подскажите пожалуйста - как вывести значение например в колонке newColumn2 (например baselinestart)
Прошу подскажите пожалуйста  - почему не отображается графическая данные.

<html>
<head>
   <script src="https://cdn.anychart.com/releases/8.12.0/js/anychart-core.min.js" type="text/javascript"></script>
   <script src="https://cdn.anychart.com/releases/8.12.0/js/anychart-gantt.min.js" type="text/javascript"></script>
  <script src="https://cdn.anychart.com/releases/8.12.0/js/anychart-ui.min.js" type="text/javascript"></script>
  <script src="https://cdn.anychart.com/releases/8.12.0/js/anychart-exports.min.js"></script>  
  <script src="https://cdn.anychart.com/releases/v8/js/anychart-data-adapter.min.js"></script>
  <link rel="stylesheet" href="https://cdn.anychart.com/releases/8.12.0/css/anychart-ui.min.css"/>
  <link rel="stylesheet" type="text/css" href="https://cdn.anychart.com/releases/8.12.0/fonts/css/anychart-font.min.css"/>

</head>
<body>
    <div id="container"></div>
    <script>
        anychart.onDocumentReady(function () {   
            
            var gant = {{ chartData|tojson|safe }};
            console.log('gant:', gant);

            var treeData = anychart.data.tree(gant, 'as-table');
            console.log('treeData:', treeData);

            var chart = anychart.ganttProject();
            // set data for the chart
            chart.data(treeData);

            var newColumn2 = chart.dataGrid().column(2);
            newColumn2.labels().format({{baselinestart}});
           
            chart.container("container");  
            // initiate drawing the chart
            chart.draw();
            chart.edit(true);
        });  
  
      </script>
</body>
</html>

![scrin1](https://github.com/AnyChart/AnyChart/assets/79909671/cfee77c3-8131-4913-824c-a7a7d9a52840)

Ниже массив из таблицы, который выбираю из БД:

[{'id': '1', 'parent': 'null', 'name': 'Проект 1', 'baselinestart': '2023-02-01', 'baselineend': '2023-12-21', 'actualstart': '2023-02-05', 'actualend': '2023-12-31', 'progressvalue': '50', 'connectto': 'null', 'connectortype': 'null'}, {'id': '1_1', 'parent': '1', 'name': 'Задача 1', 'baselinestart': '2023-02-01', 'baselineend': '2023-04-01', 'actualstart': 'null', 'actualend': 'null', 'progressvalue': '10', 'connectto': 'null', 'connectortype': 'null'}, {'id': '1_1_1', 'parent': '1_1', 'name': 'Задача 1_1', 'baselinestart': '2023-02-01', 'baselineend': '2023-03-01', 'actualstart': 'null', 'actualend': 'null', 'progressvalue': '50', 'connectto': 'null', 'connectortype': 'null'}, {'id': '1_1_2', 'parent': '1_1', 'name': 'Задача 1_2', 'baselinestart': '2023-03-02', 'baselineend': '2023-04-01', 'actualstart': 'null', 'actualend': 'null', 'progressvalue': '50', 'connectto': 'null', 'connectortype': 'null'}, {'id': '1_2', 'parent': '1', 'name': 'Задача 2', 'baselinestart': '2023-04-02', 'baselineend': '2023-09-01', 'actualstart': '2023-04-02', 'actualend': '2023-09-25', 'progressvalue': '65', 'connectto': 'null', 'connectortype': 'null'}, {'id': '1_2_1', 'parent': '1_2', 'name': 'Задача 2_1', 'baselinestart': '2023-04-02', 'baselineend': '2023-06-01', 'actualstart': '2023-04-03', 'actualend': '2023-06-01', 'progressvalue': '40', 'connectto': 'null', 'connectortype': 'null'}, {'id': '1_2_2', 'parent': '1_2', 'name': 'Задача 2_2', 'baselinestart': '2023-06-02', 'baselineend': '2023-09-01', 'actualstart': '2023-06-02', 'actualend': '2023-09-20', 'progressvalue': '40', 'connectto': 'null', 'connectortype': 'null'}, {'id': '1_3', 'parent': '1', 'name': 'Задача 3', 'baselinestart': '2023-09-02', 'baselineend': '2023-12-21', 'actualstart': '2023-09-10', 'actualend': '2023-12-31', 'progressvalue': '70', 'connectto': 'null', 'connectortype': 'null'}]

**Comment by sturdystablestalwart** [comment]
@IgorLelyakov
It seems that there is a discrepancy between the expected keys and provided ones, I would suggest using the camel case as shown in [documentation](https://docs.anychart.com/Gantt_Chart/Project_Chart#data). Below is the fixed example of your data. 
```json
{
      "id": "1",
      "parent": "null",
      "name": "Проект 1",
      "baselineStart": "2023-02-01",
      "baselineEnd": "2023-12-21",
      "actualStart": "2023-02-05",
      "actualEnd": "2023-12-31",
      "progressValue": "50",
      "connectTo": "null",
      "connectorType": "null"
},
``` 
To have custom column display the `baselineStart `you just need to fallow the [documentation on formatters](https://docs.anychart.com/Gantt_Chart/Data_Grid/Columns#text_(labels)) and use `newColumn2.labels().format('{%baselineStart}')`
Thank you for your question, if any other questions will come up, don't hesitate to ask, I'm here to help.

**Comment by IgorLelyakov** [comment]
Добрый день!
Спасибо за ответ, заменил как вы предложили.
Выдает следующую ошибку:
File "d:\Python\Projects1\templates\gant3.html", line 31, in template
    newColumn2.labels().format('{%baselineStart}');
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'baselineStart'.

**Comment by sturdystablestalwart** [comment]
@IgorLelyakov 
I've put together [a working sample](https://playground.anychart.com/rdT08gfe) for you. It seem that something interferes with normal behaviour of the chart, could you try removing any additional libraries and re-testing.
Thank you for your question, if any other questions will come up, don't hesitate to ask, I'm here to help.

**Comment by IgorLelyakov** [comment]
Спасибо за ответ, да действительно влияет на поведение графика и ошибку, то что я использую библиотеку  flask python и оператор render_template. В ней используется  шаблонизатор Jinja2, в котором команды обычно обрамляются символами %....% ( в начале и в конце команды) и поэтому выдается ошибка, скажите можно ли без символа % использовать оператор newColumn2.labels().format('{%baselineStart}'), есть ли другой способ вывода колонки или мне надо отказаться от использования flask python?

**Comment by sturdystablestalwart** [comment]
@IgorLelyakov 
I've never used Jinja2, but it seems that the syntax configuration there could be adjusted to your case as an example from `{% foo %}` to `<% foo %>` . Additionally I could recommend you testing some ways to devide the whole string into pieces:  
```js
var baselineStart = "%baselineStart"
newColumn2.labels().format('{'+baselineStart+'}');

```

**Comment by IgorLelyakov** [comment]
Огромное спасибо, все получилось

**Comment by sturdystablestalwart** [comment]
Thank you for your question, if any other questions will come up, don't hesitate to ask, I'm here to help.
