### ISSUE TITLE
Anychart Map throwing runtime error when clicked on zoomed in state

### ISSUE THREAD

**Issue by nandirishav** [AnyChart/AnyChart#216]
Hi,

**I'm using anychart to draw a world map .** I am trying to add a zoom button on the map which will toggle zoom on click . 
When the map is zoomed in , if we click on a country I trigger a function that redirects me to another page . 
But the map throws this run time error sometimes especially in mac devices - 
Error - "Cannot read properties of null ( reading 'fc') 
TypeError - Cannot read properties of null (reading 'fc') at OR.<anonymous> (https://localhost:3000/static/js/bundle.js:113502:21)

This is the map component that I have created in React - 

`import React, { useEffect, useRef, useState } from "react";
import anychart from "anychart";
import { useLocation, useNavigate, useSearchParams } from "react-router-dom";
import PortalTooltip from "../../Graphs/tooltip";
import {
  MapTooltipLabel,
  MapTooltipValueCon,
  MapTooltipWrp,
  ZoomContainer,
} from "./index.sc";
import {
  GradientLabel,
  GradientLabelBox,
  Item,
  LabelContainer,
  LabelItem,
  LabelItemContainer,
  LabelTitle,
  MapHeaderContainer,
  // TopLabelContainer,
} from "../Layout/index.sc";
import Header from "../Header";
import useQueryParams from "../../hooks/useQueryParams";
import { iso2Mapping } from "../../constants/countryIsoMapping";
import { ZoomIn, ZoomOut } from "../../assets/icons";

const AnyChartMap = ({ data: mapData = [], countryIsoCode, alert, info }) => {
  const [searchParams, setSearchParams] = useSearchParams();

  const [enableTooltip, setEnableTooltip] = useState(false);
  const [toolTipPos, setToolTipPos] = useState({ left: 0, top: 0 });
  const [tooltipData, setTooltipData] = useState();
  const [isZoomed, setIsZoomed] = useState(false);

  const navigate = useNavigate();
  const { getAllQueryParams } = useQueryParams();
  const { countryFilter = "" } = getAllQueryParams();
  const countryName = countryFilter.split("-")[0];
  const mapRef = useRef(null);

  useEffect(() => {
    if (mapData.length > 0) {
      // create map
      var map = anychart.map();
      mapRef.current = map; // Assign the map reference to the ref

      // create data set
      var dataSet = anychart.data.set(mapData);

      // create choropleth series
      var series = map.choropleth(dataSet);

      // set geoIdField to 'id', this field contains in geo data meta properties
      series.geoIdField("iso_a3");

      // Create color scale based on rank
      series.colorScale(
        anychart.scales.ordinalColor([
          { less: 1, color: "#9BD8F4" },
          { from: 1, to: 2, color: "#A8DDB5" },
          { from: 2, to: 3, color: "#F1C741" },
          { from: 3, to: 4, color: "#FB9323" },
          { from: 4, to: 5, color: "#EC2424" },
          { from: 5, to: 6, color: "#840000" },
        ])
      );

      series.hovered().fill("");

      // enable the tooltips and format them at once
      series.tooltip().title().useHtml(true); // Enable HTML for the title
      series.tooltip().titleFormat(function () {
        // 'this' refers to the data point
        return new Date().getFullYear(); // Use any field you want for the title
      });
      series.tooltip().format(function (e) {
        return e.getData("area") + " " + +e.getData("value");
      });
      series.tooltip().enabled(false);

      series.selectionMode("none");

      // set geo data, you can find this map in our geo maps collection
      // https://cdn.anychart.com/#maps-collection

      map.geoData(anychart.maps["world"]);

      // Disables zoom On Mouse Wheel
      map.interactivity().zoomOnMouseWheel(false);
      // Disables zoom on double click
      map.interactivity().keyboardZoomAndMove(false);
      // Disables zoom on double click
      map.interactivity().zoomOnDoubleClick(false);

      // set map container id (div)
      map.container("container");

      map.background().fill("#638EDC");
      map.unboundRegions().stroke({ color: "#4974C2", thickness: 0.5 });
      var margin = map.margin();

      margin.top(0);
      margin.right(67);
      margin.bottom(0);
      margin.left(67);

      // initiate map drawing
      map.draw();

      map.listen("pointMouseOver", function (e) {
        setEnableTooltip(true);
        setToolTipPos({
          ...toolTipPos,
          left: e?.originalEvent?.clientX,
          top: e?.originalEvent?.clientY - 10,
        });
        const tData = e.iterator?.f;
        setTooltipData(tData);
      });

      map.listen("pointMouseMove", function (e) {
        setToolTipPos({
          ...toolTipPos,
          left: e?.originalEvent?.clientX,
          top: e?.originalEvent?.clientY - 10,
        });
      });

      map.listen("pointMouseOut", function (e) {
        setEnableTooltip(false);
      });

      map.listen("pointClick", (e) => {
        const clickedArea = e.point.get("area");
        const clickedISO3 = e.point.get("id");
        if (clickedArea && clickedISO3) {
          navigate(
            `/food?countryFilter=${clickedArea}&countryId=${clickedISO3}`
          );
        }
      });

      // Cleanup function
      return () => {
        map.dispose(); // Dispose the map when the component is unmounted
        if (mapRef.current) {
          mapRef.current?.dispose(); // Dispose the map when the component is unmounted
        }
        // clearTimeout(zoomTimeout);
      };
    }
  }, [mapData, searchParams]); // Empty dependency array ensures the useEffect runs only once on mount

  const label = [
    "#840000",
    "#EC2424",
    "#FB9323",
    "#F1C741",
    "#A8DDB5",
    "#9BD8F4",
  ];

  const handleMapZoom = () => {
    try {
      const map = mapRef?.current;
      if (map) {
        if (isZoomed) {
          map.zoom(0); //658,257
        } else {
          map.zoomToFeature(iso2Mapping["Jordan"]);
        }
      }
      setIsZoomed((zoom) => !zoom);
    } catch (error) {
      console.log(error, "error");
    }
  };

  return (
    <div
      style={{
        width: "100%",
        height: "100%",
        borderRadius: "0.1875rem",
        // border: " 1px solid #EAEAEA",
        backgroundColor: "#638EDC",

        position: "relative",
      }}
      id="container"
    >
      <ZoomContainer onClick={handleMapZoom}>
        {isZoomed ? <ZoomOut /> : <ZoomIn />}
      </ZoomContainer>
    </div>
  );
};

export default AnyChartMap;
`

Screenshot of the error is attached
<img width="1705" alt="Screenshot 2024-02-20 at 12 46 16 PM" src="https://github.com/AnyChart/AnyChart/assets/65340002/ed0d8e88-4bb7-4752-a574-1e48e27af565">

**Comment by nandirishav** [comment]
I was able to fix this by wrapping the entire useeffect logic within  anychart.onDocumentReady method and used the dispose method before creating a new map instance

`anychart.onDocumentReady(() => {
      if (mapData.length > 0) {
        // create map
        mapRef?.current?.dispose();
        var map = anychart.map();`

**Comment by sturdystablestalwart** [comment]
Thank  you for reaching out and thank you for sharing the solution!
