### ISSUE TITLE
Vertical Line xAnchor

### ISSUE THREAD

**Issue by panovps** [AnyChart/AnyChart#22]
const date = new Date();
date.setUTCHours(4, 0, 0, 0);
controller.verticalLine({
       xAnchor: date
}).stroke({color: '#546e7a', thickness: 0.5, dash: 5});

Добавляю вертикальную линию на 4 часа UTC, ожидаю ее увидеть в 7 часов утра (UTC+3), а она всегда показывается в 4 утра в любом часовом поясе.

**Comment by loki20beta** [comment]
@panovps can you, please, provide the full sample?
--
не могли бы вы, пожалуйста, привести полный код?

**Comment by panovps** [comment]
Метод в объекте:

```
adjustChart () {
            const data = this.chartData.charts[0].data;

            const time1 = data[0].x;
            const time2 = data[data.length - 1].x;

            const controller = this.chart.plot(0).annotations();

            for (let currentTime = time1; currentTime <= time2; currentTime += 24 * 3600000) {
                const date = new Date(currentTime);
                date.setUTCHours(4, 0, 0, 0);

                date.setTime(date.getTime() - date.getTimezoneOffset() * 60 * 1000);

                controller.verticalLine({
                    xAnchor: date
                }).stroke({color: '#546e7a', thickness: 0.5, dash: 5});
            }
        }

    }
```

**Comment by loki20beta** [comment]
@panovps 
by default output timezone is zero, use:
1) outputTimezone to shift all values http://api.anychart.com/8.0.1/anychart.format#outputTimezone
2) or add timezone shift every time you add an annotation 

по умолчанию временная зона будет ноль, чистое UTC,
1) либо задавайте смещение для всего http://api.anychart.com/8.0.1/anychart.format#outputTimezone
2) либо задавайте смещение для каждой аннотации при создании
