### ISSUE TITLE
Как получить при нажатии кнопки мыши на запись в таблице в диаграмме ганта значения всех полей выбранной записи в виде массива?

### ISSUE THREAD

**Issue by IgorLelyakov** [AnyChart/AnyChart#220]
Как получить при нажатии кнопки мыши на запись в таблице в диаграмме ганта значения всех полей? Например в виде:
{Id: 1, name: 'Задача1', baselineStart: '2022-03-12', baselineEnd: '2022-08-01', ......}

Могу получить последовательно все значения:
 chart.listen("rowClick", function (e) {
                                                var itemid = e.item.get("id");
                                                console.log ('id=', itemid);
                                                itemName = e.item.get("name");
                                                console.log ('Name=', itemName);
                                                .....
                                                });

а можно ли сразу получить все поля выбранной записи?

**Comment by sturdystablestalwart** [comment]
@IgorLelyakov 
While it is a bit unconventional you can get the all fields using the `treedata.search()` method and the `la` field from the object it returns. Take a look at [a sample](https://playground.anychart.com/X4vs97w8)  I've put together.

**Comment by IgorLelyakov** [comment]
Большое спасибо!

**Comment by IgorLelyakov** [comment]
Скажите пожалуйста можно ли вывести в таблицу в Диаграмме ганта поле "id" и поле "parent" ?

**Comment by sturdystablestalwart** [comment]
@IgorLelyakov 
To add columns to the datagrid you could use the `column()` method, more on it in the [documentation here](https://docs.anychart.com/Gantt_Chart/Data_Grid/Columns#custom_columns). I've modified [previous sample](
https://playground.anychart.com/vSUbSZP9) to fit your needs. 
Take a look and feel free to ask any additional questions, I'm here to help!

**Comment by IgorLelyakov** [comment]
Большое спасибо, использую табличный вариант хранения данных, не выводится parent. Применяю следующий код:
anychart.onDocumentReady(function () {

  // create data
  var gantt = getData();
  console.log('gantt:', gantt);

  var treeData = anychart.data.tree(gantt, 'as-table');
  console.log('treeData:', treeData);

  var chart = anychart.ganttProject();
  // set data for the chart
  chart.data(treeData);

  var newColumn2 = chart.dataGrid().column(2);
  newColumn2.labels().format('{%baselineStart}');
  
  var newColumn3 = chart.dataGrid().column(3);
  newColumn3.labels().format('{%id}');
  
  var newColumn4 = chart.dataGrid().column(4);
  newColumn4.labels().format('{%parent}');

  chart.container("container");

  // initiate drawing the chart
  chart.draw();

  chart.edit(true);
});

function getData() {
  return [{
    "id": "1",
    "parent": "null",
    "name": "Проект 1",
    "baselineStart": "2023-02-01",
    "baselineEnd": "2023-12-21",
    "actualStart": "2023-02-05",
    "actualEnd": "2023-12-31",
    "progressValue": "50",
    "connectTo": "null",
    "connectorType": "null",
    "ppp": "50",
  },
   {
     "id": "2",
    "parent": "1",
    "name": "Проект 2",
    "baselineStart": "2023-02-01",
    "baselineEnd": "2023-12-21",
    "actualStart": "2023-02-05",
    "actualEnd": "2023-12-31",
    "progressValue": "50",
    "connectTo": "null",
    "connectorType": "null",
    "ppp": "30",
  },
         ];
}
![image](https://github.com/AnyChart/AnyChart/assets/79909671/829fd938-d973-4ea6-8071-01cf7c55fb1f)

**Comment by sturdystablestalwart** [comment]
@IgorLelyakov 
You could still use the code I've provided in [the last(now modified) sample](https://playground.anychart.com/T8XTDr6I)
```js
function(){

    var item = treeData.search('id', this.id);
    var parent = item.getParent();

    if (!parent) { return  "N/A" };

    var parentName= parent.la.name;
    return  parentName
  }
```

**Comment by IgorLelyakov** [comment]
Большое спасибо!!!
