### ISSUE TITLE
Labels being cut off if they are positioned on the first and last point on my line chart

### ISSUE THREAD

**Issue by mmohamud1** [AnyChart/AnyChart#222]
I have a spline chart which needs to fully cover the container (so first and last points are on the edge of the div) however I have some code showing the scores via labels on the lowest and highest point on the chart. the porblem I have occurs if the smallest or highest points are either on the first or last point of the chat as they cut off. I need a way to position the labels on the first and last points differently. Beloww is a  screenshot of my issue and my code.
`    var highestValAdded = false
    var lowestValAdded = false
    var dataArray = JSON.parse('{{.Chart.Data}}');
    dataArray = dataArray.map(function(item) {
        if (item.value === -1) {
            return { ...item, value: null }; // Spread operator to copy item and replace value
        }
        return item;
    });

    /******** TREND ********/
    //create a chart
    var chart = anychart.area();
    // create a spline area series and set the data
    var series = chart.splineArea(dataArray);
    series.connectMissingPoints(false);
    var fill = {
        keys: ["#57BEB7", "white"], // Define colors for the gradient
        angle: 270 // Set the angle of the gradient
    };
    series.fill(fill);
    series.stroke("#57BEB7")
    // labels
    series.labels(true);
    series.labels().format(function() {
        if (this.value === {{.Chart.HighestValue}} && !highestValAdded) {
            highestValAdded = true
            if ({{.Chart.HighestValue}} == {{.Chart.LowestValue}}){
                lowestValAdded = true
            }
            return this.value + "%";
        } else if (this.value === {{.Chart.LowestValue}} && !lowestValAdded) {
            lowestValAdded = true
            return this.value + "%";
        }
        return "";
    });
    series.labels().position("center-top");
    series.labels().anchor("top");
    series.labels().offsetX(5);
    series.labels().fontColor("#55565A");
    series.labels().fontWeight(600);
    // set the chart title
    chart.title().enabled(false);
    // set the titles of the axes
    var xAxis = chart.xAxis();
    xAxis.enabled(false);
    var yAxis = chart.yAxis();
    yAxis.enabled(false);
    chart.xScale().mode('continuous');
    // grid
    chart.xGrid().enabled(true);
    chart.xGrid().stroke("#f0f0ef");
    // tooltip
    chart.tooltip().format((d) => {
        return `Score: ${d.value}%`
    });
    chart.tooltip().allowLeaveStage(true);
    var interactivity = chart.interactivity();
    interactivity.selectionMode("none");
    var margin = chart.margin();
    var padding = chart.padding();

    series.markers()
        .type('circle')
        .size(1)
        .fill("#57BEB7")
        .stroke("none");

    margin.left(0);
    margin.right(0);
        margin.bottom(0);
        margin.top(0);
    padding.left(0);
    padding.right(0);
    padding.bottom(0);
    padding.top(0);
    // set the container id
    chart.container("chart-{{ .CardId }}");
    // initiate drawing the chart
    chart.draw();`
<img width="880" alt="Screenshot 2024-03-13 at 11 04 41" src="https://github.com/AnyChart/AnyChart/assets/63135402/24a47763-2404-471e-b6a6-71b2c94e437b">

**Comment by mmohamud1** [comment]
any help would be greatly appreciated

**Comment by sturdystablestalwart** [comment]
@mmohamud1 
It would be easier for me to help you if you could isolate the chart code from any additional libraries or framework syntax and present some data to test the chart on. 
At this point I could suggest you looking into the [wordWrap()](https://api.anychart.com/anychart.core.ui.LabelsFactory.Label#wordWrap) and [positionFormatter()](https://api.anychart.com/anychart.core.ui.LabelsFactory.Label#positionFormatter) methods.
As to the workaround you've found you could keep going the same route and try setting up the `offsetX()` on [pointMouseOver](https://api.anychart.com/anychart.enums.EventType#category-point-event-types) event.

**Comment by mmohamud1** [comment]
this was the solution if it helps anyone 
`    // make sure the positions for the first and last label do not overflow
    series.labels().positionFormatter(function () {
        if (this.value.x === 0) {
            return {x: this.value.x + 22, y: this.value.y}
        } else if (this.value.x === document.getElementById('chart-{{.CardId}}').offsetWidth) {
            return {x: this.value.x - 22, y: this.value.y}
        } else {
            return {x: this.value.x, y: this.value.y}
        }
    });`
