### ISSUE TITLE
`zoomOnMouseWheel` missing from type definition for `Interactivity`

### ISSUE THREAD

**Issue by zainbhaila** [AnyChart/AnyChart#223]
`anychart.core.utils.Interactivity` should have the following functions available:

```
        zoomOnMouseWheel(): boolean;
        zoomOnMouseWheel(value: boolean): anychart.core.utils.Interactivity;
```

See documentation here: https://docs.anychart.com/Basic_Charts/Timeline_Chart#behavior

**Comment by sturdystablestalwart** [comment]
@zainbhaila 
You're right, this will be queued to be fixed in the future releases.
Thank you for your report, and if you have any additional concerns or questions, I'm here to help.
