### ISSUE TITLE
В режиме редактирования не отображаются в data grid новые введенные значения полей actualStart, actualEnd, baselineStart, baselineEnd, progress, parent

### ISSUE THREAD

**Issue by IgorLelyakov** [AnyChart/AnyChart#226]
В режиме редактирования отображаются в data grid новое введенное значение поля name, но не отображаются в data grid новые введенные значения полей actualStart, actualEnd, baselineStart, baselineEnd, progress, parent. 
Есть ли возможность отображать новые введенные значения в этих полях или это возможно только для поля name?

Второй вопрос - как вывести "parent" в treeData.listen("treeItemMove", function (e) {
          var itemName = e.item.get("name");
          var itemId = e.item.get("id");
          var itemParent = e.item.get("parent");
          chart.title(itemId + itemName + itemParent);
                      });
[массив данных.txt](https://github.com/AnyChart/AnyChart/files/14772123/default.txt)
[Исходные данные1.txt](https://github.com/AnyChart/AnyChart/files/14801394/1.txt)

![image](https://github.com/AnyChart/AnyChart/assets/79909671/38944de4-c6b3-4deb-9d99-592b57fda999)

**Comment by sturdystablestalwart** [comment]
@IgorLelyakov 

Q1: Is it possible to keep changes in the custom columns?
A1: Sure, you'll need to use different column set-up by utilizing `setColumnFormat()` method and provide updates to values with  `onEditStart()` and `onEditEnd()` as shown in [the sample that I've put together for you](https://playground.anychart.com/uUUiGRzT).  

Q2: How do I get a parent of an element assigned to a variable?
A2: You could do that by using the `getParent()` method as shown in the shown in the 18 line of the sample provided above.
Using the code you've provided:
```js
treeData.listen("treeItemMove", function (e) {
  var itemName = e.item.get("name");
  var itemId = e.item.get("id");
  var itemParent = e.item.getParent();
  chart.title(itemId + itemName + itemParent);
});

```

**Comment by IgorLelyakov** [comment]
Огромное спасибо за ответ и пример!

**Comment by sturdystablestalwart** [comment]
Thank you for your question, if any new questions will come up, don't hesitate to reach out, I'm here to help.
