### ISSUE TITLE
Можно ли использовать одновременно горизонтальный скроллер и toolbar

### ISSUE THREAD

**Issue by IgorLelyakov** [AnyChart/AnyChart#231]
Добрый день, не выводит горизонтальный скроллер, если установлен toolbar.
Если убрать toolbar, то появиться горизонтальный скроллер.
Можно ли оставить toolbar и при этом видеть горизонтальный скроллер?
[Gant1.txt](https://github.com/AnyChart/AnyChart/files/15062259/Gant1.txt)

**Comment by sturdystablestalwart** [comment]
@IgorLelyakov 

Sure, you can use both of them at the same time, you just need to add a toolbar and you are ready to go. Take a look at [the modified sample](https://playground.anychart.com/vQlCrb6w) from the previous question. Note that both the toolbar and the scroller a present.
![image](https://github.com/AnyChart/AnyChart/assets/72163215/b17be0ff-fc8b-48bb-8f19-c6de5c312808)

**Comment by IgorLelyakov** [comment]
Большое спасибо!
