### ISSUE TITLE
Проблема с подключением календаря

### ISSUE THREAD

**Issue by IgorLelyakov** [AnyChart/AnyChart#232]
Добрый день, пишет ошибку при подключении календаря, прошу посмотрите пожалуйста.
Добавил библиотеку ( в конце списка библиотек)
 <script src="https://cdn.anychart.com/releases/8.12.1/js/anychart-calendar.min.js"></script>

И вставил из примера код:
var calendar = anychart.scales.calendar();
calendar.weekendRange([0,6]);

**Comment by sturdystablestalwart** [comment]
@IgorLelyakov 
Could you explain what were you trying achieve?
Please, include a link to the mentioned example of the code.

**Comment by IgorLelyakov** [comment]
Пытаюсь разобраться с календарем
ссылка ниже
https://playground.anychart.com/api/v8/scales/_samples/anychart.scales.Calendar.availabilities

**Comment by sturdystablestalwart** [comment]
@IgorLelyakov 
Thank you for the additional info. 

1. Don't add calendar module, as it is a calendar chart module and got nothing to do with what you've found and what you need.
2. Links that you've provided lead to the functionality of a resource chart( not to be mistaken for gantt resource chart)
3. The calendar that you need is accessed with `chart.xScale().calendar()`  in your case

I've created [a sample](https://playground.anychart.com/7pf95bdq) for you to look into.
You could also access [the API of a calendar](https://api.anychart.com/v8/anychart.core.gantt.Calendar) to further customise your chart.

**Comment by IgorLelyakov** [comment]
Огромное спасибо за пример!
