### ISSUE TITLE
Событие "row MouseUp" срабатывает 2 раза, как различить 1-е и 2-е событие

### ISSUE THREAD

**Issue by IgorLelyakov** [AnyChart/AnyChart#233]
Событие row MouseUp при клике на табличную часть диаграммы ганта срабатывает 2 раза, как различить 1-е и 2-е событие.
(Если на графической части диаграммы ганта зажать в режиме редактирования начало или конец задачи и потащить а затем отпустить то событие row MouseUp срабатывает 1 раз)

Так же 2 раза срабатывают событие dataTable.listen("treeItemUpdate", function (e) { console.log ('treeItemUpdate'); ....
Как различать 1-е и 2-е события, потому что я на событие вешаю операцию обновления данных в БД, и из-за 2-х событий одна и та же операция обновления выполняется 2 раза.
![image](https://github.com/AnyChart/AnyChart/assets/79909671/70496a59-36ca-4c67-a308-0ebf9321a250)
[Gant1.txt](https://github.com/AnyChart/AnyChart/files/15110221/Gant1.txt)

**Comment by sturdystablestalwart** [comment]
@IgorLelyakov 

You could use a workaround by setting a `timeOut` as shown in the code snippet below.
```js
  var timeOut
  chart.listen("rowMouseUp", function (e) {
    if (timeOut){clearTimeout(timeOut);}
    timeOut = setTimeout(function(){
      console.log ('rowMouseUp');      
    });
  });
```
We will investigate further and address the issue in future updates.

**Comment by IgorLelyakov** [comment]
Большое спасибо, все сработало!

**Comment by sturdystablestalwart** [comment]
After the release v8.13.1 `rowMouseUp `is fired only once. `treeItemUpdate` is fired twice as there are two updates( one for the start and one for the end of the `treeItem`), so this behaviour is normal and expected.
