### ISSUE TITLE
В chart.listen("connectorSelect"...) дублируется операция удаления разъема

### ISSUE THREAD

**Issue by IgorLelyakov** [AnyChart/AnyChart#235]
Добрый день!

chart.listen("connectorSelect", function (e) {
                                console.log ('connectorSelect');
                            var sourceId = e.fromItem.get("id");
                                console.log ('sourceId=', sourceId);
                            document.addEventListener('keyup', function(event) {
                                if (event.key === 'Delete') {
                                        console.log('Клавиша Delete нажата');
                                    var id = sourceId;
                                    var connectTo = null;
                                    var connectorType = '';
                                    var record2 = {id, connectTo, connectorType};
                                        console.log ('record2=', record2);
                                }
                            });
                      
            }); 
В этой операции после удаления 1-о разъема, происходит удаление 1-о разъема.
Но если затем выбрать и удалить 2-й разъем, то происходит повторное удаление 1-о разъема и 2-о разъёма.
Далее, если выбрать и удалить 3-й разъем, то происходит повторное удаление 1-о и 2-о разъемов и удаление 3-о разъема.
Я на эту операцию удаления вешаю операцию удаления в БД, как избавиться от повторений?
![image](https://github.com/AnyChart/AnyChart/assets/79909671/3710fc92-11c6-4fdc-8599-4c8ddb801ad1)
[Gant1.txt](https://github.com/AnyChart/AnyChart/files/15246209/Gant1.txt)

**Comment by sturdystablestalwart** [comment]
@IgorLelyakov 

It seems that you're missing the `options`attribute in the `addEventListener` method. The issue is you do delete a connector, but you create and leave a listener toa delete key be, so it keeps triggering. Below is a corrected code sample, and you also free to explore [a sample](
https://playground.anychart.com/rajC2v96) that I've put together for you.
```js
  chart.listen("connectorSelect", function (e) {
    console.log ('connectorSelect');
    var sourceId = e.fromItem.get("id");
    console.log ('sourceId=', sourceId);
    document.addEventListener(
      'keyup', 
      function(event) {
        if (event.key == 'Delete') {
          console.log('Клавиша Delete нажата');
          var id = e.fromItem.get("id");
          var connectTo = null;
          var connectorType = '';
          var record2 = {id, connectTo, connectorType};
          console.log ('record2=', record2);
        }},
      {once: true}
    );
  });
```

**Comment by IgorLelyakov** [comment]
Большое спасибо!
