### ISSUE TITLE
Chart.lineMarker() Not Found for stock/ candlestick charts

### ISSUE THREAD

**Issue by met68** [AnyChart/AnyChart#239]
I am trying to add multiple horizontal lines to a stock chart (candlesticks).

But when I try the following code, it keeps telling me that lineMarker() is not a function.

`let chart = anychart.stock();
var lineMarker = chart.lineMarker();`

The documentation here: https://docs.anychart.com/Stock_Charts/Axes refers to lineMarkers, suggesting that these should be available with stock charts.

I know I can also use horizontal line annotations, but I like that lineMarker() can take an index, allowing me to easily and programatically add multiple horizontal lines to a chart.

Am using version 8.12.1

Any help would be much appreciated.

**Comment by sturdystablestalwart** [comment]
@met68 
You can achieve required behaviour by adding `plot()` method into the `lineMarker` declaration as shown in the code snippet below:
```js
  var chart = anychart.stock();

  var lineMarker = chart.plot(0).lineMarker(0);
  lineMarker.axis(chart.plot().yAxis())
    .value(513)
    .stroke("red");
```
You also are free to explore [a sample](https://playground.anychart.com/M8YX5I00) i've put together.
Thank you for your request, and if you have any additional questions or concerns, please, feel free to usk; I'm here to help!

**Comment by met68** [comment]
Hi Alexander,

As a quick follow-on question to the above, is there a way to add a label to each lineMarker (i.e. lineMarker(0), lineMarker(1) etc.) displaying for instance the value of each lineMarker?

Mark
