### ISSUE TITLE
AnyChart calendar - Different stroke styles for different values

### ISSUE THREAD

**Issue by qwer-lives** [AnyChart/AnyChart#241]
Is there any way to achieve this? The library doesn't seem to support it.

I tried hacking some stuff around it (manually modifying the path elements after the graph is created based on the contents) but it doesn't really work. I basically want a way to fill based on value (which already works), but at the same time highlight some of the cells based on some property of the value, regardless of the fill.

**Comment by sturdystablestalwart** [comment]
It will be hard to recommend anything without seeing the code first, please provide the following items, so I can assist you better:

1. [Playground demo](https://playground.anychart.com/) / HTML, CSS, and JS code
2. Data sample

Thank you for your report, and if you have any additional questions or requests, I'm here to help.

**Comment by qwer-lives** [comment]
You can find a very simple example of what I mean [here](https://playground.anychart.com/KsrKscVB/2).

Notice how in the original data I have an "important" field, and I would like to highlight the elements that have it set to true somehow. One way would be to have different stroke color for them, for example (as mentioned in the title of this issue), but I'd be fine with other suggestions too.

**Comment by sturdystablestalwart** [comment]
@qwer-lives

You are correct at this time what you described cannot be achieved with conventional means.
Yet if I understood correctly the `important` and `type` properties are bound by the same logic and you could use a custom function to set the stroke of a day, as shown at [the sample](https://playground.anychart.com/eenU5N5T) and a code snippet below.
```js
  var days = chart.days();
  days.normal().stroke(function(){
    return this.value == 1 ? "blue" : "red";
  });
```

Thank you for your report, we will make sure to add a more direct way of implementing this behaviour in upcoming releases.

**Comment by qwer-lives** [comment]
I wasn't aware that this was possible! `important` and `type` are not actually bound by the same logic in the real data, but for my particular use case I can hack around it by encoding both in `value`, until there's a more direct solution.

Thank you!
