### ISSUE TITLE
NPM package is still on 7.14

### ISSUE THREAD

**Issue by calebeaires** [AnyChart/AnyChart#25]
I am using anycharts with NPM, but packate is on 7.14 version. Will npm package be updated to 8.0 soon?

**Comment by RomanLubushkin** [comment]
@calebeaires , thank you for your report!
By a mistake 7.14.4 (which was released right after 8.0.1) was set by 'latest' version, we will try to fix it. For now, you can install AnyChart v8 using following command:
```
npm install anychart@8.0.1
```

**Comment by RomanLubushkin** [comment]
@calebeaires , we have fixed the problem, now AnyChart 8.0.1 is set as default version and can be install as follows
```
npm install anychart
```
