### ISSUE TITLE
error: invalid 8.0.1.zip file on Get Offline Version (Windows 7)

### ISSUE THREAD

**Issue by brentbowers** [AnyChart/AnyChart#26]
When I try to extract the 8.0.1 version using Get Offline Version, "Windows cannot complete the extraction" and "...\8.0.1.zip is invalid".  

Thanks

**Comment by Shestac92** [comment]
Thank you for your report! We will check it and back to you soon.

**Comment by Shestac92** [comment]
Yes, there's a trouble with saving offline version. We will fix it as soon as possible. Thank you for this report!
