### ISSUE TITLE
AnyChart has incompatibilities with postss-loader autoprefixer

### ISSUE THREAD

**Issue by calebeaires** [AnyChart/AnyChart#28]
Anychart css make angular-cli build show annoying warnings: 

```
WARNING in ./node_modules/css-loader?{"sourceMap":false,"import":false}!./node_modules/postcss-loader/lib?{"ident":"postcss","sourceMap":false}!./node_modules/anychart/dist/css/anychart-ui.min.css
(Emitted value instead of an instance of Error) autoprefixer: 
/Users/computer/Documents/base/base-one/node_modules/anychart/dist/css/anychart-ui.min.css:1:10719: Gradient has outdated direction syntax.
 New syntax is like `to left` instead of `right`.
```

**Comment by Shestac92** [comment]
@calebeaires 
This issue is known already. We are going to update css in the nearest future to avoid these warnings.

**Comment by Shestac92** [comment]
@calebeaires 
We are glad to inform you that we have fixed warnings related to CSS while compiling.
The fixed dev-preview is available with the following managers:
yarn add anychart@8.1.0-dev-preview-2
npm install anychart@8.1.0-dev-preview-2

Also, the fix will be included in the next public release.

**Comment by calebeaires** [comment]
That`s good. I have tested. Can`t wait to the next release! :)
