### ISSUE TITLE
Themes references "blendedHueProgression" of anychart color object

### ISSUE THREAD

**Issue by null4bl3** [AnyChart/AnyChart#29]
Hi guys. I am trying to setup your awesome chart modules here, and have encountered something a bit strange. While trying to setup the most simple tag cloud chart i run into this error:

`TypeError: Cannot read property 'blendedHueProgression' of undefined`

The error stems from using both the darkEarth and darkTurquise theme downloaded from the official anychart site. It points to this function in the themes: 

`defaultOrdinalColorScale: {
      autoColors: function(a) {
        return b.anychart.color.blendedHueProgression("#b2dfdb",
          "#00838f", a)
      }
    }`

Which it here claims that .color is undefined.

`dark_turquoise.js:23:41
/node_modules/anychart/dist/js/anychart-bundle.min.js:1927:444`

There is no special configuration being used just the very most basic setup:

`var chart = anychart.tagCloud(data);
    chart.container('container');
    chart.draw();`

Where data is a short list structured after the documentations example of [{ x: "title", value: 4 }]

Any thoughts on how to further debug this issue ?

**Comment by Shestac92** [comment]
@null4bl3 
Thank you for your report! I've been trying to reproduce the same issue but I didn't succeed. 
Here is an example of a simple tag cloud with mentioned themes, but AnyChart always uses the last set theme and doesn't throw errors  - https://playground.anychart.com/fDvKXIYv
Could you provide us the full listing of creating chart code and applying themes, please? Are themes included in HTML? Which version of AnyChart do you use?
These details will help us a lot reproduce and fix then this trouble.
