### ISSUE TITLE
ANDROID - Regarding polar chart ! 

### ISSUE THREAD

**Issue by achinverma** [AnyChart/AnyChart#30]
Hi,

i have seen your library and i want to use polar chart , i want to make a polar chart like below in screenshot , can i customize your polar chart as y0u can see in the screenshot.

1) can i set the random color for each arc in the circle as now all in blue color ?.
2) progress of a particular section in percentage - as you can see in the image below , like if i have 40 % then my arc will be filled 40% .
![brush- 1](https://user-images.githubusercontent.com/2811593/36187638-ae3b633c-116c-11e8-985a-cbac3f0c6140.png)

**Comment by Shestac92** [comment]
@achinverma 
Please, check the answer in your previous opened issue - https://github.com/AnyChart/AnyChart-Android/issues/1
