### ISSUE TITLE
Chaining functions does not work as expected using definitions

### ISSUE THREAD

**Issue by mebibou** [AnyChart/AnyChart#33]
I was using anychart in TypeScript before and didn't realize there were definitions in the anychart dist folder because they are not being picked up automatically like other libraries do (that's not the bug I report here though). Now that I added the definitions, I am getting many errors when I do something like:
```typescript
export class Test {
  private chart: anychart.charts.CircularGauge;

  init() {
    this.chart.stroke(null).padding(0).margin(5).startAngle(270).sweepAngle(180);
  }
}
```
which gives the error: `Property 'startAngle' does not exist on type 'Chart'`, even though this definitely works.

The reason is because the definition of `margin` is:
```typescript
margin(value: ...): anychart.chart.Core;
```
when it should be something like:
```typescript
margin<T>(value: ...): T;
```
which will just give you the type of the component asking for it. Actually, I'm a bit puzzled of the definition file and how complicated it looks (and make my Atom so slow because of the huge amount of definitions in there, which a lot of them are duplicated it seems)

I'm using version `8.2.0-preview-0103`

**Comment by Shestac92** [comment]
@mebibou 
Thank you for the report! Yes, this chaining works with pure JS. I will report it to our dev team to consider the fix for it.

**Comment by Shestac92** [comment]
@mebibou 
Due to technical difficulties, the fixed Typedefs will be released with the next minor update (during next two weeks). I will update you when the release becomes available.

**Comment by Shestac92** [comment]
@mebibou 
Our team has prepared a dev-preview of 8.2.1 update and you can try it in your projects. This update includes many bug fixes of index.d.ts.
To get this update replace in ‘package.json’ the current AnyChart dependence with the following  "anychart": "8.2.1-rc.0"
Or you can download it manually via NPM: $ npm install anychart@8.2.1-rc.0	
Very soon our team will provide public release of 8.2.1 update.

**Comment by mebibou** [comment]
yes works now, thanks
