### ISSUE TITLE
listen interface missing the event parameter

### ISSUE THREAD

**Issue by mebibou** [AnyChart/AnyChart#34]
When using TypeScript and the definitions, this causes an error:
```typescript
const chart = anychart.stock();
chart.listen('selectedrangechangefinish', (event) => {});
```
Because the definitions states the function does not take any arguments, event though this one has an event . Could you add it?

**Comment by Shestac92** [comment]
@mebibou 
Thank you for your report! This issue is already known and our dev team is preparing a fix for this. We will notify you here when the fix becomes available.

**Comment by Shestac92** [comment]
@mebibou 
Our team has prepared a dev-preview of 8.2.1 update and you can try it in your projects. This update includes many bug fixes of index.d.ts.
To get this update replace in ‘package.json’ the current AnyChart dependence with the following  "anychart": "8.2.1-rc.0"
Or you can download it manually via NPM: $ npm install anychart@8.2.1-rc.0	

With this update, you can get access to event object in a listener.
```javascript
this.chart.listen('rowSelect', function() {
    event.preventDefault();
  });
```

Very soon our team will provide public release of 8.2.1 update.
