### ISSUE TITLE
Definition missing for charts.Scatter.xAxis.labels.format

### ISSUE THREAD

**Issue by mebibou** [AnyChart/AnyChart#35]
This code does not work when using the definitions:
```typescript
const chart = anychart.scatter();
this.chart.xAxis().labels().format((value) => {
  // format the value
});
```

**Comment by Shestac92** [comment]
@mebibou 
Please, try the following approach to enable formatting function:
```javascript
    this.chart.xAxis().labels().format(function() {
      return this.value;
    });
```
In the context 'this' you can find many useful info about the label, you can return any customized value.
