### ISSUE TITLE
How to listen event on redraw?

### ISSUE THREAD

**Issue by zantdev** [AnyChart/AnyChart#36]
I need to listen event after certain point is added to the chart, not fully chart drawn, how to implement that?

**Comment by Shestac92** [comment]
@zantdev 
Could you specify which chart type do you use for this purpose?
Basically, chart dispatches redraw event every time a new point is added to the chart. You can listen to this event type, but scrolling, for example, dispatches this event too. 
Please, check the following sample for details, click 'append point' and check the browser console - https://playground.anychart.com/yQu8DU9W
