### ISSUE TITLE
Как переместить лэйбел цены перекрестия вправо?

### ISSUE THREAD

**Issue by helloris25** [AnyChart/AnyChart#38]
![image](https://user-images.githubusercontent.com/3649203/37981541-98bf8f56-31f6-11e8-87f4-0ede0b41c88b.png)

**Comment by Shestac92** [comment]
@helloris25 
Лейбл может находится только на оси, это значит, что вы можете перенести Y-ось вправо:
https://playground.anychart.com/sFHgE6EK
или создать дополнительную ось справа и перенести лейбл на нее:
https://playground.anychart.com/a6UhQBI1

The y-label can be placed only on the axis. You can place the Y-axis on the right side of plot or create an additional Y-axis on the right side of the plot and set the Y-label on this axis.
