### ISSUE TITLE
How to make borders for the chart? Можно ли сделать такую рамку для графика?

### ISSUE THREAD

**Issue by helloris25** [AnyChart/AnyChart#39]
![image](https://user-images.githubusercontent.com/3649203/38022473-42ea3fbc-3288-11e8-9501-96c70ddbdae0.png)

**Comment by Shestac92** [comment]
@helloris25 
With the latest version of AnyChart 8.2.0 you can achieve that like this - https://playground.anychart.com/kvQMWEwm
In future updates, we plan to improve it - make plot borders just with a single method/ line of code.
I've linked your request so I will notify you when this feature becomes available.

**Comment by Shestac92** [comment]
@helloris25 
we glad to notify you that the requested feature is available with the 8.3.0 version update. Please, update your AnyChart binaries to get the feature. You can download all required binaries using our CDN - https://www.anychart.com/download/cdn/?v=8.3.0

Now data plot background is available - https://docs.anychart.com/Appearance_Settings/Background#data_area
