### ISSUE TITLE
Set filename per chart

### ISSUE THREAD

**Issue by nblackburn** [AnyChart/AnyChart#4]
An option to set the filename for the chart instance would be handy instead of it being applied to everything which in many cases is not ideal.

**Comment by loki20beta** [comment]
@nblackburn do you use context menu save as? there is a way to set a custom name when you launch a save method https://docs.anychart.com/7.13.0/Common_Settings/Exports, and there is a way to override context menu, I will try to prepare a sample that does everything for a single chart.

**Comment by nblackburn** [comment]
Yes, the context menu is in use at the moment.

**Comment by RomanLubushkin** [comment]
Internal ticket TS-178

**Comment by maresha** [comment]
@nblackburn this feature will be included in the 8.0.0 version (ETA: Sep 2017) too. Please be assured we'll keep you updated on the progress.

**Comment by loki20beta** [comment]
@nblackburn  on version 8 you can do that [Export Filename - Set for chart](https://docs.anychart.com/Common_Settings/Exports#file_name)

here is a sample: [Save as filename for a chart](https://jsfiddle.net/a4ze8bo2/)
