### ISSUE TITLE
How to disable the rounding of corners in crosshair label?

### ISSUE THREAD

**Issue by helloris25** [AnyChart/AnyChart#40]
![image](https://user-images.githubusercontent.com/3649203/38084186-8ce566b0-3354-11e8-8c7d-feb7ceb722ed.png)

Thank you in advance

**Comment by Shestac92** [comment]
@helloris25 
You can achieve that using the [cornerType() method](https://api.anychart.com/anychart.core.ui.Background#cornerType).
For details, please, check [this sample](https://playground.anychart.com/DDDvvqY2).
