### ISSUE TITLE
KDJJ calculation is incorrect

### ISSUE THREAD

**Issue by akayrb** [AnyChart/AnyChart#43]
In the graphic, the KDJJ shows a +, this is incorrect and should be a -.

Edit: In fact, the whole of KDJ is misleading. There's no mention of RSV, and that KDJK is a 3 point moving average of it, thus meaning the calculations KDJD and KDJJ will be incorrect.

**Comment by Shestac92** [comment]
@akayrb 
Can you provide us with an article or a reference to the source of this information?
The %K is the current market rate for the currency pair. The %D is 3-period moving average of %K. And the %J represents the divergence of the %D value from the %K.
Please, check the math of KDJ indicator which AnyChart implements - https://docs.anychart.com/Stock_Charts/Technical_Indicators/Mathematical_Description#kdj
The full description you can find here - https://docs.anychart.com/Stock_Charts/Technical_Indicators/KDJ
