### ISSUE TITLE
Filter on drawing selection box

### ISSUE THREAD

**Issue by mateusvbf** [AnyChart/AnyChart#44]
I need to filter data according to selection range on rectangle drawing, like on this graphic: 

![screenshot](https://user-images.githubusercontent.com/31422981/41473648-4c2e6e72-7090-11e8-81e2-7ce93fcfeb4a.png)

It would be a functionality similar to range selection, but not restricted to stock chart (at least enabled in column chart)

Is that already an existing feature or possibly in future updates? Couldn't find anything related on documentation

**Comment by Shestac92** [comment]
@mateusvbf 
The same functionality is available for basic charts like Column Chart. Please, check [this sample](https://playground.anychart.com/fDMr0WAb). In this sample, you choose in the context menu 'start selection marquee' and choose required points with the drawing rectangle. To reset the selection and show all points choose 'reset selection' in the context menu.

**Comment by mateusvbf** [comment]
@Shestac92 thanks for replying. Didnt even know there was a context menu in Anychart.
