### ISSUE TITLE
Loading JSON File error

### ISSUE THREAD

**Issue by marisolvegamx** [AnyChart/AnyChart#45]
i'm starting trying anyChart Demo version , I'd like to use the load jsonfile mode and i have followed the steps in the documentation https://docs.anychart.com/Working_with_Data/Data_Adapter/Loading_JSON_File but getting this error:
anychart-data-adapter.min.js:14 Uncaught TypeError: $.JQ is not a function
    at Object.loadXmlFile (anychart-data-adapter.min.js:14)
    at pruebagrafica.php:41
(anonymous) @ anychart-data-adapter.min.js:14
Could you please help me to resolve this?
do  I  missing something? 
this is my html code:
```
<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
          <script src="../anychart8.2.1/js/anychart-base.min.js" type="text/javascript"></script>
          <script src="../anychart8.2.1/js/anychart-data-adapter.min.js"></script>
          <script type="text/javascript">

anychart.data.loadJsonFile("https://cdn.anychart.com/charts-data/data_json.json", function (data) {
	// create a chart and set loaded data
    chart = anychart.bar(data);

    chart.title("Load JSON data and create a chart");
    chart.container("container");
    chart.draw();
});

 </script>

    </head>

<body>
       <div id="container" style="width: 500px; height: 400px;"></div>
</body>
</html>

```

 Thanks in advance
Marisol

**Comment by Shestac92** [comment]
@marisolvegamx
Your javascript is absolutely ok, but you have missed `anychart-exports.min.js` which is required this feature.
So, you should include the following list of binaries in exact order:
```
<script src="../anychart8.2.1/js/anychart-base.min.js" type="text/javascript"></script>
<script src="../anychart8.2.1/js/anychart-exports.min.js"></script>
<script src="../anychart8.2.1/js/anychart-data-adapter.min.js"></script>
```

**Comment by marisolvegamx** [comment]
@Shestac92 
Thats works perfectly, thanks so much. Only I have a suggest, you shuld put that include in the documentation because I haven't seen that line anywhere
