### ISSUE TITLE
Date.UTC($YR, $MO, $DY) is ahead by 1 month in Hover Over & Axis

### ISSUE THREAD

**Issue by swizzley** [AnyChart/AnyChart#46]
https://playground.anychart.com/docs/8.2.1/samples/BCT_Japanese-Candlestick_Chart_01

```
 var data = [
      [Date.UTC(2007, 07, 23), 23.55, 23.88, 23.38, 23.62],
      [Date.UTC(2007, 07, 24), 22.65, 23.7, 22.65, 23.36],
      [Date.UTC(2007, 07, 25), 22.75, 23.7, 22.69, 23.44],
      [Date.UTC(2007, 07, 26), 23.2, 23.39, 22.87, 22.92],
      [Date.UTC(2007, 07, 27), 23.98, 24.49, 23.47, 23.49],
      [Date.UTC(2007, 07, 30), 23.55, 23.88, 23.38, 23.62],
      [Date.UTC(2007, 07, 31), 23.88, 23.93, 23.24, 23.25],
      [Date.UTC(2007, 08, 01), 23.17, 23.4, 22.85, 23.25],
      [Date.UTC(2007, 08, 02), 22.65, 23.7, 22.65, 23.36],
      [Date.UTC(2007, 08, 03), 23.2, 23.39, 22.87, 22.92],
      [Date.UTC(2007, 08, 06), 23.03, 23.15, 22.44, 22.97],
      [Date.UTC(2007, 08, 07), 22.75, 23.7, 22.69, 23.44]
    ];
```

For whatever reason the chart is drawing 1 month ahead. As you can see from your own example/sample, hover over the first value and you can see it says Aug 23, not July 23, this is true for any data sample.

**Comment by Shestac92** [comment]
@swizzley 
There's no mistake. Date.UTC(2007, 07, 23) - is Aug 23. 
Expected values for a month in Date.UTC are 0-11. It's zero-based. So, 00 - is January, 07 - is August.
You can learn more about UTC() method [here](https://www.w3schools.com/jsref/jsref_utc.asp).
