### ISSUE TITLE
cannot create line gauge chart

### ISSUE THREAD

**Issue by sariyadilak** [AnyChart/AnyChart#47]
There is an error when i try to create line gauge chart

Uncaught TypeError: a.split is not a function
    at Object.$.H (anychart-base.min.js:18)
    at anychart-linear-gauge.min.js:14
    at anychart-linear-gauge.min.js:43
    at anychart-linear-gauge.min.js:10
    at anychart-linear-gauge.min.js:10

**Comment by Shestac92** [comment]
@sariyadilak
Please, check [this sample](https://playground.anychart.com/3zMDTa9M) of a linear gauge. Try this code in your application, also make sure that you have included all required modules (click 'settings' tab at top of playground page to view all included scripts).
