### ISSUE TITLE
Error on getting type information for stroke on EMA properties

### ISSUE THREAD

**Issue by Krishna-teja** [AnyChart/AnyChart#48]
![image](https://user-images.githubusercontent.com/6452602/42729823-1d1e8ff0-87aa-11e8-8b55-878a0d399b0f.png)

Error Msg: 
[ts]
Property 'stroke' does not exist on type 'Base | Base'.

I am using anychart with typescript and found this issue. Could you please let me know how I could solve this?

Thanks!

**Comment by Shestac92** [comment]
@Krishna-teja 
The 8th version of AnyChart brought series states. You should use them to adjust series appearance. Like this:
```
const mea30 = k.ema(mapping, 30).series();
ema30.normal().stroke('#bf360c');    //adjust stroke setting sfor normal series state
```

You can learn more about series states in [this article](https://docs.anychart.com/Common_Settings/Interactivity/States).
