### ISSUE TITLE
Error Syncing Gradle

### ISSUE THREAD

**Issue by kuyajohn** [AnyChart/AnyChart#49]
Failed to resolve: com.github.AnyChart:AnyChart-Android:0.3.0

Below is a copy of the module build.gradle file

apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    defaultConfig {
        applicationId "com.calculators.charts"
        minSdkVersion 17
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.github.AnyChart:AnyChart-Android:0.3.0'
}

**Comment by Shestac92** [comment]
@kuyajohn 
We have fixed this problem. Version 0.3.0 is correct one, please use it.

**Comment by empaguiaOA** [comment]
I am using this according to your github:

implementation 'com.github.AnyChart:AnyChart-Android:1.0.2'
then Failed to resolve: com.github.AnyChart:AnyChart-Android:1.0.2

and you answered: Version 0.3.0?
and Failed to resolve also?

**Comment by RajaParikshit** [comment]
Make sure you have add this in your project gradle file 

 maven {
            url 'https://jitpack.io'
        }

**Comment by empaguiaOA** [comment]
already fixed yesterday, anyway thanks

**Comment by Aelafseged** [comment]
my android studio is 2.3.3
i did ` compile  'com.github.AnyChart:AnyChart-Android:0.3.0'`
and  still error!!!!

**Comment by Shestac92** [comment]
@Aelafseged 
@ashivakarthik 
There's no need in compiling the repo. All you need is to add the repository to the project build.gradle and add the dependency to the module build.gradle.
For details, check the [Getting Started article](https://github.com/AnyChart/AnyChart-Android/wiki/Getting-started).

**Comment by Aelafseged** [comment]
@Shestac92 
do i have to use android studio 3.4?
i have 2.3.3 it compile correctly with 26.0.2  and anychart version 0.0.1 BUT!!!!
I can't import import com.anychart.anychart.common.dataentry.DataEntry; and other classes
i'm only getting half of the classes

**Comment by Shestac92** [comment]
@Aelafseged 
We always recommend using the latest version of the iOS library and IDEA to avoid any compatibility problems or bugs. 
Unfortunately, we didn't test the library on the 2.3.3 Studio version.

**Comment by sachikan** [comment]
Any Chart is not recognizing in the Android Latest Versions

**Comment by EliReid** [comment]
Seems to work if you also add _maven { url 'https://jitpack.io' }_ in the _settings.graddle_ file as below:

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}

**Comment by soulaymen007** [comment]
enable the jetifier in gradle.propertires :

android.enableJetifier=true
