### ISSUE TITLE
Setting to disable sharing functionality

### ISSUE THREAD

**Issue by nblackburn** [AnyChart/AnyChart#5]
Add an option to disable sharing as in many corporate environments you don't want data being shared as it presents a risk to the privacy and security of that data.

**Comment by loki20beta** [comment]
Do you mean to remove menu items from the context? Or make it impossible to call a method?

**Comment by nblackburn** [comment]
Remove the items from the context menu.

**Comment by loki20beta** [comment]
@nblackburn we are sorry for the delay with reply. As of the current 7.14.0 version, the easiest way to remove sharing options from the context menu is to do the following: https://jsfiddle.net/8pmtcqet/

**Comment by RomanLubushkin** [comment]
Internal ticket TS-179

**Comment by maresha** [comment]
@nblackburn  glad to inform you that we are going to implement the Disabling Sharing feature in the 8.0.0 version (ETA: Sep 2017). Please be assured we'll keep you updated on the progress.

**Comment by loki20beta** [comment]
v8 is released
