### ISSUE TITLE
Cannot create Circular Gauge chart in Angular 6

### ISSUE THREAD

**Issue by Sagato** [AnyChart/AnyChart#50]
Hi, 

with different charts from anychart, anything is working properly, but
when I try to use the circular Gauge chart, it doesnt show me anything.
Even the component holding the chart just shows me the div element of the chart, 
but without any chart data or drawing.

I used several examples from the anychart gallery and the quick start guide:
[(https://docs.anychart.com/Gauges/Quick_Start)]

I installed anychart 8.3 via npm install. Any other chart than CircularGauge is working.
I dont see what the difference between the gauge chart and the other charts is.

Best regards,

Sagat

**Comment by Shestac92** [comment]
@Sagato 
The circular gauge due to its features has API which is slightly different from others, but you still can create circular gauge in an Angular app. Below you can find a sample of circular gauge config and its screenshot.

```typescript
    chart: anychart.charts.CircularGauge = null;

    ngOnInit() {
        this.chart = anychart.gauges.circular();
        this.chart.data([65]);
        this.chart.title()
            .enabled(true)
            .text('YTD')
            .fontColor('#fff')
            .fontSize(10);
        this.chart.background().fill(null);
        this.chart.background().stroke(null);
        this.chart.fill(null)
            .stroke(null)
            .padding(0)
            .startAngle(270)
            .sweepAngle(180);
        const axis = this.chart.axis()
            .radius(95)
            .width(0);
        axis.scale()
            .minimum(50)
            .maximum(100)
            .ticks({interval: 10});
        this.chart.tooltip().title().fontSize(9);
        this.chart.tooltip().fontSize(9).format('Value: {%Value}');
        axis.labels()
            .fontSize('0')
            .padding(10)
            .position('outside')
            .fontColor('#fff');
        this.chart.needle()
            .startRadius('5%')
            .endRadius('85%')
            .middleRadius(0)
            .startWidth('0.6%')
            .endWidth('0.4%')
            .fill('blue')
            .stroke('white');
        this.chart.label()
            .text('<strong><span style="color: white; font-size:16px"></span></strong>')
            .useHtml(true);
        this.chart.label()
            .hAlign('center')
            .anchor('center-top')
            .padding(-20, -20)
            .offsetY(0)
            .offsetX(0)
            .zIndex(1)
            .background({fill: null, stroke: null});
        this.chart.cap()
            .radius('3%')
            .enabled(true);
        this.chart.bar(0)
            .axisIndex(1)
            .position('inside')
            .dataIndex(0)
            .width(3)
            .radius(60)
            .zIndex(10);
        this.chart.cap()
            .radius('3%')
            .fill('white')
            .stroke('white');
        this.chart.range(1, {
            from: 50,
            to: 80,
            fill: {keys: ['#ff0000', '#FF4500']},
            position: 'inside',
            radius: 100,
            stroke: null,
            endSize: '30%',
            startSize: '30%',
            zIndex: 3
        });
        this.chart.range(2, {
            from: 80,
            to: 95,
            fill: {keys: ['#FFA500', '#FFAE42', '#FFFF00']},
            position: 'inside',
            radius: 100,
            stroke: null,
            endSize: '30%',
            startSize: '30%',
            zIndex: 3
        });
        this.chart.range(3, {
            from: 95,
            to: 100,
            fill: {keys: ['#ADFF2F', '#008000']},
            position: 'inside',
            radius: 100,
            stroke: null,
            endSize: '30%',
            startSize: '30%',
            zIndex: 3
        });
    }

    ngAfterViewInit() {
        this.chart.container(this.container.nativeElement);
        this.chart.draw();
    }
```
![circulargauge](https://user-images.githubusercontent.com/24609062/44440655-a77a8900-a5fb-11e8-971a-8151e24cf148.png)

**Comment by Sagato** [comment]
Hmmm, I just did exactly what you have done. I tried your code as well, that doesnt seem to work.
I am using the stock chart in another component. The stock chart works perfectly fine.

Best regards

**Comment by Shestac92** [comment]
@Sagato 
Do you get any errors or exceptions in log? If so, can you share it?

**Comment by Sagato** [comment]
@Shestac92 
Hey mate, 
no that is suprising me. I dont get any errors. Are there any special dependencies? Anything else that is needed that I dont get with npm install --save anychart?
Can I only use 2 Charts with the trial version? Or as many as I want to? At the moment this is only development anyway. Best regards

**Comment by Shestac92** [comment]
@Sagato 
No, index.d.ts and required CSS styles are enough to create gauge chart. Trials are fully functional and don't have any limitations. 
Please, make sure that your component is placed in a correct container (root). 
If you want I can prepare a demo app with a circular gauge for you. You can use it as a template for yours.

**Comment by Sagato** [comment]
This would be very kind of you. 

> Please,

 make sure that your component is placed in a correct container (root).

What do you mean by that?
I am always writing a seperate component and use it whereever I need to in my layout.

Best regards,

Sagat

**Comment by Shestac92** [comment]
@Sagato 
[Here is a demo application](cdn.anychart.com/ts/circularDemo.zip) based on Angular 5. There are two components: a circular gauge and a Gantt chart. 

1. Download the demo
2. execute `npm install`
3. to launch it execute 'npm run start'
4. open the browser on 'localhost:4200'
5. the `first` component is a circular gauge, and the `second` one is a Gantt chart

**Comment by Sagato** [comment]
Hi Mate,

I dont really know why its working now, but your component rescued me 🗡 
Thanks a lot.

You can close this issue if u want to.

Best regards,

Sagat
