### ISSUE TITLE
Radar Area Chart

### ISSUE THREAD

**Issue by jpabanil** [AnyChart/AnyChart#51]
Hi,

I would like to ask if how can I implement this in Android https://www.anychart.com/products/anychart/gallery/Radar_Charts_(Spiderweb)/Stacked_Area_Radar_Chart.php?

Any help pls

**Comment by Shestac92** [comment]
@jpabanil 
You can build this chart in the Android app. Please, check [this gist](https://gist.github.com/ArsenyMalkov/bd593c13e7369f46824d8cff6e17ad1d) for the chart code.
