### ISSUE TITLE
TypeScript: wrong type for chart.print()

### ISSUE THREAD

**Issue by KEIII** [AnyChart/AnyChart#53]
`anychart.charts.Cartesian.print` requires `paperSize` of `anychart.graphics.vector.PaperSize`
but [doc](https://docs.anychart.com/Common_Settings/Printing#parameters) says it must be a string.

Example:
```typescript
chart.print('A4', true); // error TS2345: Argument of type '"A4"' is not assignable to parameter of type 'PaperSize | undefined'.
```

It seems PaperSize should be
```typescript
enum PaperSize {
  A0 = 'A0',
  A1 = 'A1',
  // ...
}
```

**Comment by Shestac92** [comment]
@KEIII 
The latest version of index.d.ts and AnyChart binaries (8.3.0) supports `chart.print('A4', true);` in TypeScript. Please, update your binaries up to the latest version and try to compile your project. it should work properly.

**Comment by KEIII** [comment]
I'm on 8.3.0.
TS version 2.9.2 with config
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "strict": true,
    "strictPropertyInitialization": false,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}
```

**Comment by Shestac92** [comment]
@KEIII 
It seems there is a difference in index.d.ts between the latest version and version you are using.
Please, can you share with us the `index.d.ts` file to identify the version?

**Comment by Shestac92** [comment]
@KEIII 
Yes, this is the latest version of index.d.ts and it should work properly.
Please, can you share with us the configuration? We'd like to reproduce the issue using your chart config.
