### ISSUE TITLE
yAxes does not bind scale

### ISSUE THREAD

**Issue by adomas187** [AnyChart/AnyChart#54]
Hello,
It seems something is broken with yAxes. In this page:
https://docs.anychart.com/Working_with_Data/Data_From_JSON#samples

Second from the end Sample is broken, here is a link to samples AnyChart Playground:
https://playground.anychart.com/docs/8.3.0/samples/WD_Data_from_JSON_10

I have similar code on my end, and I have same issue. Extra Y axis sets Title properly, but scale itself is not binded... Any idea how to fix this? Maybe it's a bug?

**BUT** sample "Complex" here seems to be working properly: https://playground.anychart.com/docs/8.3.0/samples/WD_Data_from_JSON_12
Not sure why...

**Comment by imaximova** [comment]
Thank you for the report! We'll fix it.
I changed this sample for you, check it at https://playground.anychart.com/25tKAI9b, it should work fine now. Please pay attention to how the custom scale is set and bound to the line series.
