### ISSUE TITLE
Set palette via JSON

### ISSUE THREAD

**Issue by adomas187** [AnyChart/AnyChart#55]
Hello,
I am trying to set color palette for my chart via JSON. I have this JSON structure (some data removed):

```
{
    "chart": {
        "type": "column",
        "container": "chart-container",
        "series": [{
            "data": [],
            "name": "One"
        }, {
            "data": [],
            "name": "Two"
        }],
        "palette": "anychart.palettes.pastel",
        "title": {
            "enable": true,
            "text": "My Chart"
        }
    }
}
```
Setting "palette" gets ignored and charts are drawn in default colors...
While `chart.palette(anychart.palettes.pastel);` on Javascript works, I want it to set it via JSON. Maybe it's not yet possible? Or I do something wrong?

Any help would be greatly appreciated.

I could not find anything about setting palette via JSON data on AnyChart docs...

**Comment by Shestac92** [comment]
@adomas187 
Unfortunately, you can' set pastel via JSON. `anychart.palettes.pastel` is a reference to an array of colors. The reference gets lost when it is set via JSON. You can place the required pastel type in JSON as a meta information, but then you should handle it like this: `chart.palette(anychart.palettes.pastel);`
