### ISSUE TITLE
Unable to Use Date Time Axes feature in Android

### ISSUE THREAD

**Issue by KartikAggarwal** [AnyChart/AnyChart#56]
Unable to use Date Time Axes feature for Android in Bubble Chart

**Comment by Shestac92** [comment]
You can apply dateTime scale for the bubble chart like this:
`chart.xScale(DateTime.instantiate());`
This should help you!

**Comment by KartikAggarwal** [comment]
> You can apply dateTime scale for the bubble chart like this:
> `chart.xScale(DateTime.instantiate());`
> This should help you!

Thanks, but can you provide me with the full example of Bubble chart with Custom Date Range and Data.

**Comment by Shestac92** [comment]
@KartikAggarwal 
Yes, please, check the code below
```
AnyChartView anyChartView = findViewById(R.id.any_chart_view);

List<DataEntry> data = new ArrayList<>();
data.add(new BubbleDataEntry("2000-01-01", 1100, 1));
data.add(new BubbleDataEntry("2001-01-01", 880, 2));
data.add(new BubbleDataEntry("2002-01-01", 1100, 5));
data.add(new BubbleDataEntry("2003-01-01", 1500, 3));
data.add(new BubbleDataEntry("2004-01-01", 921, 3));
data.add(new BubbleDataEntry("2005-01-01", 1000, 2));
data.add(new BubbleDataEntry("2006-01-01", 1400, 1));

Cartesian chart = AnyChart.cartesian();

chart.bubble(data);

chart.xScale(DateTime.instantiate());

chart.title("Bubble Chart: Basic Sample");

chart.xAxis(0).title("Year");
chart.yAxis(0).title("Sales, $");

anyChartView.setChart(chart);
```

**Comment by KartikAggarwal** [comment]
> @KartikAggarwal
> Yes, please, check the code below
> 
> ```
> AnyChartView anyChartView = findViewById(R.id.any_chart_view);
> 
> List<DataEntry> data = new ArrayList<>();
> data.add(new BubbleDataEntry("2000-01-01", 1100, 1));
> data.add(new BubbleDataEntry("2001-01-01", 880, 2));
> data.add(new BubbleDataEntry("2002-01-01", 1100, 5));
> data.add(new BubbleDataEntry("2003-01-01", 1500, 3));
> data.add(new BubbleDataEntry("2004-01-01", 921, 3));
> data.add(new BubbleDataEntry("2005-01-01", 1000, 2));
> data.add(new BubbleDataEntry("2006-01-01", 1400, 1));
> 
> Cartesian chart = AnyChart.cartesian();
> 
> chart.bubble(data);
> 
> chart.xScale(DateTime.instantiate());
> 
> chart.title("Bubble Chart: Basic Sample");
> 
> chart.xAxis(0).title("Year");
> chart.yAxis(0).title("Sales, $");
> 
> anyChartView.setChart(chart);
> ```

Thanks for the solution, But i am unable to group data of to different set with 2 different Colors.

**Comment by KartikAggarwal** [comment]
@Shestac92 Any Updates ??

**Comment by ArsenyMalkov** [comment]
Could you provide us with an example of data and share your code?

**Comment by ArsenyMalkov** [comment]
Try this code:

```java
Cartesian chart = AnyChart.cartesian();
anyChartView.setBackgroundColor("#050505");
chart.background("#050505");
chart.xScale(DateTime.instantiate());

List<DataEntry> data = new ArrayList<>();
data.add(new BubbleDataEntry("2001-01-01", 1100, 1));
data.add(new BubbleDataEntry("2001-01-02", 880, 1));
data.add(new BubbleDataEntry("2001-01-03", 1100, 1));
Bubble bubble = chart.bubble(data);
bubble.name("Christopher Sanchez");
bubble.color("#31b552");

List<DataEntry> data1 = new ArrayList<>();
data1.add(new BubbleDataEntry("2001-01-10", 1500, 1));
data1.add(new BubbleDataEntry("2001-01-15", 500, 1));
Bubble bubble1 = chart.bubble(data1);
bubble1.name("Judy Evans");
bubble1.color("#efcd16");

chart.animation(true);
chart.minBubbleSize(5d)
        .maxBubbleSize(10d);

chart.xAxis(0).title().enabled(false);
chart.yAxis(0).title().enabled(false);

((DateTime) chart.xScale(DateTime.class)).ticks().interval("d", 1);

anyChartView.setChart(chart);
```

**Comment by KartikAggarwal** [comment]
@ArsenyMalkov 
Thanks, But some bubbles get distorted with X and Y axis

**Comment by ArsenyMalkov** [comment]
@KartikAggarwal 
I have updated the code above.
