### ISSUE TITLE
Unable to select a Theme in Chart Editor

### ISSUE THREAD

**Issue by lawright17** [AnyChart/AnyChart#58]
I have been unable to select a pre-set theme in the Chart Editor, particularly with Line charts. The Palette functions correctly. This is since updating to the latest version available on Qlik Branch and using Qlik Sense Desktop 12.36.1 (September).

**Comment by Shestac92** [comment]
@lawright17 
We have just checked this issue on the line chart with all AnyChart themes and it works properly. We used Qlik Sense Desktop 12.36.1 and AnyChart Qlik Extension 2.5.1 for tests.
Please, make sure that you are using AnyChart Qlik Extension 2.5.1 (which is the latest version).
