### ISSUE TITLE
Issue in radar area chart

### ISSUE THREAD

**Issue by darklight721** [AnyChart/AnyChart#6]
The 'y' labels are positioned incorrectly. That, or the area charts are drawn incorrectly. This doesn't happen in a line radar chart.

Check out this [jsfiddle](http://jsfiddle.net/tu7nmcqx/).
If you look at 'Series 3', the value in 'A' is '3', but the label on the axis it's on is '6'.

This is also existing in the [sample code](https://playground.anychart.com/docs/7.13.0/samples/BCT_RadarChart_07-jsfiddle) in your documentation for radar chart.

**Comment by darklight721** [comment]
Okay, I think I just misunderstood how area chart is supposed to be rendered.

**Comment by grasshoppergn** [comment]
Yeah, that's a stacked area chart, and the behavior seems to be correct.
