### ISSUE TITLE
Custom colors for Sankey Diagrams

### ISSUE THREAD

**Issue by adomas187** [AnyChart/AnyChart#61]
Hello,
I need to set custom color to Sankey Diagram via JSON, but I was unable to do so. `fill` (https://api.anychart.com/v8/anychart.core.ui.Background#fill) worked for Column chart, I was able to change colors for each Column. But the same method did not work on Sankey Diagram. Is it possible to change colors per value for Sankey Diagram?

If that is not possible, maybe I could ask this as a feature for future release?

**Comment by Shestac92** [comment]
@adomas187 
Unfortunately, the current version of AnyChart 8.4.2 doesn't provide individual colors for Sankey flows and nodes. Nodes as a default take colors from the theme palette. A user can set a color for all nodes, flows, and dropoffs. 
Do you want to set individual colors to flows or nodes?

**Comment by adomas187** [comment]
I would like to set individual colors for nodes. Color of flows for me is not important. What I want to do is to have one color set of nodes on the one side and another color set of nodes on the other...

Can I expect this to be available in future releases of AnyChart?

**Comment by Shestac92** [comment]
@adomas187 
Now I see clearly your requirements! Exactly for your purpose, you can use fill function. You can create a set of colors related to node names and get the color in the fill function. For details, please, check [this sample](https://playground.anychart.com/Uu4y1dZt).

**Comment by adomas187** [comment]
Oh this is great! Thank you! Would this be possible to do via JSON or no? I need it to do via JSON. But if that is not possible I will solve this somehow the other way :+1: 

Thank you very much!

**Comment by Shestac92** [comment]
@adomas187 
If you create the chart from JSON configuration, unfortunately, you can't add node coloring information to this JSON. This can't be parsed by the chart properly. 
You can load the second JSON string which includes only node coloring map, parse to the JS object and apply to the existing chart using JS code. Just like it was shown in the sample I provided.
