### ISSUE TITLE
polymer 3.0 support

### ISSUE THREAD

**Issue by punkratz312** [AnyChart/AnyChart#62]
Hello,
I was not able to find out if polymer 3.0 is supported. There is no plugin mentioned. I imported the dependency successfully but anychart.onDocumentLoad is not getting called.
Any idea?
Thanks

![image](https://user-images.githubusercontent.com/8830888/50154492-c3e8b280-02c9-11e9-891e-e6325b31ac89.png)

**Comment by Shestac92** [comment]
@punkratz312 
We never tried charts with Polymer 3.0, but if the `ready` callback function is called when the DOM is ready then there's no need in `anychart.onDocumentLoad()`. You can just create the chart, configure it and render.
Try to render the chart without using `onDocumentLoad()` and this should work.
