### ISSUE TITLE
Issues Regarding Gantt Chart

### ISSUE THREAD

**Issue by Vaish00** [AnyChart/AnyChart#63]
a) How can we Dynamically Add a task in a gantt chart using add button without refreshing it.
b) Is there any function other than anychart.onDocumentReady(function () ) for Add and Update of GanttChart

**Comment by Shestac92** [comment]
@Vaish00 
You can add new data or modify it on the fly using [functions of dataTree](https://api.anychart.com/anychart.data.Tree#addChild).
You can do modify the chart and the dataTree outside the anychart.onDocumentReady(function () ), but you should have access to the chart or dataTree variable in the current scope.
I have prepared [a sample to show how you can achieve both options](https://playground.anychart.com/kKEPPNun).

**Comment by Vaish00** [comment]
While editing gantt chart with the edit function of gantt ,It is not able capture the start date and end date in order to update the gantt chart dynamically
where will get the function to capture that data?

**Comment by Vaish00** [comment]
When a user edits a particular task. That particular task data i.e. the end
date and start date of that task should get saved.

**Comment by Vaish00** [comment]
Hi,
Even if I get the whole data of gantt chart after editing that's also fine

**Comment by Shestac92** [comment]
@Vaish00 
You can get any data field of the treeData item (start, end, progress etc). All depends on the approach of editing the item. 
Are you using mouse events? LiveEditing feature? Any custom controls to add/edit items?

**Comment by Vaish00** [comment]
Yes, i got all the fields of gantt chart. Thank you :+1: )
I am using edit function, wherein with the help of mouse the chart gets edited.
May i ask one more question???
i am using angular 5, i fetched the data from database (i.e the start data ,end date,etc) 
I will have pass the data in this function chart.data(data, 'as-table'), when i console it i get $.vr data and not VH data.. and hence the chart is got getting displayed

**Comment by Vaish00** [comment]
yes its working...... with data variable, i am almost there with the db too!
but i am struggling to get the start data and end date after editing with the help of mouse.
Is there any function which i did not discover till now

**Comment by Shestac92** [comment]
@Vaish00 
Please, can you describe in details how exactly are you editing items with the mouse? Are you using Live Edit feature?

**Comment by Vaish00** [comment]
https://playground.anychart.com/api/v8/charts/_samples/anychart.charts.Gantt.edit_get
 i am using this!!!

**Comment by Shestac92** [comment]
@Vaish00 
This is possible!
If you want to get only `start`/`end` values of the item you can use the approach shown in [this sample](https://playground.anychart.com/0PFGn3yj).
If you want to recognize the type of the event and get all available information, you can use [this modified sample](https://playground.anychart.com/xfMW9EXj).
In both samples check the browser console.

**Comment by Vaish00** [comment]
thank you ;) @Shestac92
This helped me a lot.
