### ISSUE TITLE
Activity not showing any graph from AnyChart library version 1.0.6

### ISSUE THREAD

**Issue by amnaa09** [AnyChart/AnyChart#64]
I am trying to show funnel and pie chart but it shows blank space.
XML:
 <LinearLayout
                android:layout_width="match_parent"
                android:id="@+id/funnel1_layout"
                android:layout_height="600dp"
                android:orientation="vertical">

                <com.anychart.AnyChartView
                    android:id="@+id/funnelchart1"
                    android:layout_width="match_parent"
                    android:layout_height="550dp"
                    android:layout_below="@+id/dashboard_buttons6"
                    android:layout_alignParentStart="true"
                    android:layout_alignParentBottom="true"
                    android:layout_marginStart="0dp"
                    android:layout_marginTop="-6dp"
                    android:layout_marginBottom="8dp"
                    />
          
            </LinearLayout>

Java file:

                    final AnyChartView funnelchartPayable1=  findViewById(R.id.funnelchart1);
                    final Funnel funnel1 = AnyChart.funnel();
                    List<DataEntry> dataf = new ArrayList<>();
                    dataf.add(new ValueDataEntry("Website Visits", 528756));
                    dataf.add(new ValueDataEntry("Downloads", 164052));
                    dataf.add(new ValueDataEntry("Valid Contacts", 112167));
                    dataf.add(new ValueDataEntry("Interested to Buy", 79128));
                    dataf.add(new ValueDataEntry("Purchased", 79128));

                    funnel1.data(dataf);
                    funnel1.margin(new String[]{"10", "20%", "10", "20%"});
                 //   funnel1.baseWidth("70%")
                   //         .neckWidth("17%");

                    funnel1.labels()
                            .position("outsideleft")
                            .format("{%X} - {%Value}");
                    funnel1.animation(true, 800);

                    funnelchartPayable1.setChart(funnel1);

**Comment by Shestac92** [comment]
@amnaa09 
The code you provided is absolutely ok and valid. We tested it using 1.0.6 version and it works well.
We think that something wrong with the layout that's why the view is hidden, we need the full layout's XML to review it.
Probably, something is wrong with the rest of the activity code. We can review your activity code if it's possible.

**Comment by maheshts** [comment]
Hi,
First time the funnel chart working if i am again changeing the data or reset the data to the chart  thst is not dispalying
