### ISSUE TITLE
How to add extra title at bottom of Waterfall Chart?

### ISSUE THREAD

**Issue by sujatakhatal53** [AnyChart/AnyChart#65]
I want to add an extra title at bottom of Waterfall Chart. How to do this? I have looked into documentation , I found only this:
var title = chart.title();
title.text("Sales Performance");

**Comment by loki20beta** [comment]
@sujatakhatal53 you can use chart labels to create extra titles https://docs.anychart.com/Common_Settings/Chart_Labels
like in this sample https://playground.anychart.com/tyVGvM3E
you may be also interested in this info https://stackoverflow.com/questions/46793609/how-to-add-subtitle-and-footer-on-anychart-8

**Comment by sujatakhatal53** [comment]
@loki20beta  Thanks a lot.
