### ISSUE TITLE
How to change color of columns in waterfall chart?

### ISSUE THREAD

**Issue by sujatakhatal53** [AnyChart/AnyChart#66]
II have created waterfall chart. But I dont want default colors of waterfall chart that is blue & orange.

I want to give different colors for columns. How to do this?

**Comment by loki20beta** [comment]
@sujatakhatal53  please refer to https://docs.anychart.com/Basic_Charts/Waterfall_Chart#appearance
there are also custom colored samples at https://www.anychart.com/products/anychart/gallery/Waterfall_Charts/

**Comment by sujatakhatal53** [comment]
@loki20beta Thank you so much. It works.
