### ISSUE TITLE
AnyMaps use

### ISSUE THREAD

**Issue by Olegka35** [AnyChart/AnyChart#68]
Hello!
I have started to study AnyMap and faced the problem

Everywhere in guides (e.g. https://docs.anychart.com/Maps/Quick_Start) there are use for: map.geoData(anychart.maps.australia);

But anychart.maps is not defined when I use anychart npm package. 

How can I solve this issue?

**Comment by Shestac92** [comment]
The current version of AnyChart NPM package includes all maps in the `/dist/geodata` folder. You should attach the required map JS file and after that, you can call `map.geoData(anychart.maps.australia);`
In the future updates, we are going to improve this mechanism and you will be able to include maps using `require()`.
