### ISSUE TITLE
how to add color to each stack in stacked polar chart?

### ISSUE THREAD

**Issue by Rafah-Mehfooz** [AnyChart/AnyChart#69]
how to add color to each stack in stacked polar chart?

I want to achieve this https://imgur.com/a/ZQuSaXN

**Comment by Shestac92** [comment]
Using the polar chart you can set a color for every series, but not for every stack.
So, to achieve the required appearance you should apply colors for every point.
For details, please check [this sample](https://playground.anychart.com/Ab0M7IVW/0).
