### ISSUE TITLE
Refresh Data on Chart

### ISSUE THREAD

**Issue by johnybi** [AnyChart/AnyChart#70]
Hello, I am doing an web application using  angular, 
The propose is to see the charts depending on the information selected by the user.
The issue is when the user select for the second time the chart doesn't change, instead of doing that it creates other similar copies next to the old charts.
I am new at anychart and i hope you can help me with this issue.

Thanks,
João.

**Comment by Shestac92** [comment]
@johnybi 
The common use approach is to update only the chart input data. There's no need in recreating the chart. But the exact implementation depends on the chart type. Please, can you specify what chart type you are using?

**Comment by johnybi** [comment]
Sorry by the delay answer. 
I am using 2 different types of charts: pie chart and column chart.

**Comment by Shestac92** [comment]
@johnybi 
In this case, you can update only the pie chart data (it's single series chart) and column series.
For details, check the [sample of a pie chart](https://playground.anychart.com/3xXDNgps) and a [sample of column chart](https://playground.anychart.com/xWunNTNH) which get updates.
Absolutely the same approach you can use for your charts in Angular.

**Comment by johnybi** [comment]
Thank you for the availability. 
I' ll see the links and try a similar approach.

**Comment by LohithCsk** [comment]
@Shestac92 could you please provide an example for SUNBURST chart, I am passing data dynamically to the sunburst chart component, i have a added a dropdown to  select month, upon selection new data from backend will be sent and that part is fine. but chart is not getting refreshed. Please help.
