### ISSUE TITLE
Scatter Plot series drawing bug

### ISSUE THREAD

**Issue by adojck** [AnyChart/AnyChart#71]
Hello,
I have encountered this strange issue:
![scatter-plot-last-series](https://user-images.githubusercontent.com/4030692/52566507-38435c00-2e0a-11e9-9bef-1dd5c09cb6bd.png)

As you can see in the screenshot, series named "**AVG**" has somehow it's part of data displayed like a second chart, and not inside the "main chart".

Xscale type is set to `dateTime` and every series has `x` defined in this style: `YYYY-MM-DD`

What I noticed, that first five series does not have data with `x = YYYY-02-01`, but last series AVG has these, and they gets pushed out from the chart.

Here is another screenshot, when AVG series is put in front of other series:
![image](https://user-images.githubusercontent.com/4030692/52566834-10a0c380-2e0b-11e9-968a-f706ffae0b8c.png)

Here I can see AVG series included as small blue circles in places where it should be from beginning.

I would expect the result to be like in the second screenshot, despite the order of series. As I have encountered this, I suspect it can be a bug of AnyChart.

**Comment by Shestac92** [comment]
@adojck 
Please, can you provide a configuration code of this chart and data for AVG series and any other one? This will help us to reproduce the issue and suggest a solution.

**Comment by adojck** [comment]
@Shestac92 
Here is complete JSON configuration for the chart:
https://gist.github.com/adojck/be7a24b67d9b7e22060a9f82f799b9bf

Note: this data was adjusted (fixed), so only one column stands out from the chart.

![scatter-plot-out-of-chart](https://user-images.githubusercontent.com/4030692/52627404-895c5a00-2eb5-11e9-80ad-c004a698d6b7.png)

Now the values which has `x = 2007-04-01` are out of the chart.

It seems when first series of data are missing some specific `x` values, `dateTime` Xscale does not adjust when adding second series to the chart and in the end result, I have data out of chart.

I do some minor adjustments to the chart with Javascript and I don't think it has any impact on the bug. But here is the code:

```
                        if (result.chart.type == "scatter") {
                            $('#chart-' + chartId).addClass("scatter");
                            chart.legend().hoverCursor("default");
                            chart.legend().listen("legendItemClick", function(e) {
                                e.preventDefault();
                                e.stopPropagation();
                              });
                            chart.legend().listen("legendItemMouseOver", function(e) {
                                e.preventDefault();
                              });
                            var labels = chart.xAxis().labels();
                            labels.hAlign("center");
                            labels.width(100);
                            labels.format(function(value){
                              var date = new Date(value["tickValue"]);
                              var options = {
                                year: "numeric"
                              };
                              return date.toLocaleDateString("en-US", options);
                            });
                        }
```
**Another thing:** since I posted for you complete JSON configuration for the chart, as you can see I have a lot of data in it. It's around **23 000** points to be drawn on the chart. Maybe you could suggest me any way of improving performance for this large dataset?

**Comment by Shestac92** [comment]
@adojck 
It was not a bug, it's was a wrong xScale JSON configuration. In your case, the xScale was a linear, not dateTime. Also, there were many unnecessary settings you can drop. Please, replace your chart settings at the end of JSON with the following settings (especially pay attention to scales, xAxes, yAxes, xScale and yScale settings):
```
        "title": {
            "enable": true,
            "text": "Scatter Plot"
        },
        "legend": {
            "enabled": true,
            "position": "top",
            "itemsLayout": "horizontal"
        },
        "scales": [
            [
                {},
                {}
            ]
        ],
        "yAxes": [
            {
                "title": "Offer",
                "scale": 1
            }
        ],
        "xAxes": [
            {
                "scale": 0
            }
        ],
        "xScale": {
            "type": "date-time"
        },
        "yScale": {
            "type": "linear",
            "minimum": 0,
            "maximum": 12000
        }
```

Unfortunately, this chart type can't provide better performance for the such big dataSet. For such datasets we recommend using Stock charts. Stock chart support data grouping feature which dramatically increase performance. But your date includes several yValues for one xValue for every series. This is not possible with the stock chart.
We can recommend only preprocessing the data before creating the chart if your use-case allows it.

**Comment by adojck** [comment]
@Shestac92 thanks for the help. Everything seems to work fine now.
