### ISSUE TITLE
Cannot create Solid Gauge chart in Angular 6

### ISSUE THREAD

**Issue by willbuildapps** [AnyChart/AnyChart#72]
Hi,

When I try to use the circular Solid Gauge chart, it doesn't show me anything besides the error "Description: Feature "Circular gauge" is not supported in this module. See modules list at https://docs.anychart.com/Quick_Start/Modules for details. "

I'm trying to use this example from the anychart gallery and the quick start guide:
[(https://playground.anychart.com/gallery/Circular_Gauges/Solid_Gauge)]

What can I do to overcome this error?

**Comment by Shestac92** [comment]
Probably, you include AnyChart binaries in the wrong way. The code doesn't have access to the required JS module.
Please, try [this Angular6 demo application](http://cdn.anychart.com/ts/angular6_demo.zip) which includes a circular gauge and a Gantt chart in one app. 
To launch the demo execute `npm install` and `npm run start`.
This demo shows how to include all required AnyChart resources to the Angular app.

**Comment by willbuildapps** [comment]
Thanks @Shestac92 I was missing the required imports on main.js
