### ISSUE TITLE
Listen Events on Stock Chart

### ISSUE THREAD

**Issue by BomboButt** [AnyChart/AnyChart#73]
Hi, there.

I added listen event after I were sure that data fed into chart correctly and show on chart **successfully**.
And here's the problem I bumped into:
I tried to add listener("pointMouseMove" type) to [AnyStock/Japanese candlestick](https://docs.anychart.com/Stock_Charts/Series/Japanese_Candlestick) chart, but it didn't trigger the listener when my mouse hovered around series of candlestick.

This is the relevant variables I announce:
```
var chart = anychart.stock();
var plot = chart.plot(0);
var dataTable = anychart.data.table();
var mapping = dataTable.mapAs({ 'open': 1, 'high': 2, 'low': 3, 'close': 4});

var series = plot.candlestick(mapping);
```

And it didn't have any response from listener when I add:
```
chart.listen("pointMouseMove", function(e) {
        alert(e.point.getIndex());
})
```
It didn't react even when I change `chart` variable to either `series` or `plot` variables, which will work right when I apply listener onto [AnyChart/Basic Charts/Japanese candlestick](https://docs.anychart.com/Basic_Charts/Japanese_Candlestick_Chart).

So, I'm wondering **which part should I revise** or **there's no such feature of listen event serves for AnyStock**?

**Comment by Shestac92** [comment]
@BomboButt 
Unfortunately, the Stock chart doesn't support point related events. The stock chart allows rendering thousands of points, also it provides grouping feature (several raw points are joined into one combined point for proper granularity). In this case, point related events are not available. Please, can you describe what interactivity do you want to implement using point listener? Probably, we can suggest another solution for this.

**Comment by BomboButt** [comment]
@Shestac92 
Thanks for your quick reply.
I want to get the index of series that mouse will trigger when hovering, so that I can get display message of other column under the same index.

**Comment by Shestac92** [comment]
@BomboButt 
Unfortunately, there are no methods to get the hovered series. Exactly for this purpose, the library provides powerful API for customizing the tooltip. Can the tooltip meet your requirements to achieve your goals? 

The AnyStock provides event markers! You can check [the documentation](https://docs.anychart.com/Stock_Charts/Event_Markers/Overview) and [beautiful samples of using them](https://www.anychart.com/products/anystock/gallery/Stock_Event_Markers/).

**Comment by BomboButt** [comment]
@Shestac92 
Yes, I need to retrieve the point without having a tooltip on that. So, I have the legend to retrieve the other info I need.

Thanks for your suggestion.

**Comment by 26medias** [comment]
If that still helps after so long, setup a tooltip, it gives you the x position. Save it, and on click use that last position.
Solved it for me.
@BomboButt 

```
chart.tooltip().format(function(e){
    // e.x, e.index
});
```

**Comment by real-supreme** [comment]
@Shestac92 Hello

The _pointClick_ event seems to be working in anychart's playground for stockChart. The below code worked there:
```
anychart.onDocumentReady(function () {
    // Creates Candlestick chart.
    var chart = anychart.candlestick([
        [Date.UTC(2018, 10, 1), 511.53, 514.98, 505.79, 506.40],
        [Date.UTC(2018, 10, 10), 507.84, 513.30, 507.23, 512.88],
        [Date.UTC(2018, 10, 20), 512.36, 515.40, 510.58, 511.40],
        [Date.UTC(2018, 10, 30), 513.10, 516.50, 511.47, 515.25],
        [Date.UTC(2018, 11, 10), 515.02, 528.00, 514.62, 525.15]
    ]);

    chart.title('Create a Candlestick chart');
    chart.xScale().minimum(Date.UTC(2018, 9, 25)).maximum(Date.UTC(2018, 11, 15));
    chart.container('container');
    chart.draw();
  chart.listen(
        'pointClick',
        function (e) {
          console.log(e, 'PointClick worked')
        },
        true,
      )
});
```

My intention with this is to open a popup with the date and many other data related to it, when the user clicks on the particular point (not anywhere on the screen)
