### ISSUE TITLE
Retrieve Data of DataTable from AnyStock

### ISSUE THREAD

**Issue by BomboButt** [AnyChart/AnyChart#74]
Hi, there.

I wonder whether it's possible to retrieve data from dataTable after mapping them to specific column if the index of data is given?

This is the variables I've declared:
```
var chart = anychart.stock();
var dataTable = anychart.data.table();
var candle_mapping = 
var plot;
var mapping = dataTable.mapAs({
        'datetime': 0,
        'open': 2,
        'high': 3,
        'low': 4,
        'close': 5,
        'value': 6,
        'average_volume': 7,        // further info I would like to add in dataTable
});

dataTable.addData(data);

var series = chart.plot(0).candlestick(mapping);
    
```

I've gone over API documentation:
[This page](https://playground.anychart.com/api/v8/data/_samples/anychart.data.View.get)(`get()`) suggests that I can retrieve **'average_volume'** once I get the index of data by:
```
candlestick_series.legendItem().format( function(e) {
        var average_volume = mapping.get(this.index, 'average_volume');
        .....(other code)
});
```
However, it seems only work for anychart rather than stock() class. Is there any alternative?

**Comment by Shestac92** [comment]
@BomboButt 
Yes, AnyStock works with data.Table and it provides specific API. You can get any value of any point by several approaches. The best practice is to get the point by its key - date. Because of the Stock chart works with dateTime related data. Is appropriate for you to get the `average_volume` value of a point by its dateTime value?

**Comment by BomboButt** [comment]
@Shestac92 
Yes, that's the API I should apply. So, which API should I refer to to call dataTable??

**Comment by Shestac92** [comment]
@BomboButt 
Great, in [this sample](https://playground.anychart.com/RDDDbUsG) you can find the best approach to achieve your goals. All the required information you will find in the code comments.

**Comment by BomboButt** [comment]
@Shestac92 
Thanks a lot!
