### ISSUE TITLE
Trying to compile source code but would not work

### ISSUE THREAD

**Issue by xigolle** [AnyChart/AnyChart#75]
Dear, 

I wanted to try and implement some feature in AnyChart ( or at least try) but when I wanted to compile I get the following errors: 
![build error](https://user-images.githubusercontent.com/4833546/53956833-03f74e80-40dd-11e9-86fb-77e265e49ef4.png)

Is there something I am doing wrong here? 

It seems the build script is looking for a folder `builds` but this one is not present and there fore cannot find the depswriter.py file it needs.

Thanks in advance for helping me out.

Kind regards,
Joey Driessen

**Comment by Shestac92** [comment]
@xigolle 
Thank you for your report!
I will review build scripts and update you as I get results.

**Comment by Shestac92** [comment]
@xigolle 
The `depswriter.py` is a part of google closure library which is a project submodule.
You should execute the following steps:
- exactly clone the repo
- `git submodule init`
- `git submodule update` - may take some time time
- `./build.py deps`
- `./build.py compile`

**Comment by xigolle** [comment]
@Shestac92 Thanks for the tips! Didn't know I needed to do these additional steps. 
I also got a problem with the `git submodule update` command because I get the following error:
![image](https://user-images.githubusercontent.com/4833546/54261693-b3fd0980-456c-11e9-8a6d-088389f4d090.png)
Maybe you know a resolution to this problem ?

**Comment by Shestac92** [comment]
@xigolle 
Please, can you specify how do you clone the repo? Are you using SSH public key or with the key via https?

**Comment by xigolle** [comment]
@Shestac92 I am using HTTPS.

**Comment by Shestac92** [comment]
@xigolle 
Ok, now I see the issue. The SSH-public key is required for cloning sub-modules. Please, apply SSH key for you GitHub and try to clone the AnyChart repo using the key.

**Comment by xigolle** [comment]
@Shestac92 Thanks I got it resolved.
Although my CLI still gave me some error when running the command `git submodule update` (Something with my public key not having access). 
But I got it fixed when I used my GUI client Gitkraken and the project now just builds fine! 

Thanks for the help and now going to see if I can create some features! :)
