### ISSUE TITLE
Unable to find zoom-in api in anyStock. 

### ISSUE THREAD

**Issue by harishekhar** [AnyChart/AnyChart#76]
How can we implement the zoom-in, zoom-out on mouse scroll? 
For example,

https://demo.chartiq.com/index.html?utm_campaign=demo%20now&utm_source=website%20header%20nav&utm_medium=charting%20library%20cta

if you see I am able to do zoom-in, zoom-out over the graph but don't know how to do the same thing using anychart. 
This is primary need of my project. 

Any kind of help would be appreciated.

**Comment by Shestac92** [comment]
@harishekhar 
You can enable this feature using the `zoomOnMouseWheel()` function.
For details, check [this sample](https://playground.anychart.com/api/core/utils/_samples/anychart.core.utils.StockInteractivity.zoomOnMouseWheel).

**Comment by harishekhar** [comment]
Wow! Thanks for the prompt response. 
Can we manipulate the same functionality on pinch-in and pinch-out?

**Comment by Shestac92** [comment]
@harishekhar 
Yes! All these options are available!
In mobile browsers swipe left/right moves the scroller, pinch-in and pinch-out provide zoom-in and zoom-out respectively.
You can place html buttons on the page and using AnyStock API provide zooming. [Here is a sample of such an approach.](https://playground.anychart.com/T7Y72ceo)

**Comment by harishekhar** [comment]
I am assuming similar functionality (pinch-in-out) can be achieved on the web browser as well

Thanks for your reply @Shestac92
