### ISSUE TITLE
Redrawing after 

### ISSUE THREAD

**Issue by tarun-uwe** [AnyChart/AnyChart#77]
I have a similar question as in #36, but a little different.
We recolor Sankey - Charts manually after it was drawn.*(Why)

We we resize our browser over a certain point, it redraws again and our colors are gone.
We could use that event listener, but we do not want to execute our script everytime that event is fired, but only if anychart had redrwan that Chart.

---
Why: We do that because we have something like "from Canada" -> "USA" -> "to Canada" as Flow in Sankey Chart and we want to have both "Canada" Rectangles the same color.

**Comment by Shestac92** [comment]
@tarun-uwe 
I think I miss something in your question. The Sankey chart supports coloring Nodes via palette or common Node color. I mean that I didn't get your idea about coloring and the problem of dropping colors.
`chartDraw` event fires every time the chart is redrawn. Unfortunately, there's no way to distinguish the reason for redraw. So, in which cases do you want to call a handler function?

**Comment by tarun-uwe** [comment]
> I think I miss something in your question.

@Shestac92 I try to clarify. 

When a chart is loaded, it gets a color assignment from Anychart.

After that we analyze the colors and texts from our left side and recolor the right side.
We serach for the same string like "from Berlin" and "to Berlin" have both Berlin in its name.

We get a nice colored chart. But if we for example make the browser window smaller, there is a point, where the chart gets redrawn and the colors are mixed up again. See the following gif.

![colochange-resize](https://user-images.githubusercontent.com/30664429/54456671-a9569600-475f-11e9-999a-508b1625e273.gif)

Is that a bit clearer? And we want to execute our coloring script again, after that redraw. But only if that color fill happend.

**Comment by Shestac92** [comment]
@tarun-uwe 
Thank you for the GIF and explanation! Now I got your idea!
I think you can avoid all these problems by using a fill callback function for coloring nodes. For details, please, [check this sample](https://playground.anychart.com/W671bPck).
Pay attention to lines 30-34. This part of the code applies individual color for 'to Canada' node and resizing doesn't affect it at all. This approach is the best practice for individual coloring using AnyChart API.

**Comment by tarun-uwe** [comment]
> @tarun-uwe
> Thank you for the GIF and explanation! Now I got your idea!
> I think you can avoid all these problems by using a fill callback function for coloring nodes. For details, please, [check this sample](https://playground.anychart.com/W671bPck).
> Pay attention to lines 30-34. This part of the code applies individual color for 'to Canada' node and resizing doesn't affect it at all. This approach is the best practice for individual coloring using AnyChart API.

Thanks for your answer, we will try it. But at first glance, it seems like a good solution.
