### ISSUE TITLE
When setting Line thickness, Line loses color

### ISSUE THREAD

**Issue by adojck** [AnyChart/AnyChart#78]
I want for Line Chart to set Line Thickness, but I want to keep auto-coloring for the lines. When I set Line Thickness via JSON, it sets color of Line to black.

Is there a way to change Line Thickness, but keep auto-coloring colors on Lines?

I was following this document:
https://docs.anychart.com/Appearance_Settings/Lines_Settings#line_thickness

**Comment by Shestac92** [comment]
@adojck 
Unfortunately, the current version of AnyChart 8.5.1 requires applying both color and thickness for the stroke.
If you want to save auto coloring you can use the following approach:
```
  series.stroke(function() {
    return {color: this.sourceColor, thickness: 5};
  });
```
`this.sourceColor` stores a default color.
You can [check a sample of using this approach (lines 18 - 20)](https://playground.anychart.com/lwf4v5qi).

**Comment by tarun-uwe** [comment]
Hi Shestac92,

we generate a Column Chart via JSON. We are not sure, if we could access the series in chart object, before we draw our chart. Is there a way?

Best regards
Uwe
