### ISSUE TITLE
Scroll bar issue on switching between components in ANYCHART

### ISSUE THREAD

**Issue by SwardCoder** [AnyChart/AnyChart#80]
the problem is with scroll bar 
my code is 

 const tscroller = this.chart.xScroller(); 
       tscroller.enabled(true);
       tscroller.allowRangeChange(true);  
       tscroller.orientation('top');
       tscroller.height(55);
       timeLineScroller.fill('green');
       timeLineScroller.selectedFill('red');

this gives me output like this as expected 

![Prob1](https://user-images.githubusercontent.com/50729228/57904785-df181800-7891-11e9-992a-946e30ea3289.png)

but when i move from component where iam using anycharts and coming back later by clicking on buttons like back button (not browser back button)
then my output is displaying as following 
making selected scroll as transparent 

![Prob2](https://user-images.githubusercontent.com/50729228/57904786-df181800-7891-11e9-8567-0806862c3d7b.png)

and it works perfectly fine if i refresh my page and displaying as above 
even i observed that both while refreshing page and clicking on back button is executing the code mentioned above 

so i request you to help me get rid of the problem i want the consistancy of scroll bar in anycharts Ghant chart to be like first image 
i tried reading all documentation part and tried several things from past 2 weeks nothing worked 
i hope you will help us with some solution to it

**Comment by Shestac92** [comment]
@Skakani83 
For example, the Angular environment requires some specific settings to avoid rendering issues sometimes. Try to add the line `anychart.graphics.useAbsoluteReferences(false);` before the chart configuration code. This should solve the issue.

**Comment by Skakani83** [comment]
@Shestac92  thank you for Quick reply that worked like charm 
and also if possible help me understand what that line does 
is there any link that helps me understand the useAbsoluteReferences method under graphics

**Comment by Shestac92** [comment]
@Skakani83 
You can check the function description in [this API section](https://api.anychart.com/anychart.graphics#updateReferences).
Switching vies or controllers in the Angular environment requires using relative paths for SVG paths elements. Usually, this is not required in plain HTML web-page, absolute paths are ok. But sometimes container wrappers or frameworks require exactly relative paths.

**Comment by Skakani83** [comment]
Thank you 👍
