### ISSUE TITLE
How to Remove Extra separator Line in Gantt Charts graph

### ISSUE THREAD

**Issue by SwardCoder** [AnyChart/AnyChart#81]
i was looking at the example playground in anychart in following URL 

https://playground.anychart.com/gallery/Gantt_Charts/Human_Resource_Chart

then suddenly i found a big line seperator between names and graph as shown in below image 

i wish to remove this line which is extra from graph 
i mean how to remove line marked in yellow in below image 
![I 1](https://user-images.githubusercontent.com/50729228/58249377-552dea80-7d7c-11e9-9d53-c2fcd3098dae.JPG)

i can see this problem exist in most of the graphs playgrounds

**Comment by Shestac92** [comment]
@Skakani83 
The chart always renders the splitter from the top edge of the chart to the bottom edge. You can avoid drawing the extra splitter line by decreasing the chart height to the required bounds or to the last row position.

For details, [check the sample of using the second approach](https://playground.anychart.com/GkNs2PEN)

**Comment by Skakani83** [comment]
Thank you this sounds good solution 
and if possible can you help me with any built in function to know the last row position? in the graph

**Comment by Shestac92** [comment]
@SwardCoder 
Unfortunately, there's no built-in method to get the last row position. You can use the workaround described in the sample above. That code calculates the chart total height. All you need is to minus one rowHeight from the totalHeight to get the start position of the last row.

**Comment by SwardCoder** [comment]
ok got it @Shestac92  thank you
