### ISSUE TITLE
Can we show Tooltip only when required 

### ISSUE THREAD

**Issue by SwardCoder** [AnyChart/AnyChart#82]
Hi i was browsing through the examples 

https://playground.anychart.com/docs/v8/samples/GANTT_Events_01

the tool tip was displaying evey where on the graph like below 

![image](https://user-images.githubusercontent.com/50729228/58472744-951e1480-8164-11e9-9772-eb19e63f1032.png)

can any one help me how to achiev showin tooltip only on blue bars 
do we have any such examples 
as of now i am using Cartesian chart

**Comment by Shestac92** [comment]
@SwardCoder 
Probably [this workaround](https://playground.anychart.com/sjwkBi5V/1) will meet your requirements.

**Comment by SwardCoder** [comment]
Wow this example looks good to me let me look into this completely 
thank you @Shestac92  you Rock

**Comment by Shestac92** [comment]
@SwardCoder 
Cartesian charts provide many possibilities to customize the behavior. For example, [a column chart](https://playground.anychart.com/docs/v8/samples/BCT_Column_Chart_01) provides the required behavior as a default. Also, you can adjust this behavior for many other Cartesian chart types. [This article](https://docs.anychart.com/Common_Settings/Interactivity/Overview#hover) describes how to adjust the chart's interactivity.
