### ISSUE TITLE
Right indentation breaks live update stock chart

### ISSUE THREAD

**Issue by pathvine** [AnyChart/AnyChart#83]
![Liveupdate stock chart](https://i.gyazo.com/54a5e4d9e882f9ea85e05100ef4ec604.png)

I have a live update stock chart with right indentation. The settings for the indentation is 
`chart.xScale().maximumGap({intervalsCount: 1000, unitType: 'minutes', unitCount: 1});`

The right indentation causes a few things happening on the chart:
- The price bars, volume bars, and indicator bars below are abnormally spaced.
- Some of the indicators shows for the preloaded data but not for the live updated data.
- The cursor information box doesn't show up for the live updated data.

Can you please advise whether these are bugs or something is wrong in my code? Thanks!

**Comment by Shestac92** [comment]
@pathvine 
The `maximumGap` feature works properly with xScale of a scatter type. You should switch the xScale to the scatter type by the following line:
```
chart.xScale('scatter');
```
This will solve the first problem and I guess the second one too. I have prepared a [sample of a similar chart ](https://playground.anychart.com/Gtb5KL8c) and indicators work well. Please, can you specify what indicators didn't work for you?
Unfortunately, the tooltip's unexpected behavior seems to be a bug. We will investigate it and fix. I will update you when the fix becomes available.
Thank you for your report!

**Comment by pathvine** [comment]
@Shestac92 Thank you for the prompt reply. 
Your suggestion fixed the first problem. However, there are spaces left by the after hours for intraday charts and weekends/holidays for the daily chart. Is there any way to remove these spaces? Please advise.

The scatter chart does not fix the second problem. The indicator I am using is the Supertrend indicator, which is the red and green lines shown on the price chart. You can probably see that the indicator stops showing at some point where the live data is loaded. I realize that this happens to indicators with "line" plot; indicators with "dot/column" plots are fine.

I will look forward to the update of the tooltip fix. Thank you!

**Comment by Shestac92** [comment]
@pathvine 
Spaces left by the after hours for intraday charts and weekends/holidays are an essential part of scatter mode. In the scatter mode every point is placed on the chart strictly according to its timestamp. It takes into account every shift, gap between points. If this is not appropriate for your chart, you can switch xScale mode back to the default type.

Unfortunately, we didn't succeed to reproduce the first problem in ordinal mode. Please, can you specify what library version you are using? Do you apply any grouping settings to the chart?

Is the Supertrend indicator is custom made indicator? Or it's just an alternative name? [Here is the list of indicators](https://docs.anychart.com/Stock_Charts/Technical_Indicators/Supported_Technical_Indicators) provided by AnyChart. Are you using one of them?

**Comment by pathvine** [comment]
@Shestac92 
Understood. I have switched back to the ordinal chart. 

The Supertrend indicator is a custom made indicator. Please see the screenshot below, I have loaded the same Supertrend indicator twice. 
![supertrend](https://i.gyazo.com/a290dc0f1ac942e919477823602a2a86.png)
The only differences between the two versions are their spacing from the price bars and their plot style. One is a "line" plot, while the other one is a "marker" plot. The marker plot doesn't have any issues; it seems the line plot is bugged due to the right indentation.

**Comment by pathvine** [comment]
@Shestac92 
I would like to add that besides the spacings among the OHLC and candlestick bars become further apart, it seems the right indentation breaks line chart, as shown in the screenshot below. The price plot in cyan line stops showing up for the live data, the green line of the Supertrend indicator stops showing up for the live data as well. The Supertrend indicator in marker works fine.
![line plot](https://i.gyazo.com/cfe4062dfb81549fea7983158b566845.png)

**Comment by Shestac92** [comment]
@pathvine 
Unfortunately, we didn't succeed to reproduce the same issue using built-in technical indicators. Please, can you provide us a sample with Supertrend indicator to let us investigate the issue?

**Comment by pathvine** [comment]
@Shestac92 
Hey Shestac! Although the Supertrend is a common indicator with its equation available online, I have mixed in some proprietary code within this indicator. Hence, I cannot post this indicator publicly.

The good news is, I am able to replicate the issue with the built-in EMA indicator that comes with the Anychart. Please see below for the screenshot.
![ema](https://i.gyazo.com/26b70c96a75ff528c44dee22d2be92d6.png)

To replicate this issue, the following three conditions need to be met:
1. There must be a maximum gap/minimum gap set on the chart. The screenshot shown has maximum gap set.
2. There must be "live" data so that the bars and indicators on the chart updates dynamically. On the screenshot, the live data is loaded on the chart dynamically but the live updated price bars are shown with "odd spacing", the price bars are further apart than normal.
3. The indicator must be a "line" plot. The screenshot shows the 20-period EMA in line and 50-period EMA in markers. The exact issue is that the odd spacing mentioned above breaks the indicator in line plot, while the marker plot doesn't have this issue. This is because the markers are discrete and the line is continuous; the odd spacing from the live updated data causes the line "to break" and stop showing on the chart.

**Comment by Shestac92** [comment]
@pathvine 
Great! Thank you for the detailed description, we will use this report in to fix the issue. Yes, it seems that all these issues come from using extended gaps.
I will update you when the fix becomes available.
Thank you for your report!

**Comment by pathvine** [comment]
@Shestac92 Thanks! Will look forward to the update.

**Comment by sturdystablestalwart** [comment]
This behavior is a consequence of the method being designed to support the use of only static data. While the additional method was not added, there is a way to achieve this empty gap on the right side; it's shown in [this sample](https://playground.anychart.com/nws7RVU6). You could still use the `maximumGap()` method, but it would require additional manipulations as shown in [this sample](https://playground.anychart.com/HnPcpa33).
If you have any additional questions or requests, I'm here to help.
