### ISSUE TITLE
How to Get Rid of  titleFormat from tooltip in GanttChart

### ISSUE THREAD

**Issue by SwardCoder** [AnyChart/AnyChart#84]
Hi recently when i was trying examples of AnyChart using Ghantt i tried few examples 
and when i tried to customize my tool tip it was showing titleFormat default as Legends 
so i had to make them as empty using the following code 
```
  this.chart.getTimeline().tooltip().titleFormat(function() {
            return '';
        });
```
for normal title i am able to use format function and its working fine 

but the problem is still one blank line is displayed 
so how can i eliminate this line 

![image](https://user-images.githubusercontent.com/50729228/58694648-2a154d80-83b1-11e9-9337-359f360b57ce.png)

**Comment by imaximova** [comment]
@SwardCoder, you can disable the tooltip title and separator by writing this:
var timeLine = chart.getTimeline();
var tooltip = timeLine.tooltip();
tooltip.title(false);
tooltip.separator(false);
Please check the sample I prepared: https://playground.anychart.com/lpnR8BG3
Learn more about the tooltip formatting here: https://docs.anychart.com/Common_Settings/Tooltip#formatting

**Comment by SwardCoder** [comment]
@imaximova  thank you :)
