### ISSUE TITLE
unable to reEnable tool tip once disabled in Gantt Chart

### ISSUE THREAD

**Issue by SwardCoder** [AnyChart/AnyChart#85]
Hi Friends
Recently when i was working on **anychart.charts.Gantt**  i was using 
format() method to show tool tip like 

this.chart.dataGrid().tooltip().format(function () {
// based on some condition i am generating the tool tip text and assigning to variable and returning it 

but some times i should not show tool tip based on some condition 
so i used like this 

this.chart.dataGrid().tooltip().enabled(false);

like 
```
if(x === null)
{
// i am disabling the tooltip
this.chart.dataGrid().tooltip().enabled(false);
} else {
// i am enabling the tooltip
this.chart.dataGrid().tooltip().enabled(true);
}
```

so it is Disabling the tool tip but it is not reenabling the tool tip even if it goes to else block the next time 

so please suggest me is there any other methods like hide tool tip etc., 

and also some times 
**this.chart.dataGrid().tooltip().enabled(true);** is coming as null in Format method 
please help me with your suggesion

**Comment by Shestac92** [comment]
@SwardCoder 
This approach doesn't solve the issue because once the tooltip was disabled the tooltip's formatter is never called again.
We can suggest you [the approach described in the sample](https://playground.anychart.com/I8QHzvsk).

**Comment by SwardCoder** [comment]
@Shestac92  thank you the approach suggested by you worked 
Cheers you Rock :)
