### ISSUE TITLE
anychart.charts.Gantt  zoomTo(StartTime, EndTime) not Updating

### ISSUE THREAD

**Issue by SwardCoder** [AnyChart/AnyChart#87]
hi i have a scenario like the zoomTo function is called several times 
when i call it as 
where as startTime and EndTIme are time stamps
 anychart.charts.gantt.zoomTo(startTime, EndTime)

this is updated few times based on my calls 
but its not getting refreshed once i update startTime and EndTime 
is there any other method which i need to call before or after this statement to make sure ZoomTo is Updated and keep live?

Please help me

Please Note: i have more than one Gantt chart so the first one is working fine but second one is not working as expected so is that causing the problem ?

**Comment by Shestac92** [comment]
@SwardCoder 
If I got your idea correctly you call zoomTo once and then just update the `startTime` and `endTime` variables. If so, you should call `zoomTo()` with new timestamps every time you need to execute zooming. 
If I got it in the wrong way, please, describe in details the scenario.

**Comment by SwardCoder** [comment]
yes this answers my question thank you
