### ISSUE TITLE
Unable to override tooltip style

### ISSUE THREAD

**Issue by OhioGuy67** [AnyChart/AnyChart#88]
My Angular 7 application uses Sass so my styles are stored in .scss files (these support normal CSS commands but also add additional capabilities).  If I follow the instructions on https://docs.anychart.com/Common_Settings/Tooltip to try to override the default tooltip style, no change is occurring (specifically I'm changing the padding to 0px).  My only recourse seems to be making the change in the anychart-bundle.min.js file (which I would prefer not to have to do since I'd have to remember to do it when I upgrade to a new version).  Is there anything else I can do to make the styling change work?

**Comment by Shestac92** [comment]
@OhioGuy67 
Are you trying to override tooltip style via CSS?
Unfortunately, the AnyChart library doesn't support styling with CSS, you should use JS API methods to adjust the tooltip appearance. Follow instructions in [the article](https://docs.anychart.com/Common_Settings/Tooltip) to adjust the tooltip appearance.

**Comment by r4cker** [comment]
It is now working. But you need to enable HTML

`chart.tooltip().useHtml(true);`
