### ISSUE TITLE
Preloader not showing in chart but whole screen.

### ISSUE THREAD

**Issue by sky7st** [AnyChart/AnyChart#90]
I'm using anychart with vue.
I've tried the default preloader which is like below:

`<div class="chart" id="chart"></div> `

in init function:

init(this.$el)

```
function init (el){
    .......
    chart.preloader.render(el);  
    chart.chart.container(el);
}
```

What I expect is the loading animation should only show in the chart div.
But the loading animation actually shows in whole screen.
Is it available to show preloader just in the chart div?

BTW can I design my custom preloader?

**Comment by Shestac92** [comment]
@sky7st 
Yes, you can define the exact element for rendering the preloader and create your custom preloader. In [the docs article](https://docs.anychart.com/Common_Settings/UI_Controls/Preloader), you can find a code snippet for these options.
Also, you can override CSS of the default preloader. In the `anychart-ui.css` search for the `.anychart-loader` class.
