### ISSUE TITLE
Date format question

### ISSUE THREAD

**Issue by tr14466** [AnyChart/AnyChart#91]
![s](https://user-images.githubusercontent.com/53610056/63314626-e2142000-c33a-11e9-9d52-dec3c78254ab.png)

Hello,I have a question.
1. 2016 Dec 24 change to 2016-12-24
2. Dec 24 change to 12-24 or 12 24
How to modify the date format in the graph

Thanks.

**Comment by Shestac92** [comment]
@tr14466 
You can achieve that using format() function. I have modified the sample (lines 29-32) - https://playground.anychart.com/UWQdN4Ru/2

You can learn more about formatting labels in [the article](https://docs.anychart.com/Axes_and_Grids/Axes_Labels_Formatting#formatting_labels). 
And about format() function in [the API](https://api.anychart.com/anychart.core.ui.LabelsFactory#format).

**Comment by tr14466** [comment]
> @tr14466
> You can achieve that using format() function. I have modified the sample (lines 29-32) - https://playground.anychart.com/UWQdN4Ru/2
> 
> You can learn more about formatting labels in [the article](https://docs.anychart.com/Axes_and_Grids/Axes_Labels_Formatting#formatting_labels).
> And about format() function in [the API](https://api.anychart.com/anychart.core.ui.LabelsFactory#format).

Ok,Thank you.
