### ISSUE TITLE
the weekend problem in anystock

### ISSUE THREAD

**Issue by hwt9520** [AnyChart/AnyChart#92]
because in weekend there is nothing , so in anychart it draw blank
 how to remove the weekend blank problem?

**Comment by Shestac92** [comment]
@hwt9520 
I guess you are using `scatter` scale mode. You can remove this setting to roll-back to the default `ordinal` mode. In the ordinal mode, the blank days are missing. For details, check [the sample](https://playground.anychart.com/i2ZhFhmh).

**Comment by hwt9520** [comment]
ok got it good job!
