### ISSUE TITLE
touchstart & mousewheel

### ISSUE THREAD

**Issue by hwt9520** [AnyChart/AnyChart#93]
how to fix the : Add non-passive event listener to a scroll-blocking event
????

**Comment by Shestac92** [comment]
@hwt9520 
I'm afraid I didn't get your idea. Please, can you describe in details what you want to achieve and what issue you faced?

**Comment by hwt9520** [comment]
I use chrome... but core.js always give me this tip:

anychart-core.min.js:69 [Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

anychart-core.min.js:69 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

<img width="542" alt="捕获" src="https://user-images.githubusercontent.com/3006155/63416315-bc485300-c3ee-11e9-9ff1-12b9119f0c6a.PNG">

I have added code like this:

                this.$nextTick(() => {
                    document.getElementById(IDname).addEventListener('touchstart', fn, { passive: true })
                })
                this.$nextTick(() => {
                    document.getElementById(IDname).addEventListener('mousewheel', fn, { passive: true })
                })

but nothing changed.... how to write the correct code???

**Comment by Shestac92** [comment]
@hwt9520 
Ok, what exactly do you want to achieve by adding the code you provided?

This is not an error, the library requires these listeners for the proper functioning. So there's no need in overriding this behavior.

**Comment by hwt9520** [comment]
ok, thank you
