### ISSUE TITLE
Line and Area in StockChart used chart.xScale().mode('continuous')

### ISSUE THREAD

**Issue by tr14466** [AnyChart/AnyChart#94]
Hi,
chart.xScale().mode('continuous') cannot be used for line and area in StockChart.
How to configure.
![s1](https://user-images.githubusercontent.com/53610056/63396839-118a6180-c3fb-11e9-85e1-03d10632e8e2.png)

**Comment by Shestac92** [comment]
@tr14466 
The `continious` mode is defined for the Cartesian scale class, the StockCartesian scale doesn't support this mode. 
This gap is half of a point width, it is reduced with the point width while zooming out. Unfortunately, this behavior can't be overridden.

**Comment by tr14466** [comment]
> @tr14466
> The `continious` mode is defined for the Cartesian scale class, the StockCartesian scale doesn't support this mode.
> This gap is half of a point width, it is reduced with the point width while zooming out. Unfortunately, this behavior can't be overridden.

Thank you.

Feedback:
The current version of user's guide is inconvenient to use. I think it's still version 1.9.0 user's guide friendly.
![s2](https://user-images.githubusercontent.com/53610056/63410572-2fb98700-c426-11e9-86e9-151ad4e26a7f.png)
