### ISSUE TITLE
how to find the chart's name?

### ISSUE THREAD

**Issue by hwt9520** [AnyChart/AnyChart#95]
if I refresh the candle data I need to :

tablename.remove();
tablename.addData(candleData);

I need to know the tablename
 but when I do this with vue mounted function
<img width="945" alt="捕获" src="https://user-images.githubusercontent.com/3006155/63417690-47c2e380-c3f1-11e9-8439-e92040cabf76.PNG">

the vue component automatically give the tablename......

so if there is another way to remove() and addData()???

**Comment by Shestac92** [comment]
@hwt9520 
You always have access to the table by the variable that stores the table. You can name the variable as you need.
But I'm afraid I didn't get your idea about the table name. If so, please, describe in details the issue and the scenario.

**Comment by hwt9520** [comment]
You always have access to the table by the variable that stores the table. You can name the variable as you need.

so..I can name the table and data out of vue , and when need to refresh the data, refresh the table?

I only want to set the charts update automatically... I use it in a lazy way ...  all write in vue
I get what you said... I will try 

thank you
