### ISSUE TITLE
Right-click graphics

### ISSUE THREAD

**Issue by tr14466** [AnyChart/AnyChart#96]
Hi,Can the red area always be displayed when you right-click on the graph? It doesn't disappear until the next click on the graph.Or double-click to fix Crosshairs
![ss](https://user-images.githubusercontent.com/53610056/63634225-f54e2500-c685-11e9-8141-19417fa5f108.png)

**Comment by Shestac92** [comment]
@tr14466 
When the context menu is displayed the cursor focus is on the menu, not the chart. Because of that, the crosshair is not active at that moment. Unfortunately, there's no possibility to override this behavior.

**Comment by tr14466** [comment]
> @tr14466
> When the context menu is displayed the cursor focus is on the menu, not the chart. Because of that, the crosshair is not active at that moment. Unfortunately, there's no possibility to override this behavior.

Ok.
Thank you!
