### ISSUE TITLE
Border collapse in heat map chart?

### ISSUE THREAD

**Issue by Dong-Nhan** [AnyChart/AnyChart#98]
Hi guys, I just wonder if there is any option to configure the border collapsing of cells in heat map chart? Thank you
![image](https://user-images.githubusercontent.com/29725561/63766098-a6f28d80-c8f4-11e9-99bb-947b81c5f8e3.png)

**Comment by Shestac92** [comment]
@Dong-Nhan 
Hello, you can adjust it using chart Grids like this:
```
  chart.xGrid(true);
  chart.xGrid().stroke('black', 5);
  chart.yGrid(true);
  chart.yGrid().stroke('purple', 10);
```
For details, check [the sample](https://playground.anychart.com/UIHhG45l).

**Comment by Dong-Nhan** [comment]
Hi @Shestac92 
Thank you for your reply. xGrid and yGrid are good options but it would make the grids visible all the time. In my case, I wonder if I could make the borders of adjacent cells to be collapsed in every states?
You could see the not-collapsed borders in the picture below
![image](https://user-images.githubusercontent.com/29725561/63847225-90613a80-c9b7-11e9-94b0-ce1952fe64d7.png)

**Comment by Shestac92** [comment]
@Dong-Nhan 
In this case, you can adjust point stroke settings. I think this will help you:
```
  chart.normal().stroke("gray", 5);
  chart.hovered().stroke("gray", 8);
  chart.selected().stroke("gray", 10);
```
For details, check [the modified sample](https://playground.anychart.com/dKdNDeMn).

**Comment by Dong-Nhan** [comment]
@Shestac92 
Thank you. Using the smaller point stroke in normal state and larger point stroke in hovered and selected state would make the non-collapsed borders less obvisous. 
Here is [my modified sample](https://playground.anychart.com/XjFzvZiH). 

By the way, I think it's hard to make the borders to collapse the same way as I want (also the way that _border-collapse_ CSS property does) because AnyChart draws each cell individually. Would love to hear your opinion on this.

**Comment by Shestac92** [comment]
@Dong-Nhan 
Unfortunately, the current version doesn't provide any solution to replicate the behavior of border-collapse CSS property.
