### ISSUE TITLE
plot controls hidden/show

### ISSUE THREAD

**Issue by tr14466** [AnyChart/AnyChart#99]
Hi
"anychart-plot-controls{visibility: hidden};"
Can only use css?
Can't use js to control?for example：chart.plot(0).xxx hidden;
![sssss](https://user-images.githubusercontent.com/53610056/63906088-02359480-ca49-11e9-8c9f-959f4932b222.png)

**Comment by Shestac92** [comment]
@tr14466 
Unfortunately, changing Up/Down/Maximize buttons is available only via CSS overrides.

**Comment by tr14466** [comment]
> @tr14466
> Unfortunately, changing Up/Down/Maximize buttons is available only via CSS overrides.

Ok,thank you
